### ISSUE TITLE
Include new logging module in data platform python apps

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#1036]
List all components that are part of the pipeline and add the Data platform logger and emit logs. 

The components might include Api, Lambda, Glue script, s3 buckets , event bridge notification  etc

**Comment by bogdan-mania-moj** [comment]
List of components:

- API Gateway
- Lambda
- API Gateway Authoriser
- Lambda
- Athena
- Glue
- S3
- S3 object creation event trigger
- Athena trigger
