### ISSUE TITLE
🗣️ Get user feedback from data-platform-support for AP

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#1091]
Reach out for feedback on support channel and ask questions on how our users are finding using issues.
Questions around
- Are people not reaching out for support at all because it’s too much hassle
- Are they able to self help via guidance or R and Python channels
- how could we improve
- are the notifications sufficient e.g. from GitHub or do we need to reply in slack.

**Comment by alex-vonfeldmann** [comment]
This may be not in scope for the DP and just be AP BAU - I can't really tell - but would this epic also want to look at what users would prefer as a support model going forward, given that we want to move away from the GitHub Barrier for DP users? For example: we could explore whether they like the mixture of ticketing system and scoped self help channels in principle?

**Comment by bagg3rs** [comment]
@alex-vonfeldmann yes but AP is part of DP and this as mentioned can feed into what we could do in the future. We have users and a system so we can start with them and then once we have a DP we can research the 🎨 of the possible etc
