### ISSUE TITLE
⬆️ Upgrade OpenMetadata to latest Version

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1092]
New version of Open Metadata introduces some useful features including additional data quality metrics and a simplified search view.

As such, we would like to carry out an update on OMD and test out the new features.

Definition of Done:
[ ] - OMD is upgraded to latest version (while remaining in open-metadata cluster for now)
[ ] - New FQDN has been set up for it.

**Comment by jacobwoffenden** [comment]
This will be completed in https://github.com/ministryofjustice/data-platform/issues/1191
