### ISSUE TITLE
Data Product Versioning - implementation

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#1107]
Technical implementation of the initial agreed strategy for versioning a data product. See confluence page https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4479156541/Versioning+data+products#User-Scenarios

**Github discussion for implementation plan** 

https://github.com/ministryofjustice/data-platform/discussions/1520

**Comment by murdo-moj** [comment]
I'd imagine this would be part of creating an endpoint called `/edit_data_product`
