### ISSUE TITLE
Import AirFlow Pulumi Components into Terraform

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1232]
At the moment, Pulumi Airflow stack is non-deployable due to issues with AWS provider. In order not to expand effort into a tool that we're looking to retire, we'd like to use this as an opportunity to cross-train new team members and import the existing infrastructure into Terraform. 

Definition of Done:
- [ ] Identify infrastructure components currently managed by Pulumi
- [ ] Create terraform code for identified components
- [ ] Import existing components into terraform state
- [ ] Define tfvars files for dev and prod
- [ ] Retire Pulumi infra

**Comment by Gary-H9** [comment]
This work will be encapsulated in [this](https://github.com/ministryofjustice/data-platform/issues/1625) Epic going forward.
