### ISSUE TITLE
💨 Import Airflow Dev EKS Cluster and Associated Structures into Data Platform Terraform

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#1239]
To help decompose [the overall ticket](https://github.com/ministryofjustice/data-platform/issues/1232) into more manageable chunks, this ticket looks to cover the EKS related architecture for Airflow, and the process of moving it from management by pulumi into terraform. The list of expected resources is:

- [x] The Airflow Dev EKS Cluster (airflow-dev)
- [x] It's associated role (airflow-dev-eksRole-role-211908c) and the role policy associated with it.
- [ ] The OIDC Sign-In Provider (arn:aws:iam::593291632749:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/59429428EBABBB9F911A173D7B8E8179)
- [ ] The Kube Config Map (kube-system/aws-auth)
- [x] The Cluster Ingress and Egress Security Group Rules (sgrule-2930057320, sgrule-1315910622)
- [x] The Node Ingress and Egress Security Group Rules (sgrule-3981850410, sgrule-642024298, sgrule-2433734164)
- [x] The node groups (high-memory, standard), and their associated labels and taints
- [ ] The Namespace and Helm Chart for Kube2iam
- [ ] The Namespace and Helm Chart for the Cluster Autoscaler
- [ ] The Namespace and Helm Chart for Kyverno, as well as it's rule configurations
- [ ] The Namespace, Role, and Role Binding for MWAA/Airflow

For a full list, please consult [this document](https://files.slack.com/files-pri/T01066BNN9G-F05NHLM0936/dev.txt).

For each, the resource should be defined in the Data Platform repo according to its current state (per the AWS console, as this may be disjointed with the state in pulumi code), and imported to the stack so it can be managed via terraform plan/apply.

**Comment by Gary-H9** [comment]
Created [this](https://github.com/ministryofjustice/data-platform/issues/1410) ticket to cover the production section of this work.

**Comment by Gary-H9** [comment]
I believe the Cluster Ingress and Egress Security Group Rules + Node Ingress and Egress Security Group Rules are defined in this file [eks.tf](https://github.com/ministryofjustice/data-platform/blob/main/terraform/aws/analytical-platform-data-production/airflow/eks.tf) so I'm ticking those off as done.
