### ISSUE TITLE
Adopt performance hub account

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1247]
## Problem 

There is a free floating AWS account (677012035582) which was created for the Performance Hub which has recently come under the data platform area.  It is not currently in our list of owned/managed accounts. 

##  Context 

The AWS account was created pre mid-2021 and is used by various data pipelines for the HMPPS Performance Hub.  Pipelines in AP write to arn:aws:iam::677012035582:user/land-access-user. 

## Proposed solution

Let’s bring 677012035582 into the list of accounts we manage until we can find the time and approach that would allow us to remove  the need for it entirely.  In the meantime at least it would be following our security practices and integrated with our IAM/SSO.

## Documentation needs

Produce an ADR about the adoption of the account 

Ensure the account number is recorded alongside documentation for other accounts (such as 593291632749). Wherever 593291632749 appears ensure 677012035582 is also listed

## Definition of Done

The AWS account 677012035582 is part of the AP family of accounts 

The documentation is complete

 is satisfied that nothing is broken.

**Comment by jemnery** [comment]
I'm currently migrating this account's resources to MP, so don't do anything on this ticket. We'll need to change the AP pipelines one this is done.

**Comment by Gary-H9** [comment]
👋  Hey  @jemnery - I seem to have created this but have no recollection of doing so. Does anything still need done in relation to this piece of work?
