### ISSUE TITLE
✨ Deploy 11ty to Data Platform GH pages

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#1304]
## User Story

As the Data Platform team
I want to review static site generator options
So that we can take advantage of any new documentation features.

## Value

https://www.11ty.dev/ is being investigated by quite a few teams in MoJ already. 

### Proposal

Deploy to branch and make a decision to either roll out after review/discussion with team

## Definition of done

- [ ] Deployed to branch
- [ ] Reasons to continue or not captured.
- [ ] Any additional issues raised if required

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
This is complete
