### ISSUE TITLE
Alpha API Design

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#1305]
* Take all the use cases which are included in the MVP Scope on the central miro board
* Also look at the possible endpoints on the schema versioning diagram on confluence here https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4479156541/Versioning+data+products
* Translate these use cases into modularised API endpoints
* Create a document which lists the general endpoints to create, the methods of them, and how users will call these endpoints in order to satisfy user journeys related to data product ingestion.

**Comment by murdo-moj** [comment]
Can we have something like a /data_product/dpia endpoint with get and post methods please?

**Comment by AlexVilela** [comment]
I forgot to paste the link to the page before, here it is: https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4511991882/Initial+APIs
