### ISSUE TITLE
Testing presigned url Api 

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1321]
Create a Simple curl command to make sure the presigned url functionality is working . 

Also, set up how we are going to do the smoke tests:

create a new plan_apply template to use in the data platform workflow https://github.com/ministryofjustice/modernisation-platform-environments/blob/eccbab9f34d16a1d78491452f5281970ab4ca659/.github/workflows/data-platform.yml#L47

the new workflow should run some tests, but only for the development account.

Ideally, the apply should only run for development upon completion of the terratest code

Definition of Done 
Should be able to upload the data and query in Athena

**Comment by murdo-moj** [comment]
I have a working script for this. It's not clear how this script is automated/if it is yet

**Comment by murdo-moj** [comment]
Increasing the 1000 invocations limit for lambda requires a request https://repost.aws/knowledge-center/lambda-concurrency-limit-increase

Probably not something we want to bother with

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/3346
