### ISSUE TITLE
🐶 Add technical documentation to tech-docs-monitor

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#133]
We'd like Daniel the Manual Spaniel to tell us when our docs are due for review

**Comment by bagg3rs** [comment]
https://github.com/ministryofjustice/tech-docs-monitor/pull/16 closes

**Comment by jacobwoffenden** [comment]
https://github.com/ministryofjustice/tech-docs-monitor/pull/16 merged 🚀
