### ISSUE TITLE
🧹 Tidy up Identity Providers 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1474]
Numerous ID providers (23 in total) are still in IAM for old clusters in the `analytical-platform-data-production`. 

Steps:
1. Examine the ID provider to check if it's in use
1. If it is, note this in this ticket 
1. If it isn't, taken the required action and remove it.

**Comment by julialawrence** [comment]
Please refine.

**Comment by julialawrence** [comment]
How do we handle stories where refining is basically doing. See slack.

**Comment by julialawrence** [comment]
Closed. We haven't made progress on this since Sept 11th, 2023
