### ISSUE TITLE
unit test for daap-create-metadata

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1479]
1. Automate testing of lambda containers using pytest.
2. Add daap-create-metadata/tests/ directory.
3. In tests/requirements.txt we need pytest, moto, plus the existing dependencies (boto3 and botocore).
4. In unit/tests we should create mock_test.py, similar to https://github.com/aws-samples/serverless-test-samples/blob/main/python-test-samples/apigw-lambda/tests/unit/mock_test.py
5. Since at the moment, the lambda only handles a success case (200 response)

Tasks
- [x] Update create lambda with new base image version (1.0.2)
- [ ] Test & deploy  lambda

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-platform/pull/1574
