### ISSUE TITLE
🙈 Data Protection mini discovery

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1567]
[AvF]: What are the problems we are trying to solve? 

FIRST PROBLEM 
Our users find dealing with data protection processes around data frustrating and difficult. We want to make these processes easier to use and easier to comply with. We ourselves, as a team, do not fully understand the data protection processes that our users need to comply with. We want to get into a position where we understand them so we can lobby the data protection team for improvements on behalf of our users (for example: make DPIAs discoverable), AND build in the right checks and balances into the DP ('privacy by design'). 

SECOND PROBLEM 
We, as a team, have come up with a technical concept ('data as a product') that changes the roles of current actors in our data protection user journeys. For example, we want to categorically delegate access request management to IAOs/data owners, which (for a number of good reasons) is not how this is handled today. There is no evidence that it is a reasonable expectation that IAOs/data owners will want to do this (or will be forced to do this). Additionally, we have a concept of 'derived data products', where multiple source data can come together, and where transformed data can look completely different to source data - here the single IAO ownership & authority model completely breaks down. We need to explore with different target audiences (D&A, IOAs, digital service owners, ...) what they think an access request should look like, and who they think should be considered as access request approvers in varying scenarios. 

THIRD PROBLEM
We, as a team, have come up with a technical concept ('data as a product') that encourages data users to 'request' fit for purpose data from data owners. For any new movement of data to the platform, and for any new use case of processing data on the platform, new governance paperwork (DMF, AR, DPIA...) has to be drafted, reviewed, filed. We need to understand how we can design this dialogue between user and producer as a positive experience and not cause a maelstrom of additional compliance work for data owners.

**Comment by alex-vonfeldmann** [comment]
This is a mini discovery in itself, so adding UCD stories at this point doesn't make any sense. Next step I would assume is playback of initial findings and planning of future work/deliverables, which may not map any delivery team sprint structure/schedule.

**Comment by alex-vonfeldmann** [comment]
playback https://docs.google.com/presentation/d/1xS8UU7AjZMeciGGc3XUEyIPMPHErCLlG0wCQPqVL0xU/edit#slide=id.g21ca0f94a12_2_244
