### ISSUE TITLE
🗃 Documentation

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1569]
### User Story

As a technical writer
I need/want/expect to what types of documentation I need to produce for the Data Platform
So that I know how to provide users with effective self-service support for the Data Platform

### Hypothesis

If we... [do a thing]
Then... [this will happen]

###  List of issues 
- [x] #1256 
- [x] #1305 
- [x] #1889
- [x] #2106

- [x] #2248
- [x] #3455

**Comment by MatMoore** [comment]
### List of stories
