### ISSUE TITLE
Test end to end working of data as product via api endpoint 

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1575]
## User story
As a data producer being onboarded to the platform
I want to go through the process of creating a new data product, uploading data to it, and seeing that it is there on the platform
So I can be confident the platform works for me

## Proposal
Create a series of curl commands that will fire off each of the API requests in the right order, so that we can demonstrate the journey end to end.

Doesn't necessarily need to be automated right now, we will resume work on the smoke tests/terratest later.

## Definition of done
- [x] Document the various user journeys we are covering in Alpha
- [x] The commands are documented somewhere where everyone on the team can find them easily
- [x] Keep this as internal for now, since we haven't got authentication ready yet

## endpoints with scenario tests documented in confluence
- [x] Register data product metadata `POST /data-product/register` 
    - Scenario 1 - Data product already exists :white_check_mark:
    - Scenario 2 - Invalid data product metadata json :white_check_mark:
    - Scenario 3 -  valid data product metadata that does not already exist :white_check_mark:
- [x] Create table schema `POST /data-product/${DATA_PRODUCT_NAME}/table/${TABLE_NAME}/schema`
    - Scenario 1 - schema of same name already exists for data product :white_check_mark:
    - Scenario 2 - Parent data product for schema does not exists (has no registered metadata) :white_check_mark:
    - Scenario 3 - Invalid schema json :white_check_mark:
    - Scenario 4 - Unique table name, valid schema with existing parent data product metadata :white_check_mark:
- [x] Fetch a table schema `GET data-product/${DATA_PRODUCT_NAME}/table/${TABLE_NAME}/schema`
    - Scenario 1 - data product and schema exist :white_check_mark:
    - Scenario 2 - data product doesn’t exist :white_check_mark:
    - Scenario 3 - table doesn't exist :white_check_mark:
- [x] Load data `POST /data-product/$data_product_name/table/$table_name/upload`
    - Scenario 1 - product metadata and table schema exist, data are valid :white_check_mark:
    - Scenario 2 - Data product metadata doesn’t exist :white_check_mark:
    - Scenario 3 - Table schema doesn’t exist 🚨
    - Scenario 4 - Data do not match registered table schema 🚨

For load data scenario 4 the fix will be done as part of this ticket https://github.com/ministryofjustice/data-catalogue/issues/99

For load data scenario 3 there is still some discussion around whether this scenario should reject the request

**Comment by PriyaBasker23** [comment]
![Image](https://github.com/ministryofjustice/data-platform/assets/90777804/04277423-0d7b-46ca-8462-85b51f63114d)

**Comment by MatMoore** [comment]
It looks like athena load still needs updating to pick up the new paths, which is breaking the smoketest atm. We can update this while documenting the curl commands.

I started this last week
https://github.com/ministryofjustice/data-platform/pull/1835

**Comment by MatMoore** [comment]
Created a placeholder confluence page where we can document the commands https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4557963328/Testing+user+journeys+WIP

**Comment by LavMatt** [comment]
I'm going to look at doing create a table (schema) endpoint next
