### ISSUE TITLE
Add WAF to Api

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1576]
As a developer
I want my API to follow security practices
So that the API is secure

A WAF is a security feature for an API and can be used to neutralise known attacks.

Use the configuration and basic rules as in the WAF for register my data as outlined here https://github.com/ministryofjustice/data-engineering-pulumi-components/blob/main/data_engineering_pulumi_components/aws/waf.py

**Comment by murdo-moj** [comment]
#1566

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/3490

**Comment by murdo-moj** [comment]
I've used 3 of the basic [AWS managed rulesets](https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html):

- AWSManagedRulesCommonRuleSet
- AWSManagedRulesAmazonIpReputationList
- AWSManagedRulesAnonymousIpList
