### ISSUE TITLE
:passport_control: Prototyping Data Access Interface

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#1588]
### User Story

As a…
I need/want/expect to…
So that…

### Additional Information

User Impact: Who may need data access and for what? What are their different needs and expectations.  

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by alex-vonfeldmann** [comment]
is this part of, or maybe the new, 'access to data' epic that i suggested under the 'identify.. epic'? then it needs renaming, not sure prototyping an interface is the first thing to do here
