### ISSUE TITLE
SPIKE: Investigate open_metadata ingestion methods

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#1602]
### User Story

As  a developer 
I want to be able to ingest data from my  application 
So that i can keep the catalogue uptodate with the data products created 

### Value / Purpose
This will help us to make decision on ingestion and method of ingestion whether it is a pull or push to api in open meta data 

### Additional Information
https://docs.open-metadata.org/v1.1.x/connectors/storage
https://github.com/open-metadata/OpenMetadata/pull/7984
https://www.youtube.com/watch?v=ZvA4wuvINFA

### Definition of Done

Example - 
- [ ] Create confluence page
- [ ] Create some tickets for ingestion

**Comment by seanprivett** [comment]
No longer using Open Metadata
