### ISSUE TITLE
Investigate possibility of defining column(s) to hide from the catalogue within schema

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#1605]
### User Story

As a data producer
I want to be able able to restrict what information about my data are passed onto the more widely available data catalogue
So that i may restrict access to information about more restricted/sensitive pieces of my data.

### Value / Purpose

Allow fuller control over more sensitive types of data and what's available to digest through the catalogue

### Hypothesis

If we add a flag to certain metadata items in the schema, e.g. a particular column.
Then it will not be ingested into `openmetadata`

### Definition of Done

- [ ] Document a proposal for acheiving this feature and gain agreement on possible approach.
- [ ] Should a particular approach be agreed, create more detailed issues to implement the approach.

**Comment by seanprivett** [comment]
No longer using Open Metadata
