### ISSUE TITLE
Preserve filenames and file extensions in raw data

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/analytical-platform#1618]
Currently raw data is upload with a special filename we generate, and we drop the file extension.

Instead, we should allow providers to choose the filename.

https://github.com/ministryofjustice/data-platform/pull/1549#issuecomment-1727944755

**Comment by mitchdawson1982** [comment]
Agreement to retain the file extension and maintain the filename as uuid.

**Comment by mitchdawson1982** [comment]
- [ ] Catch up with Murdo regarding this ticket.
- [ ] Filename is not currently passed in through the api as a query parameter so api endpoint terraform on mod platform needs to be updated to reflect this. [https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/data-platform/api.tf](url)
