### ISSUE TITLE
🔢  Document tooling usage on AP

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#1648]
### User Story

Find out tooling (RStudio/Jupyter Lab) usage on AP

- Daily and monthly users 
- Calculate cost per user

### Definition of Done

- [ ] Usage and costs captured

relates to #1262

**Comment by bagg3rs** [comment]
| Tool | Usage monthly logins *includes every login event | 
|--------|--------|
| RStudio | **4941** |
| Jupyter Labs | **2159** |

| Tool | Average Daily logins from 8:00 - 16:00  | 
|--------|--------|
| RStudio | **353** |
| Jupyter Labs | **138** |

Roughly 500~ users across RStudio and Jupyter in Aug 23.

**Comment by alex-vonfeldmann** [comment]
not sure this needs UCD at this point, unless there is a hidden bigger purpose (or this needs aligning with any insights from richard's tooling research)?

**Comment by bagg3rs** [comment]
✅ Removed label that Yvan applied

**Comment by bagg3rs** [comment]
Sent finding to AWS in order to justify an immersion day for Sagemaker, relates to #1262
