### ISSUE TITLE
API End point changes - Data Product operations - Register a data product (POST)

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1656]
## User story
As a data producer
I want to register a data product (including metadata)
So that it becomes available in the data catalog
And I can start to publish my data

Note: Registering the data product end point already exists. The scope of the ticket would be to update the api end point based on the new design, and add in missing checks and responses.

## API Design
https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4511991882/Initial+APIs#Data-Product-operations

POST data-product/register

accepts application/json, representing the metadata for the data product.

### Validation
- Schema must be valid according to https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/data-platform/data-product-metadata-json-schema/v1.0.0/moj_data_product_metadata_spec.json
- Data product name must contain only letters, numbers, and underscores (TBC)
- Data product name length max limit TBC
- Data product with this name doesn't already exist

### Success response
There is no response body so we should return status code 201 on success.

### Error responses
- use the standardised response functions for responses in the base image
- Return 400 response on invalid schema
- Return 400 response on invalid data_product_name
- [Return 409](https://stackoverflow.com/a/70371989/10478115) if the data product already exists

## Lambda behaviour
This already exists as create_metadata.

Double check the functionalities:

- Validate schema
- Extract name from schema
- Validate name
- Check if data product already exists
- Store the metadata in the correct path for v1: `DataProductConfig(name).metadata_path()`
- Create a folder structure for the data product (e.g. raw_data, curated_data paths)

## Definition of done
- [x] Checked/updated the new lambda
- [x] Added swagger docs
- [x] Deployed the new endpoint for API gateway
- [ ] ~~Added to the smoke test (if possible)~~
- [ ] We are able to call the endpoint to create a new data product

**Comment by tom-webber** [comment]
[Deploying new endpoint PR](https://github.com/ministryofjustice/modernisation-platform-environments/pull/3515)

**Comment by tom-webber** [comment]
[PR for updating the lambda](https://github.com/ministryofjustice/data-platform/pull/1763)

**Comment by tom-webber** [comment]
Validation testing in code appears to be outside the scope of this ticket, and handled by the [DataProductMetadata.validate() function](https://github.com/ministryofjustice/data-platform/blob/main/containers/daap-python-base/src/var/task/data_product_metadata.py#L75) ([tests here](https://github.com/ministryofjustice/data-platform/blob/main/containers/daap-python-base/tests/unit/data_product_metadata_test.py))

These specific examples will be tested through manual API testing.
