### ISSUE TITLE
API End point - Data Product operations - Update a data product (PUT)

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1657]
## User story

As a data producer
I want to update the metadata for an existing data product
So that I can change information in the catalogue
And consumers can be notified

The scope of the ticket would be to create an api end point for updating the existing data product in line with the design below. Note: this endpoint updates details about the data product. It's not to be used for data nor data schema.

### Value / Purpose

If we have this functionality we can trigger when its requested by user or delete test tables created. We can also automate this process

### Hypothesis

By having this option we will be able allow users to update the data product information when needed

## API design

https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4511991882/Initial+APIs

The end point should be PUT /data-product/{data-product-name}

It accepts application/json, representing the metadata for the data product.

### Validation

- The metadata must be valid according to https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/data-platform/data-product-metadata-json-schema/v1.0.0/moj_data_product_metadata_spec.json
- The data product must exist already (i.e. there is a metadata file for a previous version)

### Success response

- The 200 response should be a json containing the new version number. E.g. `{"version_number": "1.1"}`

### Error responses

- Return a 400 response if the schema is not valid
- Return a 404 response if no existing data product
- Return a 400 response if fields have changed that aren't allowed to be changed

## Updatable vs not updatable fields

Only specific metadata should be updatable. We haven't defined specific rules, but for the scope of this ticket any fields that wont cause issues can updated, e.g. `description`.

Note that the data product cannot be renamed, a new one must be created instead.

## New lambda functionality
- Validate the metadata against the spec (same as create-metadata lambda)
- Fetch the most recent version of the metadata
- Increment the version number, e.g. 1.0 -> 1.1
- Compare the metadata to the previous one to see what changed
- Store the metadata in the correct path for the new version

## Checklist

- [ ] add code to terraform module for api infrastructure 
- [ ] create a lambda for updating  the data product
- [ ] DataProductConfig(name).metadata_path() will need to be updated to accept a version number
- [ ] Update GitHub docs with existing versioning logic (migrate [confluence doc](https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4479156541/Data+product+Schema+Versioning) to monorepo)
- [ ] Specify which fields are editable, and implement this being respected

## Definition of Done

- [ ] Able to update a data product to a new version
- [ ] unit test changed or implemented as per new change
- [ ] ~~smoke test implemented (if possible)~~
- [ ] swagger documentation for the new endpoint

**Comment by tom-webber** [comment]
In future, could we surface the reason for upversioning a schema? e.g. 'Data Product description updated'

**Comment by MatMoore** [comment]
@tom-webber it's possible to capture this in OpenMetadata so seems like a good idea. I think there's probably a larger story there about data consumers understanding changes to data products and what it means for them.

**Comment by MatMoore** [comment]
@mitchdawson1982 just to let you know I'm picking this up now and it might cross over with your ticket since both require creating new versions https://github.com/ministryofjustice/data-platform/issues/1662

**Comment by MatMoore** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5281
