### ISSUE TITLE
Pick a Usecase and Liaise with the user

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1658]
## User story
As a developer of 'Data as Product' , I want to take a existing data and run through the pipeline 

## Value 

This approach of picking an existing use case will help in testing our design of data as product without disturbing the current floe of data 

## Additional information 
Potential users 
( Any HMPPS datasets. Need to check with users if they need any data linkage to existing dataset)

- [ ] Pathfinder 
- [ ] Use of force
- [ ] Calculate release dates 

## Definition of Done 

- [ ] Get an agreed to flow the dev data for testing in data platform 
- [ ] Get agreement for them to own the creation of their data product metadata
- [ ] Loop in the user researchers so they can talk to our users

**Comment by seanprivett** [comment]
Covered in other epic
