### ISSUE TITLE
APi End point : Display a Table schema

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1659]
The scope of the ticket would be to  create a api end point for display table schema with  path parameter  based on the document below 

https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4511991882/Initial+APIs

The end point should be ~~/{data-product-name}/{table-schema-name}/~~ see API doc above

**Checklist** 

- [x] add code to terraform module for api infrastructure 
- [x] create a lambda for displaying the table schema

**Definition of Done** 

- [x] Able to display the  schema  for the table requested in a particular data product
- [x] unit test changed or implemented as per new change
- [ ] smoke test implemented ( if possible)

**Comment by murdo-moj** [comment]
Dependency on create a table schema [#1194](https://github.com/ministryofjustice/data-platform/issues/1194)

**Comment by MatMoore** [comment]
I'm going to start mocking up the lambda & unit tests while I wait for #1194 

This could be delivered in parallel, it's just we need example schemas in the bucket to be able to test it properly.

**Comment by MatMoore** [comment]
https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4511334405/API+endpoint+creation+checklist

**Comment by MatMoore** [comment]
Swagger config will be something like this:

```json
    "/data-product/{data-product-name}/table/{table-name}/schema": {
      "get": {
        "tags": [
          "get_schema"
        ],
        "summary": "Get the latest schema for a table.",
        "description": "Returns a json object describing the table.",
        "operationId": "getSchema",
        "parameters": [
          {
            "in": "path",
            "name": "data-product-name",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "path",
            "name": "table-name",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "authorizationToken",
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation, response format https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue/client/get_table.html",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "404": {
            "description": "Data product or table schema not found"
          }
        }
      }
    },
```

might want to provide an example of the success response as well

**Comment by MatMoore** [comment]
WIP branch with empty lambda: https://github.com/ministryofjustice/data-platform/compare/dpl-1659-display-schema-lambda?expand=1

PR for new ECR repo: https://github.com/ministryofjustice/modernisation-platform/pull/5155

**Comment by MatMoore** [comment]
Note: when the new endpoint is deployed, we can remove the get glue data endpoint.

**Comment by tom-webber** [comment]
depends on ministryofjustice/modernisation-platform-environments#3588
