### ISSUE TITLE
API end point : Remove Table Data and Schema

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1662]
![Image](https://github.com/ministryofjustice/data-platform/assets/86007219/04daca8c-1e54-44ff-85b8-d2f94b868764)

### User Story

As a data producer / controller 
I need the platform to provide the ability to remove a table and all associated data
So that I can easily remove unwanted tables,  schemas and data when I no longer require them.

### Value / Purpose
With this functionality users will be able to remove tables and schemas that they no longer require. This will avoid scenarios where data that is no longer required is left in situ using resources that could otherwise be deployed elsewhere. Additionally buy automating the process we empower users, avoiding the need to log into the aws console and or requiring administrators input.

### Hypothesis
For Alpha we will delete the relevant schema and table referenced with the url path (below) when a DELETE request is received.

API Endpoint - /data-product/{data-product-name}/table/{table-name}
HTTP Verb - DELETE

### Additional Information
- All data deleted
- Major version bump required

https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4511991882/Initial+APIs

###
Key Considerations
- although a schema could in theory be loaded to s3 without data and if there’s no data then a table in athena wouldn’t exist. So probably needs to check if associated data and tables exist before trying to delete them as well as schema file
- Metadata bucket file structure 
- `/test_product/v1.2/all_types1/schema.json` this is the path to version 1.2 of the schema.json file schema "all_types1" for data-product "test_product".

# Delete Schema Checklist
- [ ] Does raw and or curated data exist
- [ ] If exists delete raw and curated data
- [ ] for each version of the data product check the metadata.json file for the existence of the schema under "schemas"
`{
    "name": "test_product",
    "description": "just testing the metadata json validation/registration",
    "domain": "MoJ",
    "dataProductOwner": "matthew.laverty@justice.gov.uk",
    "dataProductOwnerDisplayName": "matt laverty",
    "email": "matthew.laverty@justice.gov.uk",
    "status": "draft",
    "dpiaRequired": false,
    "retentionPeriod": 3000,
    "schemas": [
        "all_types1",
        "all_types2",
        "all_types3"
    ]
}`

If the schema is present delete the schema.json for the version  i.e. if deleting "all_types1":
delete `/test_product/v1.0/all_types1/schema.json`

- [ ] Remove glue table?
- [ ] Create new major version

The remove table schema should remove all the glue table and data in curated bucket. data in raw data bucket should not be removed

Checking against the data retention is out of scope 

### Checklist

- [ ] add code to terraform module for api infrastructure change 
- [ ] create a lambda for removing the table schema

### Definition of Done

- [ ] Able to remove the  schema  for the table requested in a particular data product
- [ ] unit test changed or implemented as per new change
- [ ] smoke test implemented ( if possible)

**Comment by jemnery** [comment]
It would be helpful if some of these included the use case (the "why") in the API doc
