### ISSUE TITLE
🤖 EKS Cluster Dependency Monitoring

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1699]
### User Story

TLDR; something like dependabot or renovate monitoring versions of the modernisation platform cluster.

As a… eks administrator
I need/want/expect to… be notified if a new version of the cluster node os is released (etc)
So that… I can keep the system up to date 

### Value / Purpose

Self explanatory.

### Definition of Done

- [ ] Decide on tool to monitor
- [ ] If no tool is available, create something (shell script on GH Actions to compare code to latest and raise issue if ≠)
- [ ] Decide what needs monitored 
- [ ] Monitor it

**Comment by Gary-H9** [comment]
The [endoflife](https://endoflife.date/docs/api) API may be of use here.

We should also monitor the cluster add-ons e.g. `coredns` `kube-proxy` `vpc-cni` + `aws-guardduty-agent`  
<img width="520" alt="Screenshot 2023-10-05 at 12 11 36" src="https://github.com/ministryofjustice/data-platform/assets/26419401/faa242ea-be7c-4220-bff2-574dbeeb4992">

We might need to query these with [this](https://docs.aws.amazon.com/cli/latest/reference/eks/describe-addon.html) command. 

Also we want to monitor helm charts. This can be split out to another ticket if needed.

**Comment by Ed-Bajo** [comment]
Closed for now and would be reopened of needed.
