### ISSUE TITLE
📝 New Control panel (v3.0)

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1710]
## Background 

As we all agreed ( I assume 😄 ) from last team day,  we have multiple cases for needing a User friendly UI for our end users to use the our services, e.g. 
- Information about DP for general public
- Onboarding a user to DP 
- Data product 
  - Register data product: data upload + metadata 
  - Manage (update/remove) existing data products
  - View/track the tasks
- Datasource 
  - View all the existing datasources under different data products
  - Request access 
  - Manage the access of user's data sources
- Tooling/Toolbox 
  - BI tools
  - Coding IDE: jupyter, rstudio..
  - ..
- Apps 
  -- Register an app 
  -- Manage the app's resources and access 
  --..

The above are just examples of user stories. Providing a single point for user to use DP's service will be ideal

## Current situation 
Different teams start to design/ built the UI
 - Data labs for registering data product and data uploader
 - Our team has the Control panel tool for managing some above work
 - 
## Proposal 
Using Control panel as the single point (integration) and start to communicate other teams with the idea,  gather the user stories ,  we have following doc for detail proposal (thanks @jacobwoffenden )
https://docs.google.com/document/d/1F19rzGHz18yRnf0SF5224XXgsh8uBBjaRqbug-TVADY/edit?usp=sharing

As we are talking about user stories and user flow, inevitably,  it needs to get some user research involved, but this epic is mainly for gathering existing user requirements we already have cross team , and combine them to make implementable user stories,  flows and UI design

## Alpha Scope

<img width="2011" alt="Screenshot 2023-11-06 at 13 30 06" src="https://github.com/ministryofjustice/data-platform/assets/98329494/cdc1d077-695d-498e-a76b-f98685e493d3">

## Done when 
-  Majority of user stories and related workflows are captured with reasonable detail 
-  A draft timeline and priority are decided for the user stories. 
- ?

### List of issues in this epic

- [ ]
- [ ]

- [x] #2062
- [x] #1743
- [x] #2228
- [x] #2230
- [x] #2232
- [x] #2233
- [x] #2231
- [x] #2229
- [x] #2417
- [x] #2458
- [x] #2488
- [x] #2478
- [x] #2479
- [x] #2481
- [x] #2480
- [x] #2484

**Comment by julialawrence** [comment]
Work moved to Catalogue team.
