### ISSUE TITLE
Update the user-profile endpoint for the dashboard apps using HMPPS Auth

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1711]
### User Story

As HMPPS auth team has deprecated the user-info profile endpoint `/auth/api/user/me` ,  move  to the new endpoint `/users/me`, related document is below 
https://manage-users-api.hmpps.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

we need to migrate the following apps to use new one on auth0 platform
https://github.com/ministryofjustice/bentham-app
https://github.com/ministryofjustice/intel-app-homepage
https://github.com/ministryofjustice/prison-visitor-app
https://github.com/ministryofjustice/prison-network-app
https://github.com/ministryofjustice/drug-conveyancing-app
https://github.com/ministryofjustice/safety-diagnostic-tool
https://github.com/ministryofjustice/bold-case-info-dashboard
Also we need to update the Control panel to use new endpoint for future similar apps

### Value / Purpose

To get the dashboard apps off the deprecated apis

### Useful Contacts

Adrian Straiton from hmpps auth team

### Proposal

- Investigate what is the disparity for the user-profile returned between old api and new api, the we know
- What is the impact to those dashboard sapps
- Decide whether extra api calls are required to get the full user-profile the apps need
- Manual change the related user-info javascript on Auth0 to use new api for each affected apps
- Update the cpanel to use new api-point

### The outcome from the investigation 

- Change the implementation of fetching user-profile on auth0 to use the information from JWT token rather than making extra api calls
- Limit the fields of user-profile to the fields from JWT token
- Pass the responsibility of requiring any extra information down to the app level if they need

_No response_

### Definition of Done

- [X] Implement new fetch-user-profile javascript and test on auth0 
- [X] Update the cpanel to use the new javascript
- [ ] Switch the nomis apps to use new implementation for their auth0 clients including dev and prod

**Comment by ymao2** [comment]
The conversation for how to switch on to the new api endpoint is below 
https://mojdt.slack.com/archives/C02S71KUBED/p1696845214591779

The conclusion from the above conversation 
- Change the implementation of fetching user-profile on auth0 to use the information from JWT token rather than making extra api calls
- Limit the fields of user-profile to the fields from JWT token
- Pass the responsibility of requiring any extra information down to the app level if they need


Because of the above outcome, I amended the content of ticket

**Comment by ymao2** [comment]
raised 3 github issues to the apps' owner 
1 - https://github.com/ministryofjustice/bentham-app/issues/135
2 - https://github.com/ministryofjustice/safety-diagnostic-tool/issues/44
3 - https://github.com/ministryofjustice/bold-case-info-dashboard/issues/32

**Comment by ymao2** [comment]
Waiting for the app owners to cooperate with me for rolling out the changes to prod env

**Comment by ymao2** [comment]
update:   all others have been done, only the following app is left ,
https://github.com/ministryofjustice/safety-diagnostic-tool
The app owner is planning to test app on dev (last update from her is yesterday), hopefully get the last one sorted next week

**Comment by Gary-H9** [comment]
User returned from holiday recently, awaiting reply.

**Comment by ymao2** [comment]
updated:  we tried the dev account , the profile returned was ok, but the token returned cannot be used for calling prison api and got rejected ---> to some extends, it is expected.  IMO,  it should be ok on prod, but app-owner wants to discuss more on Monday, will update it afterwards

**Comment by ymao2** [comment]
just finished the meeting,  we decided to switch to new one at 4pm today

**Comment by ymao2** [comment]
update:  sorry I forgot the 4pm switch, have to reschedule to tomorrow

**Comment by ymao2** [comment]
completed today
