### ISSUE TITLE
SPIKE: Using MWAA for Open Metadata Ingestion

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1714]
### User Story

As an engineer, I would like to investigate the use of AWS Managed Workloads for Apache Airflow to ingestion of metadata into the catalogue instead of using a self-hosted AirFlow to minimise operational overhead of maintaining another tool.

### Value / Purpose

Using a managed service instead of supporting another self-hosted tool should both improve reliability and security and reduce operational overhead.

### Proposal

As part of building out components in Modernisation Platform, we will attempt to test scheduling ingestion jobs on MWAA. If we're unable to achieve this, we will proceed to using our own self-hosted Airflow

### Additional Information

Findings of the SPIKE captured here: https://github.com/ministryofjustice/data-platform/discussions/1707

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] SPIKE completed
- [ ] Results Captured
- [ ] Follow-on stories raised

**Comment by jacobwoffenden** [comment]
https://github.com/ministryofjustice/data-platform/discussions/1707 has been closed. MWAA will not work in the way we expected, so we will use Open Metadata's built-in Airflow.
