### ISSUE TITLE
Deploy Airflow into Modernisation Platform EKS Cluster

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#1715]
### User Story

As an engineer, I would like to depoy a self-hosted Airflow into our new MP EKS cluster so we can use it to run ingestion jobs on Open Metadata.

Further, as part of the deployment, I would like to investigate the removal of basic auth as a means of authenticating with Airflow and if not possible, document how access is being protected. 

### Value / Purpose

After having considered alternative approaches (MWAA or GHA) the team has agreed on using self-hosted Airflow for scheduling ingestion jobs. This approach was chosen because it minimises work needed to configure ingestion, removes the need to write custom ingestion scripts and allows simplifies the process of automating metadata registration for newly ingested datasets.

### Hypothesis

If we use self-hosted Airflow for our ingestion jobs, we will be able to achieve automated registration with a simple API call rather than being forced to author and maintain custom ingestion recipe definitions.

### Proposal

Deploy Airflow into our new EKS cluster
Use OMD-specific AF image.

### Additional Information

Follow-on from #

### Definition of Done

- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Airflow has been deployed
- [ ] Investigation into not using basic auth has been carried out and results captured
- [ ] Design for protecting Airflow from compromise has been documented and vetted with Simon Heron
- [ ] Code has been reviewed
- [ ] Tests are green

**Comment by julialawrence** [comment]
Done simultaneously with #1717

**Comment by jacobwoffenden** [comment]
This work has been canned, we're using Open Metadata's built-in Airflow deployment
