### ISSUE TITLE
Onboarding user stories, flow and UI

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1735]
### User Story

As a user who wants to use DP's server
I wants to a Ui for me to raise my query 
once get approve, I can be onboard to DP without to much steps and I get the accesses to different tools and services based on my team and role

Extra notes:

This can be part of ticket related to IAM and Identity ticket

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by jacobwoffenden** [comment]
17/10/23 refinement: further refine after control panel exploration session (25/10/23)

**Comment by jhpyke** [comment]
@ymao2 To flesh out questions to be answered ahead of tomorrow's discussion
