### ISSUE TITLE
🧐 Implement S3 Object level logging in Cloudtrail

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#1782]
### User Story

As a developer
I need to implement a cloudtrail trail to log object level `PutObject` requests to the data buckets in the data platform
So that i can monitor api calls to those buckets in the data platform along with associated information.

### Value / Purpose

By having this functionality we will be able to track the data flow through various bucket zone ( Landing , rawhistory and curated)

### Hypothesis

This functionality will help improve the audibility of data and capture issues when failure 

### Proposal

See discussion here where decision was made to use Option 2 https://github.com/ministryofjustice/data-platform/discussions/1748

### Definition of Done

- [x] create cloudtrail trail in modernisation-platform-environments terraform for PutObject requests for source buckets with target bucket for log files being the log bucket.

**Comment by tom-webber** [comment]
Encountering a circular dependency: Need to create a bucket policy prior to creation of the cloudtrail for that bucket

solution: apply bucket policy prior to applying cloudtrail

Also we don't have the permissions to delete Cloudtrail logs withing Mod Platform.
