### ISSUE TITLE
Investigate deprecation warning in Pulumi #62

### ISSUE THREAD

**Issue by murad-ali-MoJ** [ministryofjustice/analytical-platform#1796]
We are currently get a warning of deprecation in Pulumi actions with latest versions of Pulumi AWS:

`warning: override_json is deprecated: Use the attribute "override_policy_documents" instead.`
`warning: source_json is deprecated: Use the attribute "source_policy_documents" instead.`

We don't call either of these directly (they are arguments for [getPolicyDocument](https://www.pulumi.com/registry/packages/aws/api-docs/iam/getpolicydocument/) function, but we never call them directly ourselves), so the most likely villain is `data-engineering-pulumi-components` which also calls this function in its package, and is a requirement for this repo.

**Acceptance Criteria**

- [ ] The source of the deprecation warnings is identified
- [ ] A mitigation approach is agreed and implemented

**Comment by murad-ali-MoJ** [comment]
Testing with the older version pulumi-cli, pulumi-aws, dataengineerinpulumicomponents. Still, it is showing the working message.  Request Jacob to book sometime today so we can both try to find the solution.

**Comment by julialawrence** [comment]
After a conversation with @jhpyke @julialawrence @jacobwoffenden we agreed that warnings is something that can be accepted as there will be an imminent migration to terraform. Closing
