### ISSUE TITLE
🗿 Spike: Host Static Assets

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1824]
### User Story

As an engineer
I need/want/expect to… host static assets somewhere
So that… they can be easily consumed across the business.

Some locations, such as Openmetadata will only take images (for example) from a URL. 

Liase with hosting / design team generally.

### Definition of Done

- [x] Investigate dumping on S3 or running something in Cloud Platform which can host them
- [x] Images on publicly accessible endpoint to be consumed by applications

**Comment by jacobwoffenden** [comment]
After merging #2359, #2360 and #2361, we can use a logo from a URL

<img width="1611" alt="Screenshot 2023-11-14 at 16 23 12" src="https://github.com/ministryofjustice/data-platform/assets/15148673/7de114e6-a3b8-491f-85d9-e43deb8a6289">

**Comment by jacobwoffenden** [comment]
@Gary-H9 has added them to Open Metadata, I cannot see a value in it's Helm chart to do this programatically

<img width="2032" alt="Screenshot 2023-11-14 at 16 31 27" src="https://github.com/ministryofjustice/data-platform/assets/15148673/cb036012-11de-41a4-8172-3dfabecb5371">

<img width="2032" alt="Screenshot 2023-11-14 at 16 31 39" src="https://github.com/ministryofjustice/data-platform/assets/15148673/422658fb-20fc-447f-86e3-167a8b3f6151">
