### ISSUE TITLE
:alembic: Spike: Using ADOT for Observability - Open Telemetry

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1830]
Investigate using [Amazon Distro for OpenTelemetry ](https://aws.amazon.com/otel/) for Observability.

The [repo](https://github.com/aws-observability/aws-otel-helm-charts).

**Comment by jacobwoffenden** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/11/logs-support-aws-distro-opentelemetry/ thanks @jakemulley

**Comment by julialawrence** [comment]
re-triaged. Kiling
