### ISSUE TITLE
Update Metadata product specification document in Data platform repo

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1846]
### User story
As a user i want to know about the metadata specification allowed in a data product 

### Value / Purpose
By having this the users will have idea of the meta data that needed ( required/ optional for a data product)

### Hypothesis

By having this documentation , we can give it to users for user feedback and also it help data producers to know what are possible metadata they can provide 

### Additional information 

Refactor  and move the product specification from https://github.com/ministryofjustice/data-platform-products/blob/main/data-products/_docs/product-specification.md

to data platform docs

use swagger link and Metadat reserach docs to update the documentation https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=0

**Comment by tom-webber** [comment]
[Confluence docs for implementation of metadata as we move through delivery iterations.](https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4561568040/Data+Product+Metadata+Specification)
