### ISSUE TITLE
✡️ What is the user flow for registering an app to be deployed on CP?

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1886]
### User Story

As a user of Analytical Platform
I want to be able to use the managing service offered by  DPAT team to  deploy a dashboard app on CP platform, 
And the app can 
- interact with data source (s3 bucket) through general approach or via Athena
- app can be deployed to CP 
- they can control the deployment process of the app 
- they can use the auth service (auth-proxy) and customer managements from DPAT to control the app access

### Value / Purpose
To clarify what is the path to allow the user to follow after app migration

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

- Review the current flow on Control panel 
- Review the flow we followed during app-migration 
- arrange a meeting to discuss the detail

### Definition of Done

- [x] Agree steps to onboard a new app
- [x] Map the steps to implemented processes
- [x] Identify gaps
- [x] Raise follow-on stories to implement the gaps.

**Comment by ymao2** [comment]
@julialawrence , could you please link the documentation for new app here?

**Comment by jacobwoffenden** [comment]
17/10/23 refinement: for @julialawrence to refine further

**Comment by julialawrence** [comment]
Scheduled a meeting for Wed 22/11

**Comment by julialawrence** [comment]
* Meeting output: https://docs.google.com/document/d/1S9JfeeZyGTPIVORP29IU_5mgPMqV4A7LTEK51p6tZW4/edit

* New Stories:
#2632 
#2633 
#2634 
#2635 
#2636
