### ISSUE TITLE
🔥 Decomission firebreak Open Metadata

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1894]
This ticket is to track the removal of https://github.com/ministryofjustice/data-platform/tree/main/terraform/aws/analytical-platform-development/open-metadata

Also:
- [x] `arn:aws:iam::593291632749:role/open-metadata-airflow20230623105404064900000001`
- [x] `arn:aws:iam::013433889002:role/open-metadata-airflow20230623105404064900000001`

**Comment by julialawrence** [comment]
Using the cluster for testing AzureAD integration

**Comment by jacobwoffenden** [comment]
Moving to blocked as it's being used still

**Comment by jacobwoffenden** [comment]
me and @Gary-H9 are doing this right now

**Comment by Gary-H9** [comment]
Both `open-metadata-airflow20230623105404064900000001` deleted manually (I think they were created this way) 

The guts of this task were manually removing resources then running `terraform apply`. This was completed and then we confirmed that there were no resources we missed by looking at the terraform state.
