### ISSUE TITLE
📈 Collect List of Signals for New World EKS Clusters

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1926]
### User Story

As a platform engineer
I need to curate a list of services and associated metrics
So that I can create visualisations and alarms based on sensible thresholds

### User Types

Platform Engineering

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Curate a list of AWS services and associated metrics and create dashboards and alerts in Grafana

### Definition of Done

- [ ] list of services captured
- [ ] appropriate metrics identified
- [ ] dashboards created
- [ ] alarms created

**Comment by julialawrence** [comment]
Not right now Might pick up later as part of instrumenting new platform.
