### ISSUE TITLE
🐛 Error running reset-user-efs-home

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#1942]
### Describe the bug.

There is an error when attempting to run the "Reset home directory" helm chart via the Control Panel UI. The error may be related to a failure to update the helm repo, as the sentry log shows that the "mojanalytics/reset-user-efs-home" chart is not found.

The full stack trace of the error can be found in sentry:
https://ministryofjustice.sentry.io/issues/3941226983/?query=is%3Aunresolved&referrer=issue-stream&stream_index=17

Note: in sentry there are multiple Helm related errors, that all may be linked

### To Reproduce

Log in to control panel
Go to the tools page
Click the "reset home directory" link
Reset home directory
To a user it appears it completed successfully. This is because the task is run in the background via django-channels. So check Sentry to see the stack trace of the background task

### Expected Behaviour

The task to run the helm helm chart should run successfully, and the users home directory is reset. The bug is fixed when:

the steps to "reset home directory" can be completed via Control Panel (as steps above) and there is no error reported in sentry
the [commands defined in the helm chart](https://github.com/ministryofjustice/analytics-platform-helm-charts/tree/main/charts/reset-user-efs-home) are completed. This can be checked by connecting to the rstudio tools pod and checking that the files have been moved to the backup folder (defined in the helm chart command)

### Additional context

Ticket originally captured in the Control Panel repo here https://github.com/ministryofjustice/analytics-platform-control-panel/issues/1207

**Comment by michaeljcollinsuk** [comment]
Dupliate of https://github.com/ministryofjustice/data-platform/issues/1750

**Comment by ymao2** [comment]
The root cause identified for this bug was that the name of the helm chart for `reset-user-efs-home` was released under a old name `reset-user-home` but in cpanel it uses `reset-user-efs-home`
