### ISSUE TITLE
🧪 Test Velero Backups

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1949]
### User Story

As a… engineer
I want to… run a test of our backups provided by velero on the modernisation platform cluster
So that… I have faith in the backups / can iron out any bugs or issues I'm not currently aware of 

### Hypothesis

If we... perform a recovery from backup
Then... I will successfully restore the cluster

### Proposal
Request new Analytical Platform Compute Account
Run a backup of DPAT Cluster
Restore into new Analytcal Platform Compute cluster

### Definition of Done

- [ ] Request Accounts
- [ ] Take backup in DPAT
- [ ] Restore cluster in new account

**Comment by julialawrence** [comment]
This potentially could be scored or maybe split or maybe dropped entirely.

**Comment by Ed-Bajo** [comment]
We will close this ticket and reopen when needed.
