### ISSUE TITLE
💨 Apps and Tools EKS Cluster: Create Airflow Node Group

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1950]
Spinning out of [this](https://github.com/ministryofjustice/modernisation-platform/pull/4992) PR - a node group needs to be created for the Apps and Tools cluster which sits in the modernisation platform.

This node group is needed to allow isolation between our other types of compute

**Comment by julialawrence** [comment]
Will undertake as part of new platform work.
