### ISSUE TITLE
📌 Upgrade GitHub Script action

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#1965]
Currently we are using a mixture of version `v6` and `v5.2.0` ([code search](https://github.com/search?q=repo%3Aministryofjustice%2Fdata-platform%20%22actions%2Fgithub-script%22&type=code)) but the latest (as of 17/10/23) is [`v6.4.1`](https://github.com/actions/github-script/releases/tag/v6.4.1)

The warning: 

```The following actions uses node12 which is deprecated and will be forced to run on node16: actions/github-script@211cb3fefb35a799baa5156f9321bb774fe56294. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/``` ([blog](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/) referenced)

Somehow this hasn't been picked up by Dependabot.

This ticket is to track aligning with the latest release.

Related to https://github.com/ministryofjustice/data-platform/issues/1869

# Definition of done
- [x] github scripts in workflows updated to resolve the deprecation error

**Comment by Emterry** [comment]
Bot resolved - https://github.com/ministryofjustice/data-platform/commit/37388b85d240a9e441a683a4db6115acfe433888
