### ISSUE TITLE
✨ Create a Runner Deployment that is capable of holding a long-lasting role

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#1966]
### Describe the feature request.

As part of Managed Pipelines and Modernisation's remit to move Delius/OAsys into operation via Create-A-Derived-Table, they've requested a role that has a duration of longer than the standard 1 hour in order to do so. A chain assumed role is capped to 1 hour duration, so to do this we'll need a runner that can directly assume the role in question without chain assumption.

### Describe the context.

This runner cluster will also be required to mitigate the upcoming shutdown of the existing runner cluster - however the timing with which we will need it will be accellerated by Modernisation Platform's need here.

### Value / Purpose

The value of this would be that we'd no longer be constricted by the need to chain-assume roles, and can just have roles directly available to the cluster pods. This implementation will be required for our airflow pods also, and our solution to this should be extensible to there.

### User Types

Data Engineers, Analytics Engineers

**Comment by jhpyke** [comment]
Current status:

[PR with MP to allow us to add ARC to the cluster](https://github.com/ministryofjustice/modernisation-platform/pull/5283)

[Alternernate PR to allow us to do it from MP Environments](https://github.com/ministryofjustice/modernisation-platform/pull/5284)

MP raised question of correct repo for this to live in in terms of work going forwards, currently blocked until 1 of the above can be agreed.

**Comment by jhpyke** [comment]
Underlying secrets (App ID, Install ID, and Private Key) have been stored in AWS Secrets Manager in Apps-and-tools-prod

**Comment by julialawrence** [comment]
MP are looking at moving user code to MPE repo which will help us some.

**Comment by jacobwoffenden** [comment]
Cloud Platform are providing us access to their VPC flow logs

**Comment by jacobwoffenden** [comment]
Related https://github.com/ministryofjustice/cloud-platform/issues/4983
