### ISSUE TITLE
✉️  We need to review our support mailbox access and monitoring

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#1969]
### User Story

As a Data and Analytical Platform team member
I expect that users emailing requests are responded and monitored
So that our users are not waiting for weeks without response

### Value / Purpose

Happy customers

### Hypothesis

If we as a team know who needs to respond to emails to our mailbox `analytical_platform@digital.justice.gov.uk`
Then our users will be happy in getting a response
Also should we forward this to a unified mailbox e.g. data-platform@

### Proposal

Talk about mailbox
Commit that to our WoW

### Definition of Done

- [ ] Talk about mailbox at WoW
- [ ] Updated our WoW 
- [ ] Stretched DoD - Update our TechDocs

**Comment by jacobwoffenden** [comment]
while we're at it, we should get the existing the `dataplatform@` renamed to `data-platform@`

**Comment by Ed-Bajo** [comment]
Process in placed for monitoring the mailbox.
