### ISSUE TITLE
📊 Data into SageMaker Development

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#1971]
### User Story

As a… user of SageMaker in development 
I need/want/expect to… have data available to me to perform some testing
So that… I can assess SageMaker as part of the [SageMaker spike](https://github.com/ministryofjustice/data-platform/issues/1922).

### Definition of Done

- [x] Decide what data we can use
- [ ] Edit permissions to allow it to be consumed by SageMaker in `analytical-platform-development`

**Comment by Gary-H9** [comment]
I believe @ymao2 has added this [example](https://github.com/aws/amazon-sagemaker-examples/tree/main/use-cases/retail_recommend) to the existing SageMaker domain.

**Comment by ymao2** [comment]
yes,  the data are on my s3 bucket `[dev-testing-sagemaker-yikang](https://s3.console.aws.amazon.com/s3/buckets/dev-testing-sagemaker-yikang?region=eu-west-2)`

**Comment by Gary-H9** [comment]
Closing as the rest of the spike is complete.
