### ISSUE TITLE
🐛 Slack notifications from control panel fail to send

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#1979]
### Describe the bug.

Control panel should send notifications to Slack, but these are failing since archiving the #analytical-platform channel. This means making a user a super-admin also fails

### To Reproduce

Make an action to trigger sending a slack notification e.g. changing a user to super-admin

### Expected Behaviour

The change is made and notification sent to slack

**Comment by jacobwoffenden** [comment]
Fix was to add Control Panel bot user to channel
