### ISSUE TITLE
SPIKE: investigate Versioning in openMetadata

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#2032]
## User Story
As a data consumer
I want to understand the different versions of a data product that are available
So that I can tell if I'm accessing an old version and a new version is available

## Proposal
Treat this as a spike?

We need to understand:
- how OpenMetadata represents versions of tables / schemas in the UI
- whether we can override OpenMetadata versions with our own versions when updating tables and schemas

Based on this we can decide how we represent versions of a data product within OpenMetadata, e.g.
- do we create a single schema per data product, or do we create schemas for every major version?
- do we update OpenMetatadata's version attributes whenever something changes in the data platform, or do we store the data platform version as a custom attribute?

## Definition of done
- [ ] We know how we will change entities in OpenMetadata when there is a major update to a data product
- [ ] We know how we will change entities in OpenMetadata when there is a minor update to a data product
- [ ] At least one other member of the team has reviewed the suggested approach

**Comment by seanprivett** [comment]
No longer relevant
