### ISSUE TITLE
Implement data extractor api connection in path Use of force dev data

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#2033]
### User Story
As a developer
to send data via api and test of the system i built is working 

### Value / Purpose
By having this functionality i will be able extract pathfinder dev data and pass on to the api 

### Context
The script uploading to data platform needs variables API_AUTH and DATA_PRODUCT_NAME to execute.

Use of force use the [data extractor](https://github.com/ministryofjustice/data-engineering-data-extractor) container which data engineering maintain.

Some of hmpps (use of force included) manage the helm deployment of this data extractor container from a [central helm template](https://github.com/ministryofjustice/hmpps-helm-charts/blob/main/charts/generic-data-analytics-extractor/templates/cronjob.yaml). This is where the schedule for the job is set, and where variables for the pod which is deployed using that helm template are set. API_AUTH needs to be set here as a kubernetes secret to pull down, and DATA_PRODUCT_NAME should be registered as a variable to set.

This template is used in [use of force's specific helm deployment](https://github.com/ministryofjustice/use-of-force/blob/main/helm_deploy/values-dev.yaml). Dev has some config set to extract csv files and run the data platform upload. The helm chart in dev has been manually changed to accomadate the new variables as of 31/10/23.

### Additional Information

[Current architecture of data extractor](https://dsdmoj.atlassian.net/wiki/spaces/PPDE/pages/4218552361/Data+Extractor+-+Architectural+Overview)

### Checklist 

Liaise with **Gurnank.Cheema@digital.justice.gov.uk** for PR approvals , or Dan Benton 

- [x] Register use of force as a data product
- [ ] https://github.com/ministryofjustice/pathfinder
- [x] Auth token has to be passed on to the Module. This can be manually added to Kube secrets for now for testing  
- [x]  Cronjob responsible for pulling data postgres database via  dataextractor and push data to AP https://github.com/ministryofjustice/pathfinder/blob/main/helm_deploy/pathfinder/templates/analytics-data-extractor-cronjob.yaml . Changes have to be made to args ( entry point to push data to api) only in dev environment and not to prod. 
If we pass on the code to Gareth he will be able to put in dev . Liaise with him for help 

### Definition of Done 

- [x] we push pathfinder dev data to DP as a Data product

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/hmpps-helm-charts/pull/110/files I've opened a PR in hmpps-helm-charts which I think does what we want. What I'm unclear on:

- How to properly pass the api auth to the kubernetes secret as defined in terraform in cloud-platform-environments
- **Answer**: Manually create the kubernetes secret in the use of force kubernetes cluster

What needs to be done:

- Create kubernetes secret in terraform in use of force kubernetes cluster
- Merge the changes to the helm chart templates
- Have use of force use the new helm template, and define the kubernetes secret name for the api auth + the data product name in the use of force helm values

**Comment by MatMoore** [comment]
Murdo's PR is merged now, and the secret is created. The environment variables were manually added to the kube deployment so Dan has just re-added these after merging the PR.

So I'm expecting the job to run again at midnight, and I don't think there's anything else to do, other than check that the tables with embedded newlines get moved to the fail bucket now.
