### ISSUE TITLE
📝 Make diagrams for user journeys for the new control panel

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#2058]
### User Story

As a project user
I need/want/expect all my use cases are catered for in a service
So that it's useful for me

Use the meeting notes https://docs.google.com/document/d/14NGb5D-kST3Axmc80PW8Bqzd7MYYQsn83fiwa-F7jic/edit
and any other relevant resources to create excalidraw flow diagrams to describe the user journeys which need to be captured as part of the data platform control panel GUI.

Store these diagrams in google docs for now, pending a proper area in github documentation to put them. 

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Ed-Bajo** [comment]
Work OBD.
