### ISSUE TITLE
🎛️  New Control panel : Create boilerplate and establish tech structure

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#2062]
### Background

The ticket is to establish the basic technique structure of New Control panel

### Scope

- Repo:  data-platform-control-panel
- Web framework 
- Features 
  - Login flow by using Authentication Platform (Auth0 + AAD)
  - Basic User & Permission management 
- Database storage
  - User
- UI 
- auto-testing 
- ~~Choose where the cpanel is deployed~~
- ~~Deployment related stuff~~

### Value / Purpose

Get the "empty" app ready for main feature implementation 

### Proposal 
Based on the existing Control panel with
- Python django framework 
- Login flow 
- PostgresSQL
- UI (minimum)

### Definition of Done

- [x] Repo
- [ ] Runnable code with simple endpoints
- ~~[ ] Deployed on chosen platform~~
- [ ] Runnable auto-tesitng

**Comment by Ed-Bajo** [comment]
See attached link for the User Research Catalogue user journey flow for your information - https://miro.com/app/board/uXjVNQBMdwU=/

**Comment by ymao2** [comment]
update:  we had a chat yesterday about how the app will be deployed,  a few tickets have been raised as follow-up,  so I will remove the deployment from this ticket
