### ISSUE TITLE
📊  Pull OpenMetaData metrics logs into our observability stack

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#2099]
### User Story

As a Platform
I expect to know if and how our users are using the OpenMetaData catalogue
So we can answer questions around our catalogue consumption by our users.

### Value / Purpose

Who are they? 
What do they like?
What are they looking for?
What are the top data products
What would make them come back?

### Useful Contacts

Rich

### User Types

Platform team and users

### Hypothesis

If we know how our thing is being used
Then we can make it better or shut it down

### Proposal

Pull metrics logs into #788 stack and use that information to guide our decision making and user research

### Additional Information

Metrics for OpenMetaData (1.1.x) https://docs.open-metadata.org/v1.1.x/features/data-insight

### Definition of Done

- [ ] What should we capture? what is useful?
- [ ] Can we scrape [this](https://docs.open-metadata.org/v1.1.x/features/data-insight) information from OMD into our central monitoring stack?

**Comment by julialawrence** [comment]
RIP OMD
