### ISSUE TITLE
🗃 Documentation: make it clear what exists and where

### ISSUE THREAD

**Issue by AlexVilela** [ministryofjustice/analytical-platform#2106]
### User Story

Define:
- Where should all documentation go?
   - all technical docs live in data-platform tech docs
   - user guides?
   - public documentation?
   - DPAT internal documentation?
     - Team onboarding
   - Data Platform internal documentation?
   - MoJ internal documentation?
 
- Stop using confluence?
   - migrate all relevant docs to data-platform tech docs
   - set a hard date for sunsetting confluence

- Migrate relevant docs from silver dollop to data-platform tech docs
   - set a hard date for sunsetting silver dollop

- Delete any deprecated source of information

- Shift all private sources of info into a "dump here" section in tech docs

### User Types
- DPAT team member
- Data Platform team member
- MoJ member
- Other government body member
- General public

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] All DPAT team knows where to write each type of documentation
- [ ] Existing documentation that is deprecated is no longer accessible (Confluence spaces, etc)
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed

**Comment by Gary-H9** [comment]
Superceded by https://github.com/ministryofjustice/data-platform/issues/2825
