### ISSUE TITLE
🔥 Remove `data-platform/terraform/application-migration` component from terraform management

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2150]
The whole [component](https://github.com/ministryofjustice/data-platform/tree/main/terraform/application-migration) can be removed. 

Also anything related to app migration in the [other](https://github.com/ministryofjustice/data-platform/tree/main/.github) components as well. 

Also remove the `ap_migration_apps.json` from configuration.

**Comment by Ed-Bajo** [comment]
Completed.
