### ISSUE TITLE
🐞  Add a way to lookup owner by email in OpenMetadata

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/analytical-platform#2165]
### User Story

As a data owner
I expect to specify ownership via an email address (i.e. my justice.gov.uk email)
So that I don't need to know internal data catalogue IDs

But when we create the data product, the OpenMetadata API requires we pass an ID for the owner.

So we need a way to lookup the owner id by email address. Either as a separate method, or internal to the update call. This is currently missing from the catalogue library.

### Proposal

https://github.com/ministryofjustice/data-platform/tree/main/python-libraries/data-platform-catalogue

Either add a separate method, or incorporate into the update.

If no user exists with the email, we should throw an exception so that the lambda code can reject the metadata.

### Additional Information

Until we fix this, we will be unable to set the owner via the API. In the interim we're hardcoding it to the labs team user.

### Definition of Done

 - [ ] Documentation has been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by seanprivett** [comment]
No longer relevant
