### ISSUE TITLE
🐑 Create Data Platform template repository

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2166]
### User Story

As a platform engineer
I expect all our repositories to conform to our desired standards
So that everything is harmonious

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Create template repository AND shared workflows

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Ed-Bajo** [comment]
Linked to ticket #2502
