### ISSUE TITLE
🔬 Review and scope down permissions for Open Metadata roles

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2179]
### User Story

As a platform engineer
I expect IAM polices to only have access to what they need
So that we adhere to the principle of least privilege 

### Value / Purpose

Open Metadata's IAM policy is overly permissive

```hcl
data "aws_iam_policy_document" "openmetadata" {
  statement {
    sid    = "openmetadata"
    effect = "Allow"
    actions = [
      "s3:*",
      "athena:*",
      "glue:*"
    ]
    resources = ["*"]
  }
}
```

### Useful Contacts

@jacobwoffenden

### User Types

Apps and Tools / Labs

### Hypothesis

If we scope down Open Metadata's IAM policy
Then it will only have access to the actions and resources it requires

### Proposal

identify what calls to what resources it needs per account, and adjust accordingly

### Additional Information

source:

https://github.com/ministryofjustice/modernisation-platform-environments/blob/448a84b87a4901b79377f2a087e27ca351198885/terraform/environments/data-platform/iam-policies.tf#L3-L25

### Definition of Done

- [ ] Open Metadata's role only has access to what it needs
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by seanprivett** [comment]
No longer relevant
