### ISSUE TITLE
✨ Create Analytical Platform container images

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#218]
## User Story

As a DevOps/Platform engineer, I want to control the supply chain of our container images 

## User Type(s)

DevOps/Platform engineers

## Value

We have visibility over the entire image and its contents

## Proposal

If we can use Alpine, we should look into that, but if we need to use a Debian image, it should at the minimum be

`Containerfile`:

```Dockerfile
FROM public.ecr.aws/lts/ubuntu:22.04 
```

## Definition of done

- [ ] Images provide identical functionality
- [ ] Images do not run as root
- [ ] Images pass scanning checks
- [ ] Images are signed
- [ ] SBOMs are published

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

---

## Images

| Name | Source |
|:---:|:---:|

**Comment by julialawrence** [comment]
Base images might not be straight ubuntu or debian, we might need to consume more robust base images such as rshiny, or R.
