### ISSUE TITLE
🗃️  Investigate whether we can use the OpenMetadata topology better

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/analytical-platform#2207]
### User Story

As someone browsing the catalogue
I want to be able to drill down from Data platform -> Data product -> Table
Without additional entities getting in the way

### Proposal

- Can we hide the schema level, and map each data product to a database?
- Do the new data product / data mesh features help us hide things?

### Additional Information

- Currently, we only create a single database for the whole glue catalogue
- We map data products to a schema, but this is not reflecting how the athena databases are actually set up

### Definition of Done

- [x] Checked what is possible in the UI on our current instance
- [x] Asked on OpenMetadata slack for more info
- [ ] Make an updated diagram of the OpenMetadata topology and how it maps to the data platform

**Comment by MatMoore** [comment]
Noticed there was a bug failed with the new data product feature where it is not inheriting version info, so may need to keep this in mind https://github.com/open-metadata/OpenMetadata/issues/13797

**Comment by MatMoore** [comment]
If we adopt data products, I think that implies we will need to define domains as well

It seems like any asset can be added to a data product, so we could add the tables directly to the data product, which might present a simpler model than the hierarchical database -> schema -> table.

There's not much in the way of docs at the moment, but there is this video from the release notes:
https://www.youtube.com/watch?v=6NgI_G38D0A

Maybe something like this



![Image](https://github.com/ministryofjustice/data-platform/assets/87579/f81274ad-7c17-4cbc-a1fa-806bdc817f6a)

- Database service maps to glue/athena catalogue
- Database maps to athena database
- Schema maps to default athena schema (no special meaning for us)
- Table maps to athena table
- Database/schema/table belongs to a domain
- Tables belong to data products within the domain

**Comment by MatMoore** [comment]
Some screenshots of data products within the sandbox available at https://sandbox.open-metadata.org/explore/dataProducts?sort=updatedAt&page=1&size=10

This is a tab that sits alongside the existing table view, so we could link out to it from our control panel, but it doesn't solve the problem of the UI in general being very busy

<img width="1708" alt="Screenshot 2023-11-03 at 13 33 01" src="https://github.com/ministryofjustice/data-platform/assets/87579/8691ff31-f617-43c6-bfc1-9373ff534398">
<img width="1704" alt="Screenshot 2023-11-03 at 13 33 25" src="https://github.com/ministryofjustice/data-platform/assets/87579/821551d6-793f-45be-9ab7-c67a7a84e42a">
<img width="1666" alt="Screenshot 2023-11-03 at 13 33 42" src="https://github.com/ministryofjustice/data-platform/assets/87579/0fd77775-920a-4924-adb0-a819ca2cb9bc">

**Comment by MatMoore** [comment]
Conclusion:

1. **The hierarchy is fixed and we cannot customise it**

> to answer the question of Can we customize the hierarchy, this is not possible, since it would break the foundation of the platform of following the metadata standard. We don't want to become a tool where each and every user has to decide and define the properties of each asset, but rather bring a unified language on top of which anyone can explore and build

2. Yikang is going to raise an issue upstream specifically about the glue connector mapping databases -> schemas instead of databases. This is a strange choice OpenMetadata have made in order to pull in multiple *catalogues* via one service connection. They may decide to change it or may keep the current behaviour.

3. In the meantime, @LavMatt has changed our library so that we map database <--> database when creating assets via the API. Which eliminates the issue int he short term.

4. What is visible also depends on the user's role. So when evaluating the UI we should bear in mind it may be simpler for particular user just because they can see less things. 

5. After we upgrade, we have the option to define domains and data products  in addition to the existing hierarchy to group tables. This gives us another way of viewing the metadata. I have been unable to test it on a real data product yet, but see screenshots above from the sandbox instance.

Full thread on slack: https://mojdt.slack.com/archives/C04BBJR3RPB/p1699359114286619

**Comment by seanprivett** [comment]
No longer relevant
