### ISSUE TITLE
🐛 Observability Platform Alpha Grafana unable to assume data-platform-production IAM role

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2213]
### Describe the bug.

>1. CloudWatch metrics query failed: AccessDenied: User: arn:aws:sts::319748487814:assumed-role/observability-platform-20231018120519068400000002/AWSGrafana_ASSUME_ROLE_SESSION-1699027965549 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::209019631331:role/observability-platform status code: 403, request id: e1b7590e-9303-47c2-893f-3e9ab3db9910 2. CloudWatch logs query failed: AccessDenied: User: arn:aws:sts::319748487814:assumed-role/observability-platform-20231018120519068400000002/AWSGrafana_ASSUME_ROLE_SESSION-1699027965549 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::209019631331:role/observability-platform status code: 403, request id: f397fd8f-f840-4dc7-b813-ba245adcdef5

### To Reproduce

1. Log into Observability Platform Alpha Grafana
2. Create a CloudWatch data source
3. "Save & test"

### Expected Behaviour

Data source is successfully added

### Additional context

Grafana config: https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/observability-platform/iam-policies.tf#L26-L44

Source account config: https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/data-platform/observability-platform.tf

### Bonus

[This](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/observability-platform/iam-policies.tf#L26-L44) is named incorrectly, it should be `amazon-managed-grafana-remote-cloudwatch`

**Comment by jacobwoffenden** [comment]
Bonus: [this](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/observability-platform/iam-policies.tf#L26-L44) is named incorrectly, it should be `amazon-managed-grafana-remote-cloudwatch`

**Comment by Emterry** [comment]
This is now resolved by this pr  https://github.com/ministryofjustice/modernisation-platform/actions/runs/6783237277/job/18437087282.
