### ISSUE TITLE
Authentication setup for Control Panel v3 and Data Labs API

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2231]
### User Story

As a data platform developer
We have unanswered questions
That need to be answered for us to develop the new control panel

### Proposal

Auth0 setup
- Setup new Auth0 client for new control panel 
- Setup control panel with AAD connection
- Register data labs API on auth0

Outstanding Questions

-  What iAM Identity provider do we need to create to enable this? (MP restricts 
the permissions on Idp provider)

### Additional Information

Link to overall control panel diagram can be found in [slack discussion](https://mojdt.slack.com/archives/C04M8224WCV/p1699357055872609?thread_ts=1699354812.542729&cid=C04M8224WCV)
Further flow diagram [here](https://mojdt.slack.com/archives/C04M8224WCV/p1699357182465839?thread_ts=1699354812.542729&cid=C04M8224WCV)

_No response_

### Definition of Done

- [ ] Use Terraform to setup new client for Control Panel in Auth0
- [x] Use Terraform to enable Azure AD connection with new Control Panel
- [ ] Questions from lined document resolved

**Comment by michaeljcollinsuk** [comment]
Confirmed that we will use new Auth0 tenant that has been setup in terraform

**Comment by michaeljcollinsuk** [comment]
Reference for creating new component in terraform in the [tech docs](https://technical-documentation.data-platform.service.justice.gov.uk/documentation/platform/infrastructure/terraform.html#creating-a-new-terraform-component)

**Comment by jacobwoffenden** [comment]
New Auth0 tenants have been created:

- ministryofjustice-data-platform
- ministryofjustice-data-platform-development

My suggestion is:

- ~Create a new machine-to-machine application in the new tenant(s) (same as 2OHxsZFxxRgcpZDkBHpXvgyNd0D6Ue0d in alpha-analytics-moj)~
- ~`Upload application credentials to AWS Secret Manager in analytical-platform-management-production eu-west-2 `auth0/${tenant_name}/${secret_id}`~
- ~Create a new Terraform component `terraform/auth0/${tenant_name}`~

The above was done during #1742

**Comment by jacobwoffenden** [comment]
Moving to blocked as Entra ID and client cannot be tested as we are dependent on deploying to an environment to test

**Comment by michaeljcollinsuk** [comment]
Testing with Entra ID become unblocked, which allowed us to drop using Auth0 as a middleware. Therefore we implemented authentication with Entra ID directly, this was merged in https://github.com/ministryofjustice/data-platform-control-panel/pull/35
