### ISSUE TITLE
🧭 Joint Labs/DPAT effort: Authenticate Control Panel with Labs API using M2M flow

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2233]
### User Story

Control panel should be able to call the Labs API using machine-to-machine authentication.

Control Panel:
Prerequisite:
Auth0 setup for M2M as per #2231

- call Auth0 to receive access token 
- use access token in header to call the Labs API and receive succesfull response

Labs:
 - Call auth0 to authenticate the token passed by Control Panel
 - Validate the scope returned from Auth0

Need to be able to supply token to Labs API and have it validated for execution of commands

To refine/to define

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

- [ ] M2M call between Control Panel and Labs API is tested and working

**Comment by Ed-Bajo** [comment]
See attached link for the User Research Catalogue user journey flow  for your  information - https://miro.com/app/board/uXjVNQBMdwU=/
