### ISSUE TITLE
📌Grab data products from DPR

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/analytical-platform#2267]
Digital Prisons Reporting (DPR) have a number of defined Data Products in a github repository: 

Find repository
Simple scenario scrape of data into catalogue
we don't know how many data products
spot checks rather than auto testing

**Comment by YvanMOJdigital** [comment]
https://github.com/orgs/ministryofjustice/repositories?language=&q=digital-prison-report&sort=&type=all

**Comment by PriyaBasker23** [comment]
Hi 
[@Priya Basker](https://mojdt.slack.com/team/U02BREHE1FW)

You'll have to speak to HMPPS Auth about that.
If you're after the definitions, they are all in a github-repo : https://github.com/ministryofjustice/digital-prison-reporting-data-product-definitions
This is an internal repo (unsure whether there are security issues, especially around policy definitions) so if you have access to the Moj Github organisation you can simply clone this repo.
There is just 1 in there at the moment - expect another 10-20 by the end of the year.
[13:49](https://mojdt.slack.com/archives/C065PQD5U5N/p1700660959148849)
This is the only one there : https://github.com/ministryofjustice/digital-prison-reporting-data-product-definitions/blob/main/prisons/orphanage/external-movements-1.0.0.json
