### ISSUE TITLE
📝 Update our AP guidance to clarify app deployments and responsibilities 

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#2268]
### User Story

Need to update our guidance [here ](https://user-guidance.analytical-platform.service.justice.gov.uk/shared-responsibility-model.html#user-applications) and explain what we do and don't look after.

### Value / Purpose

have a page for our users to understand what is in scope of an application being deployed.

### Definition of Done

- [ ] Documentation has been written / updated

**Comment by bagg3rs** [comment]
relates to https://github.com/ministryofjustice/data-platform-support/issues/333

**Comment by michaeljcollinsuk** [comment]
Closing as we have an [epic about the new app registration process](https://github.com/ministryofjustice/data-platform/labels/%5B%F0%9F%93%9D%20%5D%20Register%20a%20new%20app%20%28Epic%20%231700%29), that includes updating documentation about the new app registration process, that includes updating documentation

**Comment by michaeljcollinsuk** [comment]
Closing as we have an [epic about the new app registration process](https://github.com/ministryofjustice/data-platform/labels/%5B%F0%9F%93%9D%20%5D%20Register%20a%20new%20app%20%28Epic%20%231700%29), that includes updating documentation about the new app registration process, that includes updating documentation
