### ISSUE TITLE
⚰️ Kill It with Fire (Alpha Edition)

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2330]
### User Story

As a team responsible for the maintenance and upkeep of our KOPS alpha cluster, we would like to yeet it as quickly as possible. 

The last remaining app on the cluster has given their migration sign-off so the remaining blocker on fully retirement with great prejudice has been cleared.

### Value / Purpose

🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 

### Useful Contacts

@ministryofjustice/data-platform-apps-and-tools 

### User Types

Everyone 

### Hypothesis

If we destroy the old cluster, there will be much rejoicing.

### Proposal

Collect the list of resources to be destroyed and destroy them.

🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 

### Additional Information

🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 

### Definition of Done

- [x] 'Tis dead, Jim

**Comment by jacobwoffenden** [comment]
<img src="https://media1.giphy.com/media/3o84sw9CmwYpAnRRni/giphy.gif"/>

**Comment by rossjones** [comment]
Will this be broadcast on twitch?

**Comment by julialawrence** [comment]
@rossjones naturally. Paid stream. Tickets go on sale next week.

**Comment by julialawrence** [comment]
@rossjones Tis dead.
