### ISSUE TITLE
🐛 curated tables created with `extraction_timestamp` rather then `load_timestamp` as partition

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#2385]
### Describe the bug.

We've changed `extraction_timestamp` to `load_timestamp` but this has not flowed through to the curated partition folder name and as such partition columns are still named `extraction_timestamp`.

### To Reproduce

Upload a table through our api

### Expected Behaviour

partition column in tables loaded through our api is `load_timestamp`

### Additional context

Is an easy fix. The folder is created as per the defined partition column in the sql statements we use in athena_load. Just need to change this to `load_timestamp` (i think that should fix it)

https://github.com/ministryofjustice/data-platform/blob/main/containers/daap-athena-load/src/var/task/create_curated_athena_table.py#L42-L86

**Comment by MatMoore** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/4450
