### ISSUE TITLE
👤 User Request: Add iam:PassRole to Data Engineering SSO role

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2457]
### User Story

As a data engineer working in Analytical Platform, I would like to use my SSO role rather than the deprecated `restricted-admin` to run Glue jobs, however, this requires the SSO roles to have an `iam:PassRole` permission.

### Value / Purpose

Using `restricted-admin` to run Glue jobs via the console is one of the last remaining blockers to its retirement. If this is implemented, we're one step closer to users utilising SSO as a sole means of access improving the platform's security posture. 

### Useful Contacts

@julialawrence

### User Types

Data Engineers 

### Hypothesis

If we build it, they will use it. 

### Proposal

A lengthy discussion was held in a google doc, which also explains the context: https://docs.google.com/document/d/1ADCbzoEgEo2Olh_MyTExO7npEiRmA72LhJt6kc7-YKE/edit

After a discussion withe the customer, this is the agreed proposal: 
* There already exists a role called `data-first-data-science` and managed by data engineering which has the sufficient permissions to run the Glue jobs needed.
* Amend SSO data engineering permissions policy to allow `iam:PassRole` permission _specifically for the above role only_
* Request the `data-first` role have its trust policy amended if needed.

### Definition of Done

- [x] Raise a PR in `modernisation-platform` repository to add `iam:PassRole` permission restricted to the `data-first-data-science` role in the `Data Production` account. 
- [x] Test with Customer (Robin Linacre)

**Comment by julialawrence** [comment]
Code to be amended is here: https://github.com/ministryofjustice/modernisation-platform/blob/9ca87cf8c3fb441a820eaa9eda61ae4b18797e52/terraform/environments/bootstrap/delegate-access/policies.tf#L241

**Comment by murad-ali-MoJ** [comment]
The [PR](https://github.com/ministryofjustice/modernisation-platform/pull/5578) was raised to the modernisation-platform and waiting for review.

**Comment by murad-ali-MoJ** [comment]
PR has been merged.  send the message to the user.

**Comment by murad-ali-MoJ** [comment]
Get confirmation from Robin Linacre, that it is working.
