### ISSUE TITLE
📌 Version Pinning

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2477]
As per [this](https://mojdt.slack.com/archives/C04M8224WCV/p1700142428236249) discussion we want to ensure that packages in the [requirements](https://github.com/ministryofjustice/data-platform-control-panel/blob/60a36607d08e39144d452f65a257abf265fcda2b/requirements.txt#L3) file are pinned. 

### Value

Consistency: By specifying exact versions, you ensure that every environment (development, testing, production) uses the same versions of libraries. This consistency reduces the "it works on my machine" problem, where code behaves differently on different setups.

Predictability: Pinning versions leads to predictable behaviour of your application. Since you know exactly which version of each package is being used, you can be more confident that updates to dependencies won't introduce unexpected changes or bugs.

Reproducibility: For other developers setting up the project environment becomes straightforward and reproducible. Anyone cloning the repository and installing dependencies will get the same setup.

Compatibility: If your project depends on specific features or interfaces of a library that may change in future versions, pinning ensures compatibility is maintained. This is especially important for libraries that do not strictly follow semantic versioning.

Simplifying Debugging and Troubleshooting: When a problem arises, it's easier to pinpoint the issue if you know exactly which versions of dependencies are involved. Upgrading one package at a time can help isolate the cause of bugs.

Security and Compliance: For projects with strict security or compliance requirements, pinning versions ensures that only vetted and approved versions of packages are used. This can be crucial in environments where software updates undergo rigorous testing before deployment.

As to how this is done ¯\_(ツ)_/¯ 

### Definition of Done

- [x] Users cannot commit non-pinned packages in requirements files

**Comment by Gary-H9** [comment]
This is true in both the `requirements.txt` and `package.json`. Need to confirm that the DoD is satisfied.

**Comment by jacobwoffenden** [comment]
> As to how this is done ¯_(ツ)_/¯

@Gary-H9 you dropped this "\\"

**Comment by Gary-H9** [comment]
The DoD can be completed here by creating an action as illustrated in [this](https://github.com/Gary-H9/github-issues-playground/pull/3) PR. Testing was completed in the PR by adding and removing pinned/unpinned files from the `package.json` and `requirements.txt` which are in the repo (they're copies of the same files in the control panel repository).

**Comment by Gary-H9** [comment]
This was completed and implemented on the control panel [here](https://github.com/ministryofjustice/analytics-platform-control-panel/commit/e9b74be62d1cb2b31040ffbac4119d1bcae679b4).
