### ISSUE TITLE
🧪 New Control Panel: Automated  unit-testing Setup and env

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2479]
Build the following parts for auto unit testing 
-  create docker-compose for building mini local testing environment for running auto-unit tests 
-  add a few simple tests related users model for testing purpose
-  Add it as one step of flow when a PR is raised and when we publish a new docker image

Done when 
- docker-compose for testing env
- simple tests are passed
- can be triggered as part of github workflows for PR and building docker image

**Comment by ymao2** [comment]
related PR was https://github.com/ministryofjustice/data-platform-control-panel/pull/37
