### ISSUE TITLE
💂‍♂️ Setup Sentry

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2483]
ClickOps for now. 

Investigate if possible in Terraform. i.e. [here](https://blog.sentry.io/introducing-terraform-for-sentry/). If possible, add detail to this ticket then implement.

**Comment by jacobwoffenden** [comment]
Sentry team created: https://ministryofjustice.sentry.io/settings/teams/data-platform

Sentry project created: https://ministryofjustice.sentry.io/settings/projects/data-platform-control-panel

**Comment by jacobwoffenden** [comment]
Sentry is setup, but not used
