### ISSUE TITLE
✨ New simple shiny app with write-permission to another app's web-bucket  

### ISSUE THREAD

**Issue by ltd-pa** [ministryofjustice/analytical-platform#2504]
### Describe the feature request.

We're hoping the data-platform team will support deploying a new Rshiny app, with auth enabled, that will act as a simple CMS solution to another (already deployed) app (`moj-officehub-locator`). The new app would simply function to allow a select team outside of the analytical platform to read and push changes to the data behind the `moj-officehub-locator` app, though a web-form constructed in the new app. 

Key requirement:
- Support the deployment of a new shiny app, with its own auth, that can read and write to the `moj-officehub-locator` web-bucket. 
- No support required with the app development on either side.

**Comment by ltd-pa** [comment]
For additional context:

https://mojdt.slack.com/archives/C04VBJTKY58/p1700838446879359

**Comment by Ed-Bajo** [comment]
We are close to reenabling the app process. This request can be filled with a new app. No additional work required to deliver.
