### ISSUE TITLE
🧹 Check AP user EFS lifecycle policy

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#2551]
EFS storage is growing larger than it should, investigate and check [Slack Message](https://mojdt.slack.com/archives/C04M8224WCV/p1701192722781989?thread_ts=1701182741.543239&cid=C04M8224WCV) for more details and question

Should look to alert user on consumption once we know an appropriate size to keep down costs

**Comment by julialawrence** [comment]
Closed
