### ISSUE TITLE
📚Comprehensive Documentation for Repository Creation and Environment Setup

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2632]
### User Story

As an Analytical Platform Developer
I want create detailed documentation on how to create a repository from our provided template, including the steps for setting up new environments.
So that Analytical Platform App Owners can create and manage their repositories securely and successfully, in a manner that is compatible with our new application process.

### Value / Purpose

This documentation will provide App Owners with clear guidelines and best practices for repository creation and environment setup, ensuring a seamless integration with our platform's new app process.

### Useful Contacts

@julialawrence @ymao2

### User Types

Analytical Platform App Owners

### Hypothesis

If we provide comprehensive documentation for creating repositories from our template and setting up environments
Then we will enable App Owners to manage their repositories more effectively and align with the security and operational standards of our new application process.

### Proposal

Publish the documentation in the analytical platform user guide.

### Definition of Done

 - [x] Detailed documentation for creating repositories from the template and setting up new environments has been written and updated.
 - [x] Another team member has reviewed the documentation for clarity and completeness by following it.
 - [ ] Documentation published

**Comment by michaeljcollinsuk** [comment]
@julialawrence do the repo templates already exist, and if so can they be linked to the ticket? Or do we need to create the template as part of this ticket?

**Comment by julialawrence** [comment]
Link to existing template: https://github.com/ministryofjustice/data-platform-app-template

**Comment by michaeljcollinsuk** [comment]
Initial thoughts on the steps to document:

- Create new repo from the template
- Select data-platform-new-app-reg-test as the template
- Environments created as part of the template
- Go to settings > Teams > Add analytics-hq team as an Admin

NOTE: need to double check that as part of creating the repo via the template, the dev/prod environments are created

**Comment by michaeljcollinsuk** [comment]
Notes on the github env vars/secrets:

- Repo env secrets
- DEV_ECR_ROLE_TO_ASSUME - Q where is this added from? *think this comes from cloud platform PR*
- KUBE_XXX - created automatically

Repo Env Vars

- DEV_ECR_REPOSITORY - is this added by Cloud Platform PR?

**Comment by michaeljcollinsuk** [comment]
Notes on the workflow files that are created:

- Duplicate checkout steps - could 1 be removed?
- “name: Configure AWS Data Account Credentials step” - this will be redundant if the base Docker image is made public
- ACTION: Need to follow up about making the base image public with dev ops

**Comment by michaeljcollinsuk** [comment]
Note about why/how environments are copied from the template repository - from https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment:
>Running a workflow that references an environment that does not exist will create an environment with the referenced name. The newly created environment will not have any protection rules or secrets configured. Anyone that can edit workflows in the repository can create environments via a workflow file, but only repository admins can configure the environment.

When the repo is created from the template, this will include an "initial commit". This will trigger the github actions dev/prod workflows. As these reference a `prod` and `dev` environments, they are created as part of the workflows (which will fail ultimately fail as app is not ready yet). This will mean that if a user already has a repo that they created without using the template, when they copy the workflow files, this will create the environments for them.

**Comment by michaeljcollinsuk** [comment]
In future may consider creating the initial repo programatically via control panel Github integration https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-using-a-template

Could then make request to add the the `analytics-hq` team as an admin https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#add-or-update-team-repository-permissions. Note: would need to check this:
> To add a repository to a team or update the team's permission on a repository, **the authenticated user must have admin access to the repository**, and must be able to see the team

**Comment by michaeljcollinsuk** [comment]
Added new ticket to update Dockerfile documenation https://github.com/ministryofjustice/data-platform/issues/2981

**Comment by michaeljcollinsuk** [comment]
Draft PR opened: https://github.com/moj-analytical-services/user-guidance/pull/392

**Comment by michaeljcollinsuk** [comment]
Documentation has been written and reviewed, closing this as the run through of all documentation sections and deployment of docs is being tracked in https://github.com/ministryofjustice/data-platform/issues/2636
