### ISSUE TITLE
📦 Refactoring App Base Images for Public Hosting on GitHub Container Registry

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2634]
### User Story

As an Analytical Platform Developer
I want to refactor our app base images to be publicly available and hosted in the GitHub container registry.
So that we can eliminate the step of amending and providing a role with the right trust and permissions to pull from ECR, thereby simplifying the new app process for both the platform team and app owners.

### Value / Purpose

Moving our base images to the GitHub container registry will significantly reduce the overhead for the analytical platform team and simplify the process for app owners, making the app development lifecycle more efficient and user-friendly.

### Useful Contacts

@julialawrence @ymao2

### User Types

Analytical Platform Team Members, App Owners

### Hypothesis

* Since our base image repos are public and are largely based on open source rshiny distribution, making the images public will not introduce additional security concerns.
* Avoiding having to manage a role with permissions to pull from ECR hosted in `analytical-platform-data-production` will make IAM management simpler and the process of onboarding new apps easier.

### Proposal

Amend workflows that build images to push to GHCR and make packages public

### Definition of Done

- [ ] Base images have been successfully refactored and are publicly available on the GitHub container registry
- [ ] Documentation for app owners on how to access and use the new base images has been created and is easily accessible.
- [ ] The change has been documented in AP user guide
- [ ] If needed, template app repo has been amended

**Comment by michaeljcollinsuk** [comment]
I think this can be closed as already completed.

- Base image is already published to GHCR ([see config](https://mojdt.slack.com/archives/C04M8224WCV/p1701683153933089?thread_ts=1701680702.636469&cid=C04M8224WCV))
- Documentation has been published about the choice of shiny server available, and how to deploy with the OS base image https://mojdt.slack.com/archives/C04M8224WCV/p1701683153933089?thread_ts=1701680702.636469&cid=C04M8224WCV
