### ISSUE TITLE
🛠️Documenting Self-Service of Cloud Platform Namespaces for App Owners

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#2635]
### User Story

As an Analytical Platform Developer
I want to provide comprehensive instructions and sample code to enable App Owners to self-service their requests for Cloud Platform namespaces and integrate them with their GitHub repositories.
Even though the namespace creation process isn't automated yet, App Owners can navigate this essential step more easily, reducing complexity and potential confusion.

### Value / Purpose

Documenting and simplifying this process is crucial for App Owners, particularly those unfamiliar with the Cloud Platform. By providing clear instructions and example code, we aim to make the namespace configuration process more approachable and manageable.

### Useful Contacts

@julialawrence @ymao2

### User Types

App Developers new to Cloud Platform

### Hypothesis

If we provide detailed documentation and sample code for the self-service of Cloud Platform namespaces
Then App Owners will find it easier to set up and configure their namespaces, leading to a smoother integration with their GitHub repositories and a better overall experience in setting up their applications in the interim while we work to automate this step.

### Proposal

Document the process in the AP user guide and provide sample code together with instructions on how to replace placeholders.

### Additional Information

Undecided: 
* Do we provide instructions using the CP CLI or fully manually?
* Where should we store sample code?

### Definition of Done

- [x] Agreed on undecided issues listed in Additional Information
- [x] Documented the process for creating CP namespaces
- [x] Documentation and sample code reviewed by team
- [ ] Second developer validates instructions and code by carrying out the outlined process end-to-end
- [ ] Documentation and sample code published

**Comment by michaeljcollinsuk** [comment]
Could we create a PR template for this part of process? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by michaeljcollinsuk** [comment]
Initial thoughts:

- Document steps to use the Cloud Platform CLI to create initial files https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html
- Then we need to document additional changes that need to be made:
    - Github environments in ECR file
    - Add analytics-hq team to RBAC
    - More TBC

**Comment by michaeljcollinsuk** [comment]
More thoughts:

- Document steps to use the Cloud Platform CLI to create initial files https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html
- Create environment - can do this via CLI
    - Need to document naming convention for the namespace - repo name
    - The generated RBAC file needs amending - add analytics-hq team
- Create ECR repo - can do this via CLI
    - Needs amending - check this template for what needs updating https://github.com/ministryofjustice/analytical-platform-migration-scripts/blob/main/templates/ecr_template.j2
- Create serviceaccount - can do this via CLI
    - Needs manual amends - see template file used in app migration https://github.com/ministryofjustice/analytical-platform-migration-scripts/blob/main/templates/serviceaccount_template.j2
- Create the PR

**Comment by michaeljcollinsuk** [comment]
Initial draft of documentation has been added to a draft PR, and is ready for review:

https://github.com/moj-analytical-services/user-guidance/pull/392/files#diff-027575753b81752fd1558e92cf8a55110f5791ce2b3d176d71d59b76fc5cf900R73

**Comment by Gary-H9** [comment]
I've read the PR above and pushed some minor changes 
- 'app' -> 'application' 
- Capitalise Headings 
- Refactor last section for brevity

All in all I think it's great and can be merged. I'll leave this for Michael to confirm as complete on his return since it's still in Draft.

**Comment by michaeljcollinsuk** [comment]
Documentation has been written and reviewed, closing this as the run through of all documentation sections and deployment of docs is being tracked in https://github.com/ministryofjustice/data-platform/issues/2636
