### ISSUE TITLE
🤝  All Hands Support 🙌 

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#2777]
### User Story

As a Platform
I want all the team to spend some time in support
So that the team can engage with customers gain valuable learning opportunities, helping team members stay connected with user experiences and challenges and as a TEAM move forward together.

### Value / Purpose

This issue is about importance of having everyone in a team (not just the current "support team") participate in AP issues, to improve the overall support to our users.

- Improves support for our users - our team is spread across the D&A and P&A already both the `#analytical-platform-support` `#data-and-analytics-engineering` questions that come often require both teams to help give assistance.
- With a more diverse support team we can fix problems rather than just band-adding. 
- Support will be radically changing soon, how can we provide support to our new products to a much much wider audience while continuing to keep our users happy.

### Hypothesis

If we have all hands support
We improve the overall user experience for our users

### Proposal

Widen the PagerDuty rota to include all DP team members.

### Additional Information

There are many supporting articles on this approach see [here](https://zapier.com/blog/everyone-on-support/)

### Definition of Done

- [ ] Discussed as team
- [ ] Issues raised to do a workshop/session etc

**Comment by julialawrence** [comment]
@tom-webber and @mitchdawson1982 are on the support rota now. All other members of the labs team are covering DE support.
