### ISSUE TITLE
Datahub setup

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/analytical-platform#2778]
- Find out where it is deployed now
- Understand the current codebase which deploys datahub
- How are we able to see logs
- The deployment is Underprovisioned if we want to import DBT
- highlight current limitations and any red flags with existing deployment
- identify why it cant live in Cloud Platform
- Can we increase the size of the instance?

### Definition of done

- Notes on how to deploy datahub
- answer the question: can we test with this? 
- share knowledge with the team
- Have taken ownership of the DataHub instance.

**Comment by PriyaBasker23** [comment]
Datahub  url - https://datahub.apps-tools.development.data-platform.service.justice.gov.uk/

**Comment by YvanMOJdigital** [comment]
https://github.com/ministryofjustice/data-platform/issues/2454 - Closed DPAT issue, referencing mod platform

**Comment by MatMoore** [comment]
We are hosting elasticsearch using AWS OpenSearch on modernisation platform

https://github.com/ministryofjustice/modernisation-platform-environments/compare/main...feature/datahub-opensearch

**Comment by PriyaBasker23** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/tree/feature/datahub-opensearch
