### ISSUE TITLE
How do we get metadata from select few early adopters to populate catalogue

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/analytical-platform#2781]
Agree metadata set

[here's a metadata spec to ask people for](https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit?pli=1#gid=1105700365 ) (you could add to this sheet)

[Later metadata spec evolution link](https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4561568040/Data+Product+Metadata+Specification)

### To do:

- [ ] Identify 5 early adopters
- [ ] update metadata sheet to v2 and confirm fields 
- [ ] Identify simplest way of getting that on to the catalogue - followup ticket to ingest to catalog

**Comment by MatMoore** [comment]
v1.1 required fields are

  "required": [
    "name",
    "description",
    "domain",
    "dataProductOwner",
    "dataProductOwnerDisplayName",
    "email",
    "status",
    "dpiaRequired",
    "retentionPeriod"
  ],

Full list via https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/data-platform/data-product-metadata-json-schema/v1.1.0/moj_data_product_metadata_spec.json

  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the Data Product. Must contain only lowercase letters, numbers, and the underscore character.",
      "pattern": "^[a-z0-9_]+$",
      "example": "my_data_product"
    },
    "description": {
      "type": "string",
      "description": "Detailed description about what functional area this Data Product is representing, what purpose it has and business related information.",
      "example": "this data product hold lots of useful information I want to share with those who may have use for it."
    },
    "domain": {
      "type": "string",
      "description": "The identifier of the domain this Data Product belongs to. Should be one of HQ, HMPPS, OPG, LAA, HMCTS, CICA, or Platforms",
      "example": "HMPPS"
    },
    "dataProductOwner": {
      "type": "string",
      "description": "Data Product owner, the unique identifier of the actual user that owns, manages, and receives notifications about the Data Product. To make it technology independent it is usually the email address of the owner.",
      "example": "jane.doe@justice.gov.uk"
    },
    "dataProductOwnerDisplayName": {
      "type": "string",
      "description": "The human-readable version of dataProductOwner",
      "example": "Jane Doe"
    },
    "dataProductMaintainer": {
      "type": "string",
      "description": "Secondary party who is able to approve DPIA access requests, but who may or may not be legally responsible for the data",
      "example": "example.information.asset.owner@justice.gov.uk"
    },
    "dataProductMaintainerDisplayName": {
      "type": "string",
      "description": "The human-readable version of dataProductMaintainer",
      "example": "Jonny Data"
    },
    "email": {
      "type": "string",
      "description": "point of contact between consumers and maintainers of the Data Product. It could be the owner or a distribution list, but must be reliable and responsive.",
      "example": "jane.doe@justice.gov.uk"
    },
    "status": {
      "type": "string",
      "description": "this is an enum representing the status of this version of the Data Product. Allowed values are: [draft|published|retired]. This is a metadata that communicates the overall status of the Data Product but is not reflected to the actual deployment status.",
      "enum": ["draft", "published", "retired"]
    },
    "dpiaRequired": {
      "type": "boolean",
      "description": "Bool for if a data privacy impact assessment (dpia) is required to access this data product",
      "example": true
    },
    "retentionPeriod": {
      "type": "integer",
      "description": "Retention period of the data in this data product in days.",
      "example": 3650
    },
    "tags": {
      "type": "object",
      "description": "Additional tags to add.",
      "example": { "sandbox": true }
    },
