### ISSUE TITLE
Can we register data from the Data Discovery Tool [Done pending import to new environment]

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/analytical-platform#2782]
### User Story
As a data platform we want to populate a catalogue with existing metadata to gain user feedback.

### Proposal
This repo contains metadata for data engineering managed pipelines that create clones of operational databases https://github.com/ministryofjustice/data-discovery. 

The github repository contains community contributions regarding descriptions to the data held in the these databases. But there will also be (in some cases) metadata defined and saved in json files in s3.

There is some existing code that was used on a very small subset of available metadata, which scrapes the data dsicovery tool and outputs a metadata json file in the data platform format ready to be ingested via our api.

For each database in the data discovery tool you will need to create as a data product and register via the api (`data-product/register` endpoint), some metadata for this could be pulled from from the ddt where it exists (unlikely to have data owners and retention periods though) 

When a data product exists register each table metadata json via the `data-product/{data_product_name}/table/{table_name}/schema` endpoint

**Comment by seanprivett** [comment]
@LavMatt to expand on this ticket

**Comment by MatMoore** [comment]
Note: the data discovery tool sometimes has images. Datahub does allow images in descriptions, but it must be hosted elsewhere. I will see if I can preserve the images using absolute URLs.

**Comment by MatMoore** [comment]
There are some columns here that aren't representable in data platform due to complex types (list and structs) and some are missing types altogether. For now I'm just going to pass these along as string rather than skip them

Some tables are also missing metadata in s3 (e.g. nomis_dn.a_comparator_sites). I'll just use whatever we can get from the markdown in the case

**Comment by MatMoore** [comment]
work in progress: https://github.com/ministryofjustice/data-platform-metadata-to-ingest/

**Comment by MatMoore** [comment]
Scripts here in case we need to rerun: https://gist.github.com/MatMoore/05946fc2a60b93eea8b6d82251188153

This includes
1. a script to scrape data discovery tool and output json
2. a script to load from the json into datahub using the data-platform-catalogue library

I think this is correctly generating the datasets with schemas, but it's not always generating the linkages between the datasets and data products. I am doing some further debugging to work out what's going on.

We should be able to inspect the data product and the dataset from the command line like this
- `datahub get urn --urn 'urn:li:dataProduct:sop' --aspect dataProductProperties`
- `datahub get urn --urn 'urn:li:dataset:(urn:li:dataPlatform:glue,sop.starters,PROD)' --aspect datasetProperties`

I've documented various aspects that might be relevant to look at here. https://docs.google.com/spreadsheets/d/1DFks3XD1Imp_HE5Ise_ERY7X-D70b-9JqRGwjD0vQa8/edit#gid=0

I am not sure what ordering guarantees we can expect when we `emit` two events for the same entity URI and aspect. Is it possible for the earlier event to override the later one? If so there may be a race condition int he data-platform-catalogue code.

**Comment by MatMoore** [comment]
Problematic code here

```python
                assets = data_product_existing_properties.assets.append(
                    data_product_association
                )
```

Append returns None - this wipes out previously added assets from the data product

**Comment by MatMoore** [comment]
Having fixed the above, the metadata looks ok on datahub. So think we can call this done until we need to import into a new environment.
