### ISSUE TITLE
🔧 Review documentation publishing 

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2789]
### User Story

As a platform engineering
I want to ensure our documentation is tested/linted
So that links aren't broken

This work should be done as part of [this](https://github.com/ministryofjustice/data-platform/issues/2825) epic.

### Useful Contacts

@jacobwoffenden

### Proposal

Check what other tooling teams are using to test/lint/validate tech-docs

### Definition of Done

- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
We could maybe look at using [this](https://github.com/ministryofjustice/nvvs-devops/blob/main/.github/workflows/check-links.yml).
