### ISSUE TITLE
📝 Documentation Epic

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2825]
### Summary

The purpose of this epic is to improve the state of documentation for the Apps and Tools team. This activity ought to occur in three threads. 

1. At the moment there are numerous locations where things are documented. 
  a. If possible this should be reduced, with a bias towards using one technology to display documentation. This simplicity will mean less overhead in managing the documentation going forward. [(issue here)](https://github.com/ministryofjustice/data-platform/issues/2826)
  b. Document where certain types of documentation ought to be stored. i.e. if writing a process for a user this should go in X. If writing an technical document that should be created in Y by default. [(issue here)](https://github.com/ministryofjustice/data-platform/issues/2828)
  c. [Implement](https://github.com/ministryofjustice/data-platform/issues/2829) step a.
2. Review documentation.
  a. Review user facing guidance first. Ensure that guidance is correct, up to date, adds value. 
  b. Review internal documentation
  c. Prune where possible. 
3. Ensure a process is setup to ensure documentation is regularly reviewed.

### List of issues in this epic
- https://github.com/ministryofjustice/data-platform/issues/2826
- https://github.com/ministryofjustice/data-platform/issues/2828
- https://github.com/ministryofjustice/data-platform/issues/2829
- https://github.com/ministryofjustice/data-platform/issues/2833
- https://github.com/ministryofjustice/data-platform/issues/2789
- https://github.com/ministryofjustice/data-platform/issues/3069

### Other information

Discussions on documentation can be carried out in #data-platform-documentation-epic on Slack.

Additionally we ought to capture [this](https://github.com/ministryofjustice/data-platform/issues/2248) ticket in this piece of work.
- [x] #2826
- [x] #2828
- [x] #2829
- [x] #2833
- [x] #2789
- [x] #3069
- [x] #3315
- [x] #4474

**Comment by julialawrence** [comment]
Questions to address:
* P&A strategy
* Who do we align with?
