### ISSUE TITLE
📝  Documentation: Agree/Decide Technology

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2826]
As per the [epic](https://github.com/ministryofjustice/data-platform/issues/2825): 

"At the moment there are numerous locations where things are documented.
a. If possible this should be reduced, with a bias towards using one technology to display documentation. This simplicity will mean less overhead in managing the documentation going forward."

The goal of this ticket is to:
- [ ] decide which technology should be used to display documentation
- [ ] Agree on level of alignment with rest of  Data Platform
- [ ] document this decision in an ADR

**Comment by julialawrence** [comment]
Tech docs refactored and will be used for publishing.
