### ISSUE TITLE
📝  Documentation: Categorisation 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2828]
As per the [epic](https://github.com/ministryofjustice/data-platform/issues/2825):

"Document where certain types of documentation ought to be stored. i.e. if writing a process for a user this should go in X. If writing an technical document that should be created in Y by default."

Define where: 
- [ ] User facing documentation should be created.
- [ ] Platform documentation should be created. 
- [ ] Other types of documentation not mentioned here should be detailed and noted.
- [ ] All of the above should be recorded in one location to be referred to in future.
- [ ] Capture output in ADR
- [ ] Capture in ways of working

**Comment by julialawrence** [comment]
Following the principles of other teams -- runbooks: internal, user guide: external
