### ISSUE TITLE
📝 🔧  Documentation: Implementation

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2829]
After [this](https://github.com/ministryofjustice/data-platform/issues/2826) ticket any implementation work should be captured and done in this Issue.

This should include removing any old documentation sites etc.

Additional Information
This work is connected to ticket Documentation: Categorisation - https://github.com/ministryofjustice/data-platform/issues/2828

**Comment by julialawrence** [comment]
Implementation complete.
