### ISSUE TITLE
🐛 Cost Anomaly Detection in analytical-platform-data-engineering-sandbox-a

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#2834]
### Describe the bug.

We were unable to publish to your SNS topic arn:aws:sns:eu-west-2:(analytical-platform-data-engineering-sandbox-a)cost-explorer-anomaly-monitor for the alert subscription SNS Subscription. As a result, you won’t be notified of all of the anomalies that have been configured with that alert subscription. To resolve the issue, check that you’ve entered the correct SNS ARN, or follow the user guide ([https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ad-SNS.html](https://lk26fk7n.r.us-east-1.awstrack.me/L0/https:%2F%2Fdocs.aws.amazon.com%2Fawsaccountbilling%2Flatest%2Faboutv2%2Fad-SNS.html/1/0100018cdd660e23-9cdce46a-ed17-4f48-a728-36c868ca7aec-000000/FQa37hUZsHvbexobMec1f2q_Rn0=355)) to ensure the alert is set up correctly to work with AWS Cost Anomaly Detection. If you have any questions, contact us at [https://aws.amazon.com/support](https://lk26fk7n.r.us-east-1.awstrack.me/L0/https:%2F%2Faws.amazon.com%2Fsupport/1/0100018cdd660e23-9cdce46a-ed17-4f48-a728-36c868ca7aec-000000/0VqoBM69BLKKJIVZT9brEQmXtkk=355).

**Comment by Emterry** [comment]
pr in #ask-data-engineering https://github.com/ministryofjustice/data-engineering-cleanup/pull/27
