### ISSUE TITLE
🧹 AP Control Panel quality of life improvements

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#2846]
### User Story

As a developer
I need/want/expect to AP control panel to be in a good state
So that working on it is more efficient and enjoyable

### Proposal
Spend time to make a variety of improvements to the Control Panel codebase:

### Code quality
- [ ] Define linting rules and setup linting checks in CI
- [ ] Run black/isort/flake8 on whole codebase and resolve issues
- [ ] Update pre-commit checks to run linting checks
- [ ] Resolve deprecation warnings
- [ ] Resolve non failure warnings when running tests to make the test output more readable
- [ ] Clean up unused/commented out code
- [ ] Remove unused/duplicate sentry environments
- [ ] Review long term sentry failures and try to resolve

### Dev environment
- [ ] Review existing developer setup process
  - Ensure [running.md](https://github.com/ministryofjustice/analytics-platform-control-panel/blob/main/doc/running.md) is still accurate and working
  - Review unfinished docker compose instructions, update or remove
- [ ] Consider adding other ways to install local environment Dev setup
  - dev container?
  - Localstack?

### Upgrades
- [ ] Update python version to 3.11
- [ ] Update python dependencies
  - Prioritise updating moto dependency (will allow easier testing of Boto calls)
  - Consider using poetry for dependency management
- [ ] Update Dockerfile 

### Refactoring
- [ ] Improve the UI for tools
  - Admin facing UI for releasing a new tool version
  - User facing UI to make tool descriptions clearer
  - Improve tool releases page - see https://github.com/ministryofjustice/data-platform/issues/3209
- [ ] Update the way that celery tasks are used
  - Add tasks directly with Celery as per docs
  - Remove custom message broker classes etc
  - [Install celery flower to help with monitoring](https://github.com/ministryofjustice/data-platform/issues/1927)
  - Improve the Tasks List UI page
- [ ] Better way of listing App's and their owners
Context: Simon Heron requested a list of all apps and their owners. Current best options are using the API https://controlpanel.services.analytical-platform.service.justice.gov.uk/api/cpanel/v1/apps/ or query the database (via django shell). Some options to improve:
  - Update App list page could be updated to show more information
  - Admin action to export details e.g. csv download, or write to s3, or email?
  - Review the API endpoints, could add one specific for apps/owners 
- [ ] API
  Context: there is an API but it has been been actively maintained for some time
  - Review authentication
  - Review existing endpoints and permissions 

### General UI improvements 
- [ ] Review and fix language and grammar, ensuring tone, branding
  - An example of this would be the bucket message, it read a bit informal
    - > We are on the edge of hitting the limit of AWS S3 bucket (1000).
Before we implement the long term solution, could you make sure you remove the buckets you do not need any more? also make sure not create more buckets than your need, try to use sub-folders to manage different datasets rather than multiple buckets.  
- [ ] Review and fix links to Slack and user guidance
- [ ] Remove link to AP Grafana, its broken
- [ ] Remove emojis from UI, for accessibility
- [ ] Check user session length
  - Extend so that the user is not forced to log in so often?
  - Or add automatic redirect to login from the "Your session expired" page

### Definition of Done

- [x] Split into an epic
- [x] Split tasks, prioritise and create DOD for each

**Comment by jacobwoffenden** [comment]
Shall we also add to the proposal:

- [ ] Review and fix language and grammar, ensuring tone, branding
  - An example of this would be the bucket message, it read a bit informal
    - > We are on the edge of hitting the limit of AWS S3 bucket (1000).
Before we implement the long term solution, could you make sure you remove the buckets you do not need any more? also make sure not create more buckets than your need, try to use sub-folders to manage different datasets rather than multiple buckets.  
- [ ] Review and fix links to Slack and user guidance
- [ ] Remove link to AP Grafana, its broken
- [ ] Remove emojis from UI, for accessibility

**Comment by michaeljcollinsuk** [comment]
New epic has been created, with associated subtasks https://github.com/ministryofjustice/data-platform/labels/%F0%9F%94%A7%20Control%20Panel%20QOL%20%28Epic%20%233371%29

Some of these may need refining further, and prioritisation is still required.
