### ISSUE TITLE
🚚 Migrate Analytical Platform EFS

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2949]
As part of [this](https://github.com/ministryofjustice/data-platform/issues/2943) Epic migrate the EFS from Analytical Platform into respective Data Platform Apps and Tools AWS environments.

- [ ] Establish if AWS DataSync can be utilised
- [ ] Decide time to migrate
- [ ] Migrate Development
- [ ] Migrate Production

### Diagram
<img width="943" alt="Screenshot 2024-01-15 at 12 11 01" src="https://github.com/ministryofjustice/data-platform/assets/26419401/69338003-59af-4ecb-b7ba-801bed5fff3d">

**Comment by julialawrence** [comment]
Will undertake as part of new platform work.
