### ISSUE TITLE
 ✨ Create new OIDC role for GitHub runner

### ISSUE THREAD

**Issue by hemeshpatel-moj** [ministryofjustice/analytical-platform#2951]
### Describe the feature request.

As a Developer of the CJS Dashboard App
I want to connect to the Analytical Platform via GitHub Runners
So I can run an integration test which requires access to a specific bucket.

Technical notes: 
- This is the [repo](https://github.com/ministryofjustice/cjs_scorecard_exploratory_analysis) in which the GitHub runners run on and will need access to the `mojap-cjs-dashboard` bucket.
- We need an OICD role which can be assumed by a GitHub runner, that has sufficient permissions to access and read the data in the above bucket.

### Value / Purpose

So that we can run an Integration Test - improve the quality/level  of testing.

**Comment by jacobwoffenden** [comment]
Hi @hemeshpatel-moj,

I've just created a role (`arn:aws:iam::593291632749:role/github-cjs-dashboard-app`), can you give it a whirl and see what happens

Cheers!

**Comment by jacobwoffenden** [comment]
Spoken to @hemeshpatel-moj on Slack.

Will test next week and get back to us.
