### ISSUE TITLE
🔥 Remove Simulated Data Producer resources

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2959]
Simulated Data Producer is no longer used

This ticket is to delete the following:

- https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-development/resources/simulated-data-producer-rds.tf#L1-L39
- https://github.com/ministryofjustice/data-platform/tree/main/containers/daap-simulated-data-producer
- https://github.com/ministryofjustice/data-platform/blob/main/.github/workflows/platform-simulated-data-producer.yml

**Comment by julialawrence** [comment]
Closed as won't do (right now)
