### ISSUE TITLE
Spike: comparison of metadata store architectures

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#2971]
### Describe the feature request.
 Create a list of pros and cons to compare between:

* Using DataHub as our central metadata store
* Having our own custom metadata store, from which we push to DataHub

Also test the process of extracting metadata from the catalogue and document the findings, attention should be paid to the completeness and usability of the extracted data.

From this we can make an informed decision as a team to choose an architecture

Output of this investigation is a team decision on the desired architecture and an ADR which describes this.

### Describe the context.

**Points raised in 16 Jan architecture meeting**
https://docs.google.com/document/d/1_ivdiuVg3kUC6mtwa8uFbbcbOacoPP3j_6mB2U0dlaQ/edit?usp=sharing

Reference Murdo's versioning spike #2962

**Comment by jemnery** [comment]
Versioning doc: https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4666360065/DataHub+s+versioning
