### ISSUE TITLE
Complete the Frontend with functionalities working

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#2982]
### User Story
In the role of a developer, establish a frontend for presenting items within the datahub catalog.

### Value / Purpose
The primary objective is to provide users with the ability to test and progressively build the frontend.

### Hypothesis
Creating a frontend  with established standards is will help to enhance feedback collection and facilitate iterative development.

### Proposal
Here is a checklist of design-related tasks to finalise on the prototype, aligning it with the specifications outlined in 
[https://www.figma.com/file/zTOVhHRnWfxRJqH6Gr8cIc/Catalogue-sketches?type=design&node-id=206-2398&mode=design&t=pEjdb6k2pwuuHuiw-0](https://www.figma.com/file/zTOVhHRnWfxRJqH6Gr8cIc/Catalogue-sketches?type=design&node-id=206-2398&mode=design&t=pEjdb6k2pwuuHuiw-0)

- [x] Ensure links have the govuk-link class.
- [x] Modify filters to include the desired options when initially presented to users (e.g., domain, data product).
- [x] Integrate pagination buttons at the bottom of the page.
- [x] Remove the horizontal rule between search results or eliminate lines from the summary list component.
- [x] Incorporate the details page (accessible by clicking on a result).
- [x] Apply Filter 
- [x] Clear Filter
- [x] Remove Filters
- [x] Back buttons

**Comment by jemnery** [comment]
https://github.com/ministryofjustice/find-moj-data
