### ISSUE TITLE
Update metadata specification with datahub concepts and user research fields

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#2993]
### User Story
A a developer, i want to  the include of all metadata attributes specified by the user researchers.
As a developer, I want to know how our metadata concepts map to concepts in datahub.

### Value / Purpose
This effort is essential for presenting valuable information to users during testing.

### Hypothesis
Enabling this functionality will ease the delivery of the frontend to users and foster iterative development through feedback.

### Proposal
 1. Create a mapping  table with current metadata with datahub concepts and user research fields. 

<google-sheets-html-origin><style type="text/css"></style>
SEARCH - HIGH | Source dataset name | [[quite broad - could be source system, source service, source table, source AP dataset - all also covered below]]
-- | -- | --
  | AP dataset name | eg. common_platform/full
  | Table name | eg. Finance Remission and Exemptions Table
  | Column name | eg. finance_person_id
  | Data field label | prob redundant / same as column label
  | Keyword/Tag | eg. [[needs guidance]]
  |   |  
FILTER - HIGH | Data domain | eg. Prisoner Facing
  | Business area | eg. Prison
  | Source system name (acronym) | eg. NOMIS, LPA
  | Data location/availability (AP, source, ...) | eg. Analytical Platform
  | Source system name (long name) | eg. eg. National Offender Management System; Lasting Power of Attorney
  | MoJ organisation | eg. HMPPS
  | Sensitivity level | default to official-sensitive?
  | DPIA Status | eg. [[not required for access but for processing?]]

Definition of Done
The frontend should successfully display metadata requested

**Comment by murdo-moj** [comment]
https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=784169301

In the v1.1 tab, I have added some extra columns for "DataHub concept" and "Card sort item".

I just talked with Richard and Alex vF a little, and they don't have business definitions for the card sort items they provided. So it might be best to only implement the filter/search on the card sort items already present in the metadata spec.
