### ISSUE TITLE
Breakdown Identity and Access Management

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3001]
### User Story

As an engineer I would like to break down the Identity epic and generate plan of attack and story stubs that will allow the team to deliver to the definition of done of the epic.

### Value / Purpose

This plan of attack will not only highlight any lingering questions and assumptions and identify dependencies and information gaps but will also be used to track path to completion of the epic.

### Useful Contacts

@julialawrence

### Hypothesis

If we carry out a break down exercise with the involvement of the PM , DM and SO, we will give the team more confidence that they're delivering the right thing.

### Proposal

The key outstanding question is identifying what we want to do with this?
Two meetings:
1. Refine the epic, to agree DoD for this priority
2. Map technical implementation, draft stories.

### Definition of Done

- [ ] Breakdown carried out
- [ ] Stories raised

**Comment by Ed-Bajo** [comment]
There is a need to ascertain thethe To Be state of the Analytical Platform.
