### ISSUE TITLE
💡 Implement Control Panel changes to manage user permissions internal to QuickSight

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#3067]
### User Story

As an Engineer,
I want to implement Control Panel changes, so that I can manage user permissions internal to Quicksight.

### Value / Purpose

Access to QuickSight, will make it easier, faster and better for people to read data, metrics and insights.

### Useful Contacts

@julialawrence
@Ed-Bajo 

### Proposal
Implement Control Panel changes to manage user permissions internal to Quicksight including datasource creation. This will require collaboration from plat ops DPAT contingent 

### Definition of Done

- [ ] Control Panel changes carried to manage permission out and tested.
- [ ] Datasources created

**Comment by michaeljcollinsuk** [comment]
Closing as not planned as it has been superseded by https://github.com/ministryofjustice/data-platform/issues/3065
