### ISSUE TITLE
📝 🐛 Easy local build of docs

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3069]
As demonstrated in [this](https://mojdt.slack.com/archives/C04VBJTKY58/p1706106373244069) thread it's not trivially easy for users to preview changes they are making to documentation. 

We ought to improve upon or replace the existing functionality outlined in README of the [moj-analytical-services/user-guidance](https://github.com/moj-analytical-services/user-guidance) repository.

### User Story

As someone wanting to create documentation and merge it
I want to preview it locally
So I can confirm I have created it correctly

This should be considered as part of [this](https://github.com/ministryofjustice/data-platform/issues/2825) epic.

**Comment by jacobwoffenden** [comment]
This was done as part of https://github.com/moj-analytical-services/user-guidance/pull/398
