### ISSUE TITLE
🤔 Discuss what tools we release (variants) and how we release them on Analytical Platform

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3131]
### User Story

As a Analytical Platform production
I want a cohesive pattern for releasing and publishing images
So that we don't end up with infinite variants and fragmentation of versions

### Useful Contacts

@jacobwoffenden

### User Types

Analytical Platform Product Engineering

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by julialawrence** [comment]
Duplicate of #3002

**Comment by michaeljcollinsuk** [comment]
Reopening this as I think we need to look at this again.

A recent support request for a new version of RStudio highlights the need for a process for new versions of tools https://github.com/ministryofjustice/data-platform-support/issues/701
