### ISSUE TITLE
 ✨ VS Code on Analytical Platform

### ISSUE THREAD

**Issue by AnthonyCody** [ministryofjustice/analytical-platform#3137]
### Describe the feature request.

Support VSCode as a Tool deployed on the Analytical Platform (in addition to R-studio, and as a possible replacement for Jupyter Lab Data Science).

### Describe the context.

User of the Analytical Platform have to use R studio as an IDE for running python.
VS code has proven to be a far better development tool for this purpose, and there is user demand for this as a tool on the AP.

### Value / Purpose

At present, users wishing to run python code (outside a Jupyter notebook) have to use R studio terminal to do so.
This is unintuitive for new users and less than ideal for experienced ones.

VS Code on the Analytical Platform has been a long time ask of the data modellers & analysts as an alternative IDE to R-studio.  The data engineers have standardised on VS Code as the preferred IDE of choice, so there is proven utility in making this more widely available and an existing pool of users to provide support.

Added bonus points: VS Code runs .ipynb (Jupyter notebook) files, so the AP may not need to support Jupyter going forward.

### User Types

Data Analyst users of AP

**Comment by mshodge** [comment]
👍 x ∞

**Comment by Ed-Bajo** [comment]
Link to ticket in current sprint -

**Comment by Ed-Bajo** [comment]
In the process of been implemented.
