### ISSUE TITLE
🤔 If we no-go QuickSight, do we sunset the tactical solution?

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3152]
### User Story

As a Analytical Platform engineer
I want us to come to a decision on the future of QuickSight if we decide to no-go it
So that we don't still end up maintaining QuickSight if its not our tool of choice

### Value / Purpose

We (Analytical Platform) provide QuickSight in a tactical offering, as in its not part of core product.

### Hypothesis

If we decide to no-go QuickSight
Then sunset QuickSight

### Definition of Done

- [ ] decision made

**Comment by julialawrence** [comment]
Let's rewrite this to cover the migration plan instead.
