### ISSUE TITLE
 ✨ Provide a terminal outside of R Studio on Analytical Platform

### ISSUE THREAD

**Issue by vonbraunbates** [ministryofjustice/analytical-platform#3184]
### Describe the feature request.

Allow users to have direct access to a POSIX-compliant shell on the list of AP tooling.  Helpful criteria:
* prefer a widely-used shell over a feature-rich niche e.g. `bash` or `sh` over `zsh`, `fish` etc.
* modern implementation with array and nameref support e.g. `bash v4.4+`
* install a basic IDE e.g. `nano` as an interim solution to [issue 3137](https://github.com/ministryofjustice/data-platform/issues/3137) (doubtless somene will want `vim` too...)
* core tools for manipulating common file formats we use, e.g. `yq` for YAML, `jq` for JSON, `csvkit` for CSVs

This is far more intuitive than starting R Studio just to use a terminal.

### Describe the context.

Currently the shell is unintuitively accessed via one panel in R Studio.  This is confusing for new users (why do we need a sledgehammer to crack a nut?).  It is limiting for advanced users (there are no robust shell syntax highlighting nor `sh` code snippets in RStudio) which slows development.

Standard data engineering tools are branching out from python and R, so RStudio is no longer an efficient environment in which to use these tools.  Most notably Create A Derived Table -- using SQL, Jija, YAML and shell scripts -- is far easier to use in an SSH-like interface rather than one corner of the RStudio screen.

### Value / Purpose

This would enable users to:
* run commands using the AWS CLI (rather than using a language-specific SDK)
* simplify use of Create a Derived Table (which is SQL and Jinja-based)
* automate programmatically (and therefore auditably) various actions via shell scripts
* edit YAML and JSON files programmatically
etc. etc.

This would also streamline the UX experience between data engineers (using the terminal in macbooks) and data scientists to facilitate teaching and debugging.  Presumably this would be easier to implement than [issue 3137](https://github.com/ministryofjustice/data-platform/issues/3137) and provide an interim improvement.

### User Types

data scientists, data engineers, AP power users

**Comment by julialawrence** [comment]
@vonbraunbates Do you think your ask is covered by this feature request? https://github.com/ministryofjustice/data-platform/issues/3137

**Comment by vonbraunbates** [comment]
@julialawrence I think they complement each other.  An experienced programmer could happily do without VS code as long as there's a good shell on the AP.  

This request asks for a low-level way to interact with AP data and tools -- the sort of terminal environment you'd experience via SSH: there's a modern shell, some essential command-line tools, everything is open source and free to use.

Whereas #3137 (if I read it correctly) is asking for a high-level program to write the scripts you run with this ask -- an enterprise IDE with lots of bells and whistles and all the package monitoring and licencing complexity attached.

**Comment by Ed-Bajo** [comment]
Edwin to Contact Francesca Von Braun-Bates regarding using VS codse.
