### ISSUE TITLE
:sparkles: Onboard James

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3187]
### Onboard checklist

- [x] AWS SSO - by adding to correct teams in https://github.com/ministryofjustice/data-platform
- [x] Sign PNC sheet https://docs.google.com/document/d/1sl6a9PAYj0dbSi19qPq0HpJB80aU2gfkJYYstI5_O38/edit
- [x] Github teams
- [x] Miro access (if necessary)
- [x] Added to all meetings
- [x] Added to google drive folder
- [x] Add to relevant slack channels
- [x] Email
- [x] Slack account
- [x] Create auth0 account (alpha/dev tenant admin)
- [x] Sentry access
- [x] @justice account (if not already)
- [x] Add to 1password
- [x] [Mandatory Training completed](https://justiceuk.sharepoint.com/sites/knowthething/SitePages/Mandatory-training-in-MOJ-D%26T.aspx)
- [x] Added to [People Finder](https://peoplefinder.service.gov.uk/teams/data-platform-apps-and-tools)
- [x] Building Pass (if required)
- [x] Set up Control Panel Local Environment

### Definition of Done

- [x] All steps checked off

**Comment by michaeljcollinsuk** [comment]
Terraform apply is failed to add James to one of the teams https://github.com/ministryofjustice/data-platform/actions/runs/7756223445/job/21159397399

**Comment by michaeljcollinsuk** [comment]
@jamesstottmoj for google drive, not sure if there is actually any action to take, you should have access. As a test, can you try accessing https://drive.google.com/drive/folders/1-W7ytUZZaPvSxuzJ5hpcgVBCLBF76OuY

**Comment by Gary-H9** [comment]
Complete
