### ISSUE TITLE
🐛 Create-A-Derived-Table Action Queue is unacceptably long

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#3208]
### Describe the bug.

In create-a-derived-table, action run times can [stretch to upwards of an hour](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/7757848739) despite only [taking a matter of minutes](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/7757848739/usage) to run. This is due to long queue times when multiple PRs are made, and if many pushes are made to said PR branches.

### To Reproduce

1. Go to the Create-A-Derived-Table repo
2. Open a number of PRs with changes
3. Cause a mashup for the `deploy-dev` action
4. Get stuck queuing for ages

### Expected Behaviour

Multiple PRs should be able to use actions simultaneously.

### Additional context

Recommend Scaling runner count from 1 to 2. This should help alleviate the worst of the queuing at peak times. Could autoscale but this may be overkill.

**Comment by jhpyke** [comment]
To add, this issue has been noted by end users, and a solution sought via Slack. We should act on this promptly to ensure customers continue to use the service without issues.

**Comment by jhpyke** [comment]
Should be closed by #3218

**Comment by jacobwoffenden** [comment]
CADT's Cloud Platform and Data Platform replica count has been increased to 2.

Moving to in review while we collect feedback from users.

If no issue by CoP 6/2/24 then close

**Comment by jacobwoffenden** [comment]
Closing as we've not heard any negative feedback
