### ISSUE TITLE
🔧 Improve the Control Panel Tool Releases page

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3209]
### User Story

As a control panel admin
I want to see clear and useful information about tool releases
So that releasing and managing tools is easier

### Value / Purpose

Currently the tool releases page is difficult to read, and there is a lack of information about which tool is more recent and how many users are using it. This makes it difficult for us to delete old releases, and create new ones.

### Proposal

Improve the Tool Releases page and the manage release pages

List page
- Sort tool releases by release date and display release date in the table
- Show number of users using a particular tool
- Review table headers and improve to make it clearer what each refers to e.g. "Version" -> "Chart version" 
- Consider tooltips for better descriptions of each column

Manage tool
- Review fieldnames and helptext and update as necessary
- Add "Copy release" button to copy over existing config/setup to a new tool release form (nice to have)

### Additional Information

https://github.com/ministryofjustice/data-platform/issues/3131 may feed into these changes

### Definition of Done

- [x] UI updated
- [ ] Deployed to dev for testing
- [x] Released to prod

**Comment by Gary-H9** [comment]
🐛 I've noted that when you try to update a release with a list of users, and one of the users does not exist in the control panel. The Control Panel will report that it has successfully updated the release, but will add none of the users.

🐛 If you try and add an existing user with their capitalised username this will report a successful add but they are not added.

**Comment by michaeljcollinsuk** [comment]
PR that contributes to this work open https://github.com/ministryofjustice/analytics-platform-control-panel/pull/1369

**Comment by michaeljcollinsuk** [comment]
PR to add filtering and improved ordering merged. We may choose to revisit the page and do further work in the future
