### ISSUE TITLE
Move datahub deployment to monorepo

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/analytical-platform#3222]
Background: https://docs.google.com/document/d/18Hw0pMYuVls5Up9659p9Wqqs5lFO93vgo-jI00Oq1xE/edit

Try out the Apps & Tools approach for deploying helm charts with terraform.

If it works for us, we can manage all the helm deployments in one place, if not, we don't have to use it though

**Comment by jemnery** [comment]
Closing as invalid - moving away from "data platform" name, and the monorepo

**Comment by jemnery** [comment]
Closing as invalid - moving away from "data platform" name, and the monorepo
