### ISSUE TITLE
 ✨ Button to access QuickSight from Control Panel

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3228]
### Describe the feature request.

Add a Button to access QuickSight from Control Panel. 

I leave the finer details to @michaeljcollinsuk. 

Initial suggested process:

By default, the quicksight role is given wildcard access to all `alpha` buckets.

Then, when a user clicks the button to allow it to be used within quicksight, Control Panel will update the S3 bucket policy, to allow the quicksight role to access it.

This will be done via an API call using boto3. As all buckets are within the data-production account, there will be no cross account issue for this step.

### Describe the context.

As part of the testing assumptions ticket we identified that there will be a need _in the future_ to add a button to the Control Panel. This feature request is in relation to that.

### Value / Purpose

Ease of use for users. 

### User Types

Control Panel Users

**Comment by michaeljcollinsuk** [comment]
Closing this issue as we have since agreed to offer Quicksight as part of a new AP dashboard. There may still be a need to link from the old Control Panel to the new dashboard, but this will be decided later.
