### ISSUE TITLE
🕵️ Define the services we support as Analytical Platform

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3236]
### User Story

As an Analytical Platform product engineer
I want a list of services we as a team support
So that we aren't on the hook for anything and everything

### Value / Purpose

The ecosystem of products that use Analytical Platform branding is bigger than what the core team supports day-to-day

### Useful Contacts

Data Engineering

### User Types

Product Engineering

### Hypothesis

If we survey the Analytical Platform landscape of services, create a list of who owns AND supports them
Then this should help us identify what WE support

### Proposal

DM/PM/BA create list of services and owners

### Definition of Done

- [ ] service list created
- [ ] support documentation updated

**Comment by Ed-Bajo** [comment]
Data Engineers in the Data Catalogue team have provided a list Apps/Services connected to the Analytical Platform - https://docs.google.com/spreadsheets/d/1VCP6VHsnWsHdJvhUMruocdMk212ayx3BQA49AZS7nOs/edit#gid=1722260833

**Comment by Gary-H9** [comment]
It is worth noting [this](https://user-guidance.analytical-platform.service.justice.gov.uk/shared-responsibility-model.html#shared-responsibility-model) page should be in agreement / updated with whatever conclusions are made in this ticket.

**Comment by Ed-Bajo** [comment]
The Spreadsheet listing the services and products the AP supports have been shared with the Data Engineer Leads (Callum and Soumaya) for their comments.

Action Points:
- AP Team will review the spreadsheet listing the products and services we support.
- Share spreadsheet with Data Engineer team to agree the services and products the AP team supports.

**Comment by Ed-Bajo** [comment]
The list of of services we would be supporting are now on the attached Spreadsheet which would be forwarded to Greg and Callum. A new ticket would be raised to review the 'Shared Responsibility Model' document. 

List of services AP Team supports - https://docs.google.com/spreadsheets/d/1VCP6VHsnWsHdJvhUMruocdMk212ayx3BQA49AZS7nOs/edit#gid=1722260833
