### ISSUE TITLE
🦙 Add ollama to AP image

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3272]
### User Story

As an AP user
I need/want/expect to… to be able to run a LLM on a container in the AP 
So that… I can <do data things>

### Value / Purpose

Adding [ollama](https://ollama.com/) would allow users to run LLM models in the AP. 

### User Types

Analytical Platform users

### Hypothesis

Users would like to run LLMs in a terminal. 

### Additional Information

Assumptions: 
- Users can pull models from the internet
- The models pulled are not too large for the containers

> Note: You should have at least 8 GB of RAM available to run the 7B models, 16 GB to run the 13B models, and 32 GB to run the 33B models.

### Definition of Done

- [ ] Ollama embedded into the appropriate AP image
- [ ] Documentation created 
- [ ] ADR created / approved / merged

**Comment by jacobwoffenden** [comment]
Superseded by https://github.com/ministryofjustice/data-platform/issues/3611
