### ISSUE TITLE
:twisted_rightwards_arrows: Migrate Auth0 rules to actions before EOL on 18/11/24

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3309]
### User Story

As a AP maintainer
I need to migrate Auth0 rules to actions
Before the end of life date on 18/11/24

### Value / Purpose

This is required is we intend to continue using Auth0 for authentication in the AP after November 2024.

### Proposal

We use Auth0 rules as part of our authentication process for the AP. Auth0 rules, and are reaching their end of life on November 18th 2024.

Therefore if we still plan to be using Auth0 after this date, we need to migrate from using rules to actions.

As it stands, it seems the auth0 rules have been defined "click ops" within the Auth0 UI. As part of the migration, we can investigate other ways to deploy the new Actions if we have time before the EOL date. 

### Additional Information

https://auth0.com/docs/customize/actions/migrate/migrate-from-rules-to-actions?mkt_tok=ODU1LVFBSC02OTkAAAGRQyx1v8lRLPb2HiE0qTgTUD4ABjlQmlU2kA67L5jgqFKVlGwC1PtQE0cB20LuopBIQgKEd45mqFBUZgB5o2awcMXCqrL8P0qoBBdlh7YvonmO4xO_

### Definition of Done

- [ ] Migrate Auth0 rules to actions
- [ ] Documentation related to Auth0 rules updated

**Comment by julialawrence** [comment]
We're either gonna migrate out of this tenant or go to EntraID directly.

**Comment by julialawrence** [comment]
We're either gonna migrate out of this tenant or go to EntraID directly.

**Comment by jamesstottmoj** [comment]
Rules have been migrated to actions in the dev tenant. I have tested this in Dev. Logging into control panel is successful but launching tools results in a 502 error. This seems to be a result of JWT decoding set to RS256. By going to the application on Auth0 dashboard and changing the decoding to use HS256, the tools can be accessed. I'm unsure if this is the correct route but the [proxy suggests](https://github.com/ministryofjustice/analytical-platform-nginx-proxy/blob/0f565aa7009f4da189c7c8d65116ebefdbd5bf5d/nginx-proxy/scripts/auth0_login.lua#L6) that this should be fine.

**Comment by jamesstottmoj** [comment]
Currently converting actions in prod tenant.

**Comment by jamesstottmoj** [comment]
Rules converted to actions in prod tenant. Will migrate over to actions mid-week

**Comment by jamesstottmoj** [comment]
Updated terraform to change JWT authentication algorithms for tooling in dev. Need to either get an application in the dev environment or switch prod over after hours to test applications.

**Comment by jamesstottmoj** [comment]
[PR](https://github.com/ministryofjustice/analytical-platform/pull/5513) has been put up for dev tooling JWT switch
