### ISSUE TITLE
Consult about external party use of data uploader

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/analytical-platform#3310]
Ani Setchi

  [11:06 via Slack](https://mojdt.slack.com/archives/C8X3PP1TN/p1707908799686899)

Hi, I have sign-off to transfer data to and then from an external partner. I am hoping to use the data uploader for this. But the external party has some reservations about the data uploader. They've asked for an assurance document and would also like to understand whether we can do the transfer by giving access via roles in AWS (as their data is hosted in AWS, they say it's the safest way) rather than email credentials via the data uploader. Could someone in Data Engineering please chat with me about what that means. And possibly come to a 20 minute meeting to answer their questions. Thanks in advance.

**Comment by jemnery** [comment]
Support request here: https://mojdt.slack.com/archives/C8X3PP1TN/p1707908799686899

**Comment by murdo-moj** [comment]
@PriyaBasker23 says she'll talk to Ani.
