### ISSUE TITLE
ℹ️  Update Know the Thing

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3315]
[This](https://justiceuk.sharepoint.com/sites/knowthething/SitePages/Analytical-Platform.aspx) is wrong, it needs to be updated. 

- [ ] Establish who's face should be on the page
- [ ] Establish what should be written in the blurb 
- [ ] Redirect to the newly created Analytical Platform Guidance

**Comment by bagg3rs** [comment]
Requested access from capability team for Greg, Gary, Julia, you can search KTT for how to edit and get the correct permissions if required

**Comment by Ed-Bajo** [comment]
Completed ticket.
