### ISSUE TITLE
 ✨ Feast and Feast UI on the AP

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#3369]
### Describe the feature request.

Alongside [mlflow](https://github.com/ministryofjustice/data-platform/issues/3368), [Feast](https://aws.amazon.com/blogs/opensource/getting-started-with-feast-an-open-source-feature-store-running-on-aws-managed-services/) is another tool in the MLOps toolbox that allows for Data Scientists/ML practitioners to save and load 'features' for the ML models. Features act slightly differently to how we currently treat 'data' on the AP. In addition, Feast has its own [UI](https://docs.feast.dev/reference/alpha-web-ui) so users can explore models and features, allowing for better collaboration between ML projects. 

### Describe the context.

I am starting my role as MLOps coordinator from next week. Therefore I am highlighting MLOps needs as early as possible in the hopes that they can be made possible during my six month stint.

### Value / Purpose

Without a dedicated tool like Feast, the impact of Data Science at MoJ will be greatly reduced. It will save time for the Data Scientists by providing a centralised store of their own features, but also provide them with the opportunity to see what others are doing. Without this approach, ML model features will not be easily transferrable across ML projects.

### User Types

Data Scientists doing ML

**Comment by mshodge** [comment]
Note: Might be redundant if [SageMaker](https://aws.amazon.com/sagemaker/) is the chosen approach.

**Comment by Ed-Bajo** [comment]
Meeting to be held with the MLOps team to ascertain requirements and current state.
Linked tickets:

https://github.com/ministryofjustice/data-platform/issues/3372
https://github.com/ministryofjustice/data-platform/issues/3378
https://github.com/ministryofjustice/data-platform-support/issues/527
