### ISSUE TITLE
 ✨ Grafana integration to MLOps work

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#3372]
### Describe the feature request.

Getting ahead of myself here in terms of MLOps, but always worth highlighting user needs as early as possible. In the MLOps lifecycle, monitoring of deployed ML models is important. You need to know if the model is behaving as expected, and have alerts in place if it isn't. 'Behaving' could be an accuracy score, or latency, or another user-defined metric. Anyway, there are plenty of monitoring tools out there but seen as Grafana is already being used, I thought we could leverage the knowledge of this and think about how to include it as a ML model monitoring tool.

### Describe the context.

I am starting my role as MLOps coordinator from next week. Therefore I am highlighting MLOps needs as early as possible in the hopes that they can be made possible during my six month stint.

### Value / Purpose

Deployed ML models need monitoring, especially those used in operational settings where early intervention in poor model performance is vital for the sake of the operational tool.

### User Types

Data Scientists doing ML

**Comment by Ed-Bajo** [comment]
Meeting to be held with the MLOps team to ascertain requirements and current state.
Linked tickets:
- https://github.com/ministryofjustice/data-platform/issues/3369
- https://github.com/ministryofjustice/data-platform/issues/3378
- https://github.com/ministryofjustice/data-platform-support/issues/527
