### ISSUE TITLE
⚡ Improve developer environment for Control Panel

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3375]
As a developer in the AP

- [x] Review existing developer setup process
  - Follow the existing process 
  - Ensure [running.md](https://github.com/ministryofjustice/analytics-platform-control-panel/blob/main/doc/running.md) is still accurate and working
  - Review unfinished docker compose instructions for running locally
- [x] Explore options for other ways to run the project locally
  - dev container
  - Localstack
- [x] Document a preferred solution if found

**Comment by jamesstottmoj** [comment]
Working on getting the Control Panel to run via. a Dev Container

**Comment by jamesstottmoj** [comment]
Control panel now runs in a dev container. Need to see about best way to use git while in the dev container, especially when it comes to signing commits.

**Comment by jamesstottmoj** [comment]
Fixed dev container using incorrect region so can now create S3 buckets in the dev environment
