### ISSUE TITLE
⬆ Upgrade Control Panel to python 3.12

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3376]
- [x] Update python version to 3.12
- [x] Update python dependencies
  - Prioritise updating moto dependency (will allow easier testing of Boto calls)
  - Consider using poetry for dependency management
- [x] Update Dockerfile 
- [x] Resolve deprecation warnings
- [ ] Resolve non failure warnings when running tests to make the test output more readable

**Comment by jamesstottmoj** [comment]
Python version updated to 3.12
Various dependencies updated to latest versions where possible
Replacement of deprecated test package (model-mommy)
Fixed tests that were no longer working as a result of changes
