### ISSUE TITLE
♻ Refactor App list pages within control panel

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3378]
Implement a better way of listing App's and their owners

Context: Simon Heron requested a list of all apps and their owners. Current best options are using the API https://controlpanel.services.analytical-platform.service.justice.gov.uk/api/cpanel/v1/apps/ or query the database (via django shell). 

Some options to improve:

- On the superuser only "All apps" page display the app admins. Note: lookup query will need carefully constructed for performance issues
- Admin action to export details e.g. csv download, or write to s3, or email?
- Review the API endpoints, could add one specific for apps/owners 
- CLI management command to get the data from the database

### Definition of Done

- [x] Implementation option decided
- [ ] Implemented and tested on dev
- [ ] Deployed to prod

**Comment by Ed-Bajo** [comment]
Meeting to be held with the MLOps team to ascertain requirements and current state.
Linked tickets:
- https://github.com/ministryofjustice/data-platform/issues/3369
- https://github.com/ministryofjustice/data-platform/issues/3372
- https://github.com/ministryofjustice/data-platform-support/issues/527

**Comment by jamesstottmoj** [comment]
Button implemented in admin webapps page that will save a list of admins to a CSV
