### ISSUE TITLE
:lipstick: UI and language fixes in Control Panel

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#3380]
- [x] Review and fix language and grammar, ensuring tone, branding
  - An example of this would be the bucket message, it read a bit informal
    - > We are on the edge of hitting the limit of AWS S3 bucket (1000).
Before we implement the long term solution, could you make sure you remove the buckets you do not need any more? also make sure not create more buckets than your need, try to use sub-folders to manage different datasets rather than multiple buckets.  
- [x] Review and fix links to Slack and user guidance
- [x] Remove link to AP Grafana, its broken
- [x] Remove emojis from UI, for accessibility

**Comment by jamesstottmoj** [comment]
Language has been reviewed and reworded where appropriate
Removed broken Grafana link
Changed slack support links to Github support request page
Removed emojis

**Comment by jamesstottmoj** [comment]
The current session length is a setting in control panel, `OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS`, rather than Auth0. It is currently set to 1 hour. This can be lengthened or shortened depending on security policy.
