### ISSUE TITLE
 ✨ Access to Bedrock - Apprenticeship

### ISSUE THREAD

**Issue by carlosMoJ** [ministryofjustice/analytical-platform#3473]
### Describe the feature request.

I would like to get access to an environment where I can investigate and use Amazon Bedrock. I am part of the Apprenticeship programme (Digital and Technology specialist msc) and approaching the final project stage. I have an idea for this project where I will use publicly available data from one (or two) of our applications as a source to interact with users, and give them information and links to relevant pages (from the sources).

### Describe the context.

I am part of the Apprenticeship programme (Digital and Technology specialist msc) and approaching the final project stage. I have an idea for this project where I will use publicly available data from one (or two) of our applications as a source to interact with users, and give them information and links to relevant pages (from the sources).

I would like to start working on this around mid-March, so I can be fully prepared when I start the final project modules.

### Value / Purpose

Investigation of Bedrock
Finalise the apprenticeship programme
Create a product that can be used within MoJ, with publicly available data from MoJ, to make it easier for users to find required information. 

### User Types

Public users, MoJ users

**Comment by julialawrence** [comment]
Completed
