### ISSUE TITLE
👨‍💻 Visual Studio Code - Beta - User Feedback

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3500]
### User Story

(Raised in relation to the [private beta](https://github.com/ministryofjustice/data-platform/issues/3478))

As an Analytical Platform Product Engineering
I want feedback from the private beta about the product we're developing
So that I can establish the value / any issues with the product prior to going live

### Value / Purpose

Standard part of running a beta. 

### Useful Contacts

@Ed-Bajo 

### Hypothesis

If we... gather feedback from the beta users
Then... we can improve the offering

### Definition of Done

- [ ] Create a method of gathering user feedback about the product

**Comment by Gary-H9** [comment]
Tagging @YvanMOJdigital in relation to User Research resourcing.

**Comment by YvanMOJdigital** [comment]
Plan for this is that we will begin some observational research in preparation for Richard Trist coming over to the team and taking over. Led by Product/Delivery/Greg with support from Rich. 

We will: Observe users interacting with the tool to identify potential pain points and support/documentation needs. - _anything else?_ 

- recruit volunteers from beta users
- develop a discussion guide 
- observe use of vscode and talking through their experience
- _anything else?_

**Comment by Ed-Bajo** [comment]
@YvanMOJdigital Thanks.

The team have also invited some targeted user to provide feedback.  The plan is that I'll gather the feedback and get it ready for Richard.

**Comment by EO510** [comment]
VSCode has been released into production
