### ISSUE TITLE
📖 Short Lived Data

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3562]
### User Story

As a… member of the AP team
I need/want/expect to… data uploaded by users to not become stale
So that… we are not storing data unnecessarily 

### User Types

Analytical Platform Users

### Hypothesis

If we... establish a flow for the lifecycle of data 
Then... we will save money by not storing redundant data and be able to identify Data Owners more easily. 

### Proposal

Essentially this would an option, when a user created Data in the AP, there is a time period the data is valid for - say 90 days. After this period the data would be moved - to another bucket for example. After another period of 30 days, it would be deleted. All of this would be wrapped in Slack Notifications and emails to the Data Owner via SNS.

If the Data Owner left the org, then this process would pick that up and 'we' would have an opportunity to identify another Data Owner. Thereby stopping 'Can we delete this? We don't know who owns it.' conversations years down the line.

### Additional Information

This is based off of [this](https://mojdt.slack.com/archives/C04M8224WCV/p1709551350359019) Slack thread.

### Definition of Done

Needs refining if desired, should be part of an Epic / Milestone related to Data Ingestion.
- [ ] Do user research 
- [ ] Define the ingestion frontend in the dashboard - new ticket
- [ ] Define the workflow in AWS - new ticket

**Comment by Ed-Bajo** [comment]
User - Research
