### ISSUE TITLE
🏗️ Produce bill of materials for Analytical Platform

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3697]
### User Story

As an Analytical Platform Product Engineer
I want a complete bill of materials
So that we can build out the infrastructure to deploy the evolved Analytical Platform

### Value / Purpose

We need to know what to build, and what components go into it, for example, new AWS accounts, EKS cluster, DNS, Sentry, Entra ID, Auth0

### Useful Contacts

@jacobwoffenden @michaeljcollinsuk

### User Types

Product Engineering

### Hypothesis

If we produce a bill of materials
Then we should have a complete list of things we need to create

### Proposal

Capture components that go into build out of Analytical Platform infrastructure

### Definition of Done

- [x] Bill of materials created
- [ ] Team reviewed and signed off
- [ ] Issues raised to create those items

**Comment by michaeljcollinsuk** [comment]
Initial "bill of materials" was captured as part of https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=56325944

See the Excalidraw diagram linked in https://github.com/ministryofjustice/data-platform/issues/3703#issuecomment-2024714604

**Comment by Ed-Bajo** [comment]
New ticket raised to progress the work.
