### ISSUE TITLE
:sparkles: Enable New App Onboarding

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3699]
### User Story

As an Analytical Platform User, I would like the ability to create new apps so that I can make my analyses available to an audience outside Analytical Platform

### Value / Purpose

The capability to create new apps has been suspended since November of 2022, and we are finally ready to reenable it at the conclusion of the last round of UAT.

### Useful Contacts

Michael Collins, James Stott, Julia Lawrence

### User Types

Analytical Platform User

### Hypothesis

Reenabling this functionality will give rise to larger volume of support requests so the score for this story should include the effort that is needed to deliver it.

We expect the experience of supporting the UAT will roughly mirror that of making this publicly available but on a larger scale. 

We expect we might encounter some issues around the fact that this process takes place without our interference so we might be blindsided by the amount of support requests.

### Proposal

Integrate lessons learned from UAT into the documentation and roll out the button in the Control Panel to allow app creation process to kick off.

### Additional Information

This should conclude the current epic.

### Definition of Done

- [x] Documentation updated
- [x] Documentation published
- [x] Control Panel button made visible
- [x] Team briefed
- [x] Announcement made

**Comment by michaeljcollinsuk** [comment]
User guidance published in https://github.com/moj-analytical-services/user-guidance/pull/392
Control panel released in https://github.com/moj-analytical-services/analytical-platform-flux/pull/1246
Notice to the AP team https://mojdt.slack.com/archives/C04M8224WCV/p1710766573939009
Announcements made in [#ask-data-platform](https://mojdt.slack.com/archives/C04VBJTKY58/p1710777313942949) and [#ask-data-engineering](https://mojdt.slack.com/archives/C8X3PP1TN/p1710777471964259)
