### ISSUE TITLE
📖 Instructions and demo for running AP UI locally to aid development

### ISSUE THREAD

**Issue by AntFMoJ** [ministryofjustice/analytical-platform#3702]
### User Story

As a data engineer
I need instructions and a demo for running the AP UI locally
So that I can contribute to development on my local machine, bypassing the need to go through the whole CI cycle for each change I implement.

### Value / Purpose

Having the ability to implement and test changes to the AP UI locally will mean that work can be executed and validated more quickly than if each change has to go through the full process of being integrated and deployed to the environment the (prod or dev) service is running.

Having the instructions documented alongside a demo of the steps will enable engineers to be able work on the project locally more efficiently and confidently.

### Proposal

When running the AP UI locally, it would be useful to be able to ensure it integrates with external AWS services or databases.
This could include using mocking for these services.

### Definition of Done

- [x] Process for running locally documented
- [ ] Demo of process given with the AP team in a huddle

**Comment by jamesstottmoj** [comment]
Guide written for running the new AP UI locally [here](https://docs.google.com/document/d/1biIjGWjdG_e-qlmRRcIXI55jKQUB36uzaQMHWRIE7D4/edit#heading=h.w5b5d6182y3e)

**Comment by jamesstottmoj** [comment]
Updated readme to include instructions on how to run locally.
Post create script now also creates static assets and runs migrations
Updated readme can be viewed [here](https://github.com/ministryofjustice/analytical-platform-dashboard/pull/119/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

**Comment by jamesstottmoj** [comment]
Waiting on PR review
