### ISSUE TITLE
 ✨ Create athena workgroups for Airflow workflows

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#3704]
### Describe the feature request.

- Linked to #3726

Create Athena workgroups for Airflow athena-based workflows using IAC with 1TB query limit and following tags based on [data engineering tagging convention](https://github.com/ministryofjustice/data-engineering-pulumi-components/blob/main/data_engineering_pulumi_components/utils.py#L109):

Tag | Value
-- | --
owner | Data Engineering:dataengineering@digital.justice.gov.uk
environment-name | prod
application | airflow
is-production | True
Name | airflow-prod-workgroup

Tag | Value
-- | --
owner | Data Engineering:dataengineering@digital.justice.gov.uk
environment-name | dev
application | airflow
is-production | False
Name | airflow-dev-workgroup

Tag | Value
-- | --
owner | Data Engineering:dataengineering@digital.justice.gov.uk
environment-name | prod
application | airflow
is-production | True
Name | airflow-prod-workgroup-hmcts
business_unit | HMCTS

Tag | Value
-- | --
owner | Data Engineering:dataengineering@digital.justice.gov.uk
environment-name | dev
application | airflow
is-production | False
Name | airflow-dev-workgroup-hmcts
business_unit | HMCTS

Similar to [here](https://github.com/ministryofjustice/create-a-derived-table-infrastructure/blob/bce9b9a0e34d31a5056c6ad49b50cd4e1620e639/create_a_derived_table_infra/__main__.py#L225) (but written in Pulumi)

Ideally we would create workgroups per domain, but this will require more effort in terms of coming up with appropriate domains and helping users assign the appropriate domains. So I suggest we should just stick with these workgroups for now.

There will be a separate ticket to see if there's a way of setting a default workgroup via Airflow-wide environment variables

### Describe the context.

Athena costs spiked in February:

https://mojdt.slack.com/archives/CBVUV2613/p1710165396335149

It was difficult to track the culprit because most people and airflow use the primary workgroup which means all costs is lumped into one bucket

### Value / Purpose

Using named workgroups with tags allows you to have better Athena cost granularity and to set limits.

This is an interim solution until we build Athena monitoring solution to track costs at the per user level.

### Timelines

Ideally as quickly as possible, but more realistically 1st week of April

### Definition of Done
- [x] Requirements confirmed with requestor
- [ ] Workgroups created
- [ ] Customer informed

**Comment by julialawrence** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/athena_workgroup

**Comment by Ed-Bajo** [comment]
Reached out to Soumaya regarding the ticket. This high priority for her team and proposed a work around, see below option 3 of #3777 :

Option 3:
• Give SSO data engineer permission to create/manage AWS Cost budgets (happy to raise this as separate ticket :-)
Describe the context.

The daily Athena usage is usually < $250, which works out to be 50TB:

Anything above this limit should be investigated.


![Image](https://github.com/ministryofjustice/data-platform/assets/37578406/83ff9ab3-0859-444a-8ab3-a9be81a97c90)

**Comment by Ed-Bajo** [comment]
@SoumayaMauthoorMOJ - Note that the proposed solution (option 3 of #3777 ) would not be implemented by the team. We can have a chat on an alternative solution around creating Terraform.

**Comment by SoumayaMauthoorMOJ** [comment]
Sure can you set something up for Monday 29th April?

**Comment by jacobwoffenden** [comment]
Hi @SoumayaMauthoorMOJ!

Can you clarify what the result bucket will be please

Thanks!

**Comment by SoumayaMauthoorMOJ** [comment]
@jacobwoffenden s3://mojap-athena-query-dump/{workgroup} please :-) (s3://dbt-query-dump/ is specific to create-a-derived-table)
