### ISSUE TITLE
📖 ✉️  Ensure Users have `@justice` email address

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3714]
### User Story

As a… consumer of the AP
I expect to be informed in a timely manner of things which effect how I consume the platform
So that… my use of the platform is not interrupted

### Value / Purpose

We need to ensure our users have a `@justice` email address as part of our ongoing Identity work. Users will need this going forward. 

### Definition of Done

- [x] Establish the process for getting a `@justice.gov.uk` email address, it's most likely in ServiceNow.
- [x] Prepare comms including the above.
- [x] Send comms.

**Comment by Joooojj** [comment]
✉️📖

**Comment by EO510** [comment]
Comms have being sent out to the AP users on slack support channel and data platform channel 

 https://moj.enterprise.slack.com/archives/C4PF7QAJZ/p1712592546423129
