### ISSUE TITLE
 ✨ Add per-query limit to primary Athena workgroup

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#3726]
- Linked to #3704
- Linked to #3777

### Describe the feature request.

Add per-query [limit](https://docs.aws.amazon.com/athena/latest/ug/workgroups-setting-control-limits-cloudwatch.html) to primary athena workgroup using IAC:
- 1TB query limit

### Value / Purpose

This will help up to limit Athena costs

### Timelines

Ideally as quickly as possible, but more realistically 1st week of April

### Done

Queries which try to scan more than 1TB fail

**Comment by SoumayaMauthoorMOJ** [comment]
@jacobwoffenden I've broken the second part of  ticket into #3777 to make it clearer hope that's ok

**Comment by Ed-Bajo** [comment]
The ticket needs more information. Edwin to contact Soumaya.

**Comment by SoumayaMauthoorMOJ** [comment]
@Ed-Bajo the ask is very similar to #3704 it's to use IAC to add a per-query limit to the default Athena workgroup which is called `primary` using something like https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/athena_workgroup

**Comment by Ed-Bajo** [comment]
@SoumayaMauthoorMOJ  - Please can you include the definition of done in the ticket.
