### ISSUE TITLE
 ✨ Migrate resources from data-engineering-infra and grant permissions to SSO data engineering role

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#3765]
### Describe the feature request.

Migrate resources from [data-engineering-infra](https://github.com/moj-analytical-services/data-engineering-infra) to data-platform IAC and add relevant permissions to SSO data engineering role

**Bucket and bucket policies**

For all buckets apart from `mojap-nomis-gdpr`:

![image](https://github.com/ministryofjustice/data-platform/assets/95432492/d003e68c-f273-4935-b452-cca34d9cb2e9)

![image](https://github.com/ministryofjustice/data-platform/assets/95432492/c36cfded-c191-47c7-992d-42aa51e6225c)

![image](https://github.com/ministryofjustice/data-platform/assets/95432492/5d352135-498f-49a9-b77c-9cedc5d2867d)

** Glue database policy **

For all databases and specified role_names, apart from `restricted_admin`:

![image](https://github.com/ministryofjustice/data-platform/assets/95432492/a15a6e96-67d4-4e53-a5b2-64e6d209786f)

### Describe the context.

See following tickets for more context:
- https://github.com/moj-analytical-services/data-engineering-infra/issues/133
- https://github.com/moj-analytical-services/data-engineering-infra/issues/134

**Comment by julialawrence** [comment]
@SoumayaMauthoorMOJ the following buckets don't exist in the `data-production` account:
* `mojap-athena-query-dump-preprod`
* `mojap-athena-query-dump-dev`
* `alpha-data-engineer-logs-preprod`
* `alpha-data-engineer-logs-dev`

Please advise how you'd like to proceed.

**Comment by SoumayaMauthoorMOJ** [comment]
@julialawrence  If they don't already exist don't create them :-)

**Comment by julialawrence** [comment]
The glue policy has been imported and the data eng role added. This needs to continue into next sprint.

**Comment by jacobwoffenden** [comment]
Moving to blocked while @julialawrence is on annual leave.
