### ISSUE TITLE
🔧 🗣️  Ingestion Notifications

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3770]
### User Story

As a… user of the new AP ingestion service
I need/want/expect to… be notified of successful/failed ingestion of files
So that… I can take relevant action

### Value / Purpose

v1 of the ingestion service outlined initially [here](https://github.com/ministryofjustice/data-platform/issues/3501) and [here](https://mojdt.slack.com/archives/C04M8224WCV/p1710850375164049). Suffice to say that the service does not currently include the notifications via gov.uk Notify or Slack.

### Additional Information

A Slack App has been created [here](https://api.slack.com/apps/A06NU3WMDSS). 
A team has been created in gov.uk Notify [here](https://www.notifications.service.gov.uk/services/8f49a218-3dc1-439c-9aec-8419ff524a63).

### Definition of Done

- [x] Refactor code where necessary, this may include the `handler.py` functions in the lambda images
- [x] Ensure team have access to gov.uk notify
- [x] Edit appropriate lambdas (see Excalidraw) to have correct permissions (those outlined [here](https://repost.aws/knowledge-center/sns-topic-lambda) to start) to send notifications via SNS
- [x] Add Slack notification in the event of a failure
- [x] Add govuk notify notification in the event of a failure
- [x] Add Slack notification in the event of a success
- [x] Add govuk notify notification in the event of a success

Success = upload to location
Failure = quarantined

**Comment by Gary-H9** [comment]
- New release of [0.0.1 ingestion-transfer-notify](https://github.com/ministryofjustice/analytical-platform-ingestion-notify/blob/main/src/var/task/handler.py) image.
- v.0.0.2 in progress
- 🚧  WIP - https://github.com/ministryofjustice/modernisation-platform-environments/pull/5556 
- https://github.com/ministryofjustice/analytical-platform-ingestion-notify/pull/15

TODO:

- [x] Populate GOV.UK Notify secret values
- [x] Publish Slack application add secret to Secrets Manager

**Comment by Gary-H9** [comment]
- Enhancements to the WIP https://github.com/ministryofjustice/modernisation-platform-environments/pull/5556 
- https://github.com/ministryofjustice/analytical-platform-ingestion-transfer/pull/29

**Comment by jacobwoffenden** [comment]
- Published Slack application and installed into Justice Digital workspace
- Populated Slack and GOV.UK Notify secrets in Development
- Merged https://github.com/ministryofjustice/analytical-platform-ingestion-notify/pull/15 and released ingestion container image
- updates to permissions in modernisaton-platform-environments for lambda permissions

**Comment by Gary-H9** [comment]
- Updates to the ingestion-notify lambda container image and to the permissions surrounding the s3 notifications in the aforementioned repositories.

**Comment by Gary-H9** [comment]
Apologies, I meant to close this a few days ago. All above PRs merged and tested both Slack and email notifications for both clean and infected files.
