### ISSUE TITLE
🐞 Fix linting in JML Report

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#3771]
### Describe the bug.

Super-Linter's suite of Python linting tools fail on https://github.com/ministryofjustice/analytical-platform-jml-report

### To Reproduce

1. Run Super-Linter

### Expected Behaviour

All Python linters pass

**Comment by AntFMoJ** [comment]
[This PR](https://github.com/ministryofjustice/analytical-platform-jml-report/pull/56) implements refactoring and code fixes to resolve issues with linting.

It has been noted that unit tests have not been created, an action will be taken to create a new ticket for adding this in.
