### ISSUE TITLE
 ✨ Create usage alert on primary athena workgroup

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#3777]
- related to #3726 

### Describe the feature request.

**Option 1:**

- Create Workgroup data usage alert:
  - Data threshold = 50 TB
  - Time period = 1 day

- Create sns topic which sends alert to dataengineering@digital.justice.gov.uk when daily threshold is passed

**Option 2:**

- Create an [AWS Cost budget](https://us-east-1.console.aws.amazon.com/billing/home#/budgets/overview) that notifies daily Athena spends over $250

**Option 3:**

- Give SSO data engineer permission to create/manage AWS Cost budgets 

### Describe the context.

The daily Athena usage is usually < $250, which works out to be 50TB:

<img width="721" alt="image" src="https://github.com/ministryofjustice/data-platform/assets/95432492/7ca7d871-97fd-495d-8d57-48d2ee350584">

Anything above this limit should be investigated.

**Comment by Ed-Bajo** [comment]
Please clarify the AWS account?

**Comment by SoumayaMauthoorMOJ** [comment]
593291632749

**Comment by bagg3rs** [comment]
This is related to #4110 @Gary-H9
