### ISSUE TITLE
Investigate CKAN as a potential data catalogue

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#378]
## User Story

Identify a catalogue that we can stand up and start learning from quickly

## User Type(s)

Data Engineers

## Value

There is an immense value in assessing something based on interacting with vs reading about it, therefore build quick, assess fast and discard fast. Therefore, there is immense value to identify something quickly buildable and build it.

## Questions / Assumptions / Hypothesis

As ever, we accept the assumption that we might not use what we build. That is an acceptable risk that becomes less acceptable the longer we put off actually building

### Proposal
A proposal that is something testable, don't worry whether it works or not, it's a place for ideas.

Pick something, build something, profit. 

## Definition of done

- [x] Build something
- [x] Demo it
- [x] Demo it to other teams
- [x] Draw up some conclusions

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
# Proposal

Spin up an EC2 instance in data-platform-development, install CKAN via Docker Compose (MVP)

# Sources

- https://ckan.org/
- https://docs.ckan.org/en/2.9/maintaining/installing/install-from-docker-compose.html
- https://github.com/ckan/ckan-docker

# References

- https://ckan.publishing.service.gov.uk/
- https://www.data.gov.uk/
- https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-resources.html
- https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/accessing-ec2s.html#accessing-ec2s

**Comment by jacobwoffenden** [comment]
Deployed to https://catalogue.development.data-platform.service.justice.gov.uk/ via #425

You need to be on MoJ Digital GlobalProtect to access

Credentials are in 1Password Data Platform folder

**Comment by jacobwoffenden** [comment]
Potential extenstions:

- https://extensions.ckan.org/extension/saml2auth/
- https://extensions.ckan.org/extension/s3-resources/

**Comment by jacobwoffenden** [comment]
Datopian references:

- 🎨 https://github.com/datopian/portaljs
- 🚢 https://github.com/datopian/ckan-cloud-helm

**Comment by julialawrence** [comment]
https://docs.google.com/document/d/1ySdeTqOx2ImtW-OZ0w8wu5ALYTUsG6xMmD_dOVy0oX0/edit
