### ISSUE TITLE
🔄 Revisit AWS DataZone

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#3843]
### User Story

As a Platform
I want to provide a simple sharing mechanism for data owners
So that data consumers and data owners have a secure and logged method of requesting access to data assets

### Value / Purpose

- Amazon [Data Zone](https://docs.aws.amazon.com/datazone/latest/userguide/what-is-datazone.html) has added a lot of new functionality around sharing data between data roles (admins or owners) and those looking for data (which could in the future come from find-moj-data
- Could allow data analysts to connect analysis tools to the data they need without configuring the datasource e.g. QuickSight
- Apply appropriate data governance to data assets 
- [DZ Projects](https://docs.aws.amazon.com/datazone/latest/userguide/datazone-concepts.html#what-are-projects) use-case based grouping of teams, tools, and data and could fill the role of the [Data Engineering Database Access](https://github.com/moj-analytical-services/data-engineering-database-access) 
- DZ is now also in the London region which removes the limitation of only using IAM users and provides SSO
<img width="866" alt="image" src="https://github.com/ministryofjustice/data-platform/assets/20583399/22070af1-f634-459e-b3bb-4570894f6b44">

### Additional Information

- See end to end use case between Data Producer and Consumer [here](https://youtu.be/bm5CLP54mrw?si=B-4kGdp_b23a7Kyv&t=112)
- Available [DataZone API's](https://docs.aws.amazon.com/datazone/latest/APIReference/Welcome.html)

### Definition of Done

- [ ] Review [Projects](https://docs.aws.amazon.com/datazone/latest/userguide/datazone-concepts.html#what-are-projects) as a way for teams to work on data together also see [data-engineering-database-access](https://github.com/moj-analytical-services/data-engineering-database-access) as current method of giving teams access to the same data resources.
- [ ] Review data sharing features [(Discovering, subscribing to, and consuming data in Amazon DataZone)](https://docs.aws.amazon.com/datazone/latest/userguide/datazone-concepts.html#what-are-subscribe-fulfill) and how users can discover these assets, request and gain access to these assets, and continue to use Amazon DataZone to govern, share, and analyse
- [ ] Review [Amazon DataZone built-in blueprints](https://docs.aws.amazon.com/datazone/latest/userguide/datazone-concepts.html#what-are-environment-blueprints) A blueprint with which the environment is created defines what AWS tools and services (for example, AWS Glue or Amazon Redshift) members of the project to which the environment belongs can use as they work with assets in the Amazon DataZone catalog
- [ ] Review [available API's](https://docs.aws.amazon.com/datazone/latest/APIReference/API_Operations.html) and they could be consumed by our frontend.

**Comment by Gary-H9** [comment]
Captured my thoughts in [this](https://moj.enterprise.slack.com/docs/T02DYEB3A/F06V0D644GG) Slack Canvas.
Note:
- The `terraform-aws-provider` was only [merged three weeks ago](https://github.com/hashicorp/terraform-provider-aws/issues/33792) (as of 15th April), so I don’t think this is very well developed. I can’t see any mention of it in the [Terraform Registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs) so unsure what’s going on there.

**Comment by bagg3rs** [comment]
article here on [data zone](https://moj.enterprise.slack.com/docs/T02DYEB3A/F0703KG8Q8L)

**Comment by jacobwoffenden** [comment]
We will spin out meeting with AWS into another ticket.
