### ISSUE TITLE
✨ Permission to a S3 sandbox bucket from AP Dev user

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#3864]
### Describe the feature request.

@PriyaBasker23 and myself are experimenting with [mlflow](https://mlflow.org/) on the AP Sandbox account. We have an instance running currently which allows for us to access mlflow when we auth using our sandbox credentials. I wanted to check if I could use my AP Dev account, and I can talk to the MLFlow instance, but don't have the permissions to read/write to the S3 bucket on the sandbox where MLFlow is saving the data. 

Could my AP dev user `dev_user_mshodge` have access to s3://mlops-artifacts-bucket on the sandbox account?

In the future we might want to test this with other users too, so having other AP Dev account roles able to access that bucket might be a future request.

### Value / Purpose

Will allow us to test the access and functionality of MLFlow on the sandbox whilst using the AP Dev accounts before we come up with a plan of how to put MLFlow on the AP.

**Comment by Ed-Bajo** [comment]
Engage with DE regarding their ML requirements.
