### ISSUE TITLE
 ✨ General user Grafana access

### ISSUE THREAD

**Issue by TomJPTravers** [ministryofjustice/analytical-platform#3875]
### Describe the feature request.

It would be helpful for users of the AP to have access to Grafana

### Describe the context.

I recently had an instance when I left a script running over night in Rstudio on the AP. When I returned to it I found that the Rstudio instance must have crashed and reset at some point. I suspected that this was due to a memory issue, but couldn't check as Rstudio's memory usage reporting doesn't keep reports prior to crashes and I don't have access to Grafana

### Value / Purpose

Instances like the above won't be common but when they do occur access to Grafana to monitor data on memory usage etc. would be really helpful to aid in troubleshooting and bug fixing.

**Comment by jacobwoffenden** [comment]
Hi @TomTravers-MoJ,

Unfortunately we aren't currently in a position to open Grafana to Analytical Platform users.

As for this:

> I recently had an instance when I left a script running over night in Rstudio on the AP

Analytical Platform runs a [scheduler](https://github.com/ministryofjustice/analytical-platform-scheduler) that will scale down tooling after a period of inactivity, this tends to happen overnight. Is the script something that you could run using Airflow?
