### ISSUE TITLE
🔐 Template IAM Policies for QuickSight Users

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3878]
### User Story

In order to integrate QuickSight permissions into the AP UI we need to create template iam policies for three types of QuickSight Users:

1. Viewer
2. Author
3. Admin

### Value / Purpose

The template policies will be used to generate final user permissions within AWS and QuickSight

### Useful Contacts

@julialawrence

### User Types

QS Admins, Users

### Proposal

Generate templates for minimum permissions needed for each type of users including those needed for administrators and for onboarding new users. 

### Definition of Done

- [ ] Templated policies developed
- [ ] Documented
- [ ] Team reviewed

**Comment by Ed-Bajo** [comment]
Part of a bigger peice of work.
