### ISSUE TITLE
📖 Implement EntraID Identity Provider in MP Compute Account + Test Identity Federation

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3879]
### User Story

As an AP Operator I would like to implement an EntraID identity provider in our MP account so we can test federation with EntraID identity. Additionally, we would like to determine which provider would suit our purposes best: SAML or OIDC

### Value / Purpose

We need an identity provider for EntraID if we want to retire the use of GitHub identities for tooling usage and QuickSight embedding. 

### Useful Contacts

Julia Lawrence

### Proposal

1. Investigate the preferred option of SAML or OIDC (especially if we want to look at ABAC further down the road)
2. Work with MP to create the provider
3. Test federation

### Additional Information

MP blocks the creation of identity providers outside of its main MP repo so we will need to work with them to create this.

### Definition of Done

- [ ] SAML or OIDC choice made and documented
- [ ] Provider deployed
- [ ] Role to test federation created
- [ ] Federation tested

**Comment by Ed-Bajo** [comment]
Ticket may be need for the tooling peice.

**Comment by Ed-Bajo** [comment]
@julialawrence agreed to close ticket.
