### ISSUE TITLE
 ✨ Export list of specific application users

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3882]
### Describe the feature request.

If a user wants to export a list of all users in their application in the control panel they cannot do this. 
For applications multiple pages of users this is particularly problematic.

As it stands we have to write scripts to parse information from the Django API. 

This feature request is to create a button which allows users to export a list of all of the users of their application in the control panel.

### Describe the context.

A user recently raised [this](https://github.com/ministryofjustice/data-platform-support/issues/513) support request which would be resolved by this feature.

### Value / Purpose

This will allow users to self-serve requests like this.

**Comment by Ed-Bajo** [comment]
A story ticket has been raised to address this request because it is part of a larger request. See attached - https://github.com/ministryofjustice/analytical-platform/issues/4449
