### ISSUE TITLE
Create API gateway – Terraform implementation.

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#393]
Create API gateway for Terraform implementation.

**Comment by PriyaBasker23** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Platform-Labs-6439239ff652d87aef65297a/issues/ministryofjustice/data-platform/393?planning-poker) with Zenhub @AlexVilela @hemeshpatel-moj @murdo-moj
