### ISSUE TITLE
✨ Change to data warehouse structure so that it can be applied to folders, not just buckets 

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#3936]
### Describe the feature request.

Currently the AP Control Panel allows users to create their own data warehouse (S3 bucket) and then allows them to have admin permissions to this bucket and grant others access to the entire bucket, or selected paths. However, this approach seems to be leading to a `bucket-per-project` approach being used, where users make a new bucket per project. Given AWS S3's limit of 1,000 buckets, another solution may be required.

If users share a bucket across multiple projects, one person still needs to be admin of the bucket, meaning they have admin control over all folders in that bucket. This may present DPIA and governance issues, as the admin will have access to everything and will need to be in the DPIA for everything. Then if that person leaves the organisation, a new admin will be required and they may have to be retrospectively added to multiple DPIAs and governance documents.

This request would be to explore whether we could:
1. Allow **AP Users** to Create **Team** of users in the AP Control Panel
2. Allow **AP Users** to Create Buckets with no admin (except super-admins of the AP)
3. Allow **Team Members** to create folders within the Bucket (but not see all contents of the buckets other folders by default)
4. Allow the **Folder Creator** to add Individual level permissions to the folder.

<img width="1203" alt="Screenshot 2024-04-03 at 10 01 20" src="https://github.com/ministryofjustice/data-platform/assets/15108577/dc03a4e2-3740-4895-91bc-b534bcdc06df">

This should, in theory, allow Users to more easily follow a `bucket-per-domain/team` approach and `folder-per-project`, reducing the number of buckets.

### User Types

AP Users

**Comment by SoumayaMauthoorMOJ** [comment]
I'm wondering if this would be better achieved using Lake Formation and/or Data Zone as opposed to building something. And use database-access instead as a work-around.  database-access is currently limited to curated and derived databases but I think it could be expanded to handle user-owned folders?  @mshodge how big of a priority is this?

**Comment by mshodge** [comment]
> I'm wondering if this would be better achieved using Lake Formation and/or Data Zone as opposed to building something. And use database-access instead as a work-around. database-access is currently limited to curated and derived databases but I think it could be expanded to handle user-owned folders? @mshodge how big of a priority is this?

Not a massive priority. But would be good to have a date on the calendar I think for us to work towards and let people know in case it impacts on their work. I think a solution, whatever it is, is needed though.

**Comment by SoumayaMauthoorMOJ** [comment]
@mshodge I'll be discussing access with @julialawrence ~~this~~ next week and get back to you ~~next week~~ soon with some more info

**Comment by julialawrence** [comment]
We can not support a creation of datasources with no admin assigned. That would be a nightmare and would defacto mean that the AP team owns that datasource. I'm not sure I understand what the usecase for that specific ask is.

**Comment by mshodge** [comment]
Aren't the AP/DE team defacto owners of all datasources? That is, they have access to all of them anyway It would just be a shift toward requesting folder level permissions and paths instead of bucket level?

I guess the use case is just to reduce the number of buckets.

This is what currently happens, a bucket per project 

<img width="1024" alt="Screenshot 2024-04-09 at 10 05 43" src="https://github.com/ministryofjustice/data-platform/assets/15108577/0dd11830-ff72-4340-8b3f-e984835087b9">
approach.

Inn some cases proactive people create folders under a bucket (Person A here for example who is on three of those projects - but if they leave the org then the bucket has no owner anyway)

<img width="1035" alt="Screenshot 2024-04-09 at 10 05 48" src="https://github.com/ministryofjustice/data-platform/assets/15108577/52d03b19-de85-420c-a166-9b0e2b07c457">

But ideally the folder owner approach would allow folders across an entire domain to be under one bucket. And even if a person (or people) in those teams who had folder permissions left, it wouldn't impact on the ability of others to add/remove folder level permissions

<img width="1047" alt="Screenshot 2024-04-09 at 10 05 51" src="https://github.com/ministryofjustice/data-platform/assets/15108577/20831939-40d0-42d9-ad1c-fc9d8e4fcd88">

Another approach I guess is for each domain to have a data controller/owner who owns all data in that domain and can be the bucket level admin; rather than the analysts creating the buckets.
