### ISSUE TITLE
Lambda Authorisation - Terraform Implementation

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#394]
Add Lambda Authoriser to Authorise via Apikey or Authorisation token – Terraform implementation.

## User Story
As a data engineer I want a lambda authoriser for our API so that API calls are verified and we comply with security best practice

## Value
Authorise calls to the our data upload API. This is just using a basic Authorisation token for now, but could later be expanded to congito

Definition of done
* Working authoriser deployed to modernisation platform

**Comment by PriyaBasker23** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Platform-Labs-6439239ff652d87aef65297a/issues/ministryofjustice/data-platform/394?planning-poker) with Zenhub @PriyaBasker23 @AlexVilela @hemeshpatel-moj

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/2198
