### ISSUE TITLE
♻️ 🪣  Ingestion: Add S3 Lifecycle Action

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3941]
Follow up to the ingestion work done [here](https://github.com/ministryofjustice/data-platform/issues/3796). 

Create a lifecycle action on [quarantine bucket](https://github.com/ministryofjustice/modernisation-platform-environments/blob/532a4f5b3df23a6e3aa181a470bb188a6337a99d/terraform/environments/analytical-platform-ingestion/s3.tf#L42) within the Analytical Platform Ingestion to remove unneeded files after a defined period - say 90 days, (decide this as part of refinement).

**Comment by Gary-H9** [comment]
This is blocked pending a enquiry which is [alluded to but not linked to anywhere](https://mojdt.slack.com/archives/C04M8224WCV/p1712658851591349).

**Comment by jacobwoffenden** [comment]
Agreement on standup 01/05/24 was that we'll delete items after 90 days

**Comment by Gary-H9** [comment]
Complete as per [this](https://github.com/ministryofjustice/modernisation-platform-environments/pull/5924) PR.
