### ISSUE TITLE
Use Lambda to generate presigned URL

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#395]
Add a Lambda to generate Presigned Url. 

Goal : Ensure all security considerations are met- implementation Via Terraform to reduce security risk to the data platform.

**Comment by PriyaBasker23** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Platform-Labs-6439239ff652d87aef65297a/issues/ministryofjustice/data-platform/395?planning-poker) with Zenhub @AlexVilela @PriyaBasker23 @hemeshpatel-moj @murdo-moj
