### ISSUE TITLE
Implementation of Azure + Cognito Auth and Authorisation

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#397]
Manual Investigation/ Implementation of Azure + Cognito Auth and Authorisation

**Comment by PriyaBasker23** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Platform-Labs-6439239ff652d87aef65297a/issues/ministryofjustice/data-platform/397?planning-poker) with Zenhub @AlexVilela @hemeshpatel-moj @murdo-moj @PriyaBasker23

**Comment by LavMatt** [comment]
test user pool has been setup with azuread as identity provider using oidc. Steps to do are [here](https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4386488323/Azure+Active+Directory+with+Cognito+to+secure+Api).

https://github.com/ministryofjustice/data-platform/issues/554 is follow on work from this
