### ISSUE TITLE
DAP Compute

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#399]
By creating various cloud infra components to enable upload and transformation of data we will provide a self-service functionality to the data producers and consumers.

### User Story

As a…
I need/want/expect to…
So that…

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by LavMatt** [comment]
Will now focus on the Athena load process
