### ISSUE TITLE
🔐 Triage ITHC Findings Report

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#3993]
### User Story

As AP Operator I would like to review the findings of the ITHC and agree way forward and assign remediation priorities

### Value / Purpose

Approaching this activity systematically will allow us to adopt a remediation plan, accurately capture risks and arrive at a joint decision regarding priorities leading to better outcomes

### Useful Contacts

Tevin Jemide, Julia Lawrence

### Proposal

Review the findings captured in the [report](https://drive.google.com/drive/folders/1sWgkV94mdQYhx8wqSPFtrtFYJSNz3kcY) as well as summarised in the excel spreadsheet.
Agree priorities.
Create stories to remediate.
Identify issues for other teams to remediate.

### Additional Information

We have remediated our internal single high. We still need to pass the Data Engineering high to them.

### Definition of Done

- [ ] Attended triage session(s)
- [ ] Reviewed findings
- [ ] Agreed priorities
- [ ] Identified and passed along DE-related findings
- [ ] Stories raised

**Comment by Gary-H9** [comment]
Added a new Issue Template which can be used to create issues for remediation when triaged.

**Comment by Emterry** [comment]
meeting to discuss to be arranged - Thurs 18th (?)
