### ISSUE TITLE
:sparkles: Enable S3 folders feature for new datasources created in Control Panel

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#4005]
### User Story

As a AP user
I want to create a datasource as a folder in S3
So that I can avoid hitting the S3 bucket limit for the account

### Value / Purpose

We are near the S3 bucket limit in the data production account. Creating new datasources as folders within a root bucket will help us avoid hitting this limit, and give users more freedom to create new datasources as required.

### Hypothesis

If we... enable the s3 folder feature
Then... we mitigate the issue of the S3 bucket limit in the AP data prod account

### Proposal

The changes will only affect new datasources - existing datasources will remain as S3 buckets.
The code for the feature is written, but the feature itself is disabled. It is some time since the code was written, so we should review the implementation, and make any changes as required.
We will need to create a root bucket in dev/prod where subsequent folders will be created. This should be managed in Terraform.
We can enable the feature in dev only first, to allow time for testing with the AP users and potentially a wider set of users.
We should communicate the changes to our users, through the usual channels (#analtytical-platform-support, #ask-data-engineering) and allow users to ask any questions related to the change. We may want to propose a specific data when the change will take place.
When the above has been completed, we can enable the feature in production.

### Definition of Done

- [ ] Implementation in the Control Panel has been reviewed and amended as necessary
- [ ] Root buckets have been created in dev/prod accounts
- [ ] Feature enabled in dev for testing by the AP team
- [ ] Comms about the change have been sent out to users
- [ ] Feature enabled in prod

**Comment by Ed-Bajo** [comment]
Present the proposed change to AP users in the show & tell.
