### ISSUE TITLE
🐞 Control Panel "My Tools" UI bug when only a single release available

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#4022]
### Describe the bug.

When only a single release for a tool is available, it appears as the only tool in the dropdown and appears as "installed", even if the user has an older version of the tool installed.

Screenshot from my tooling:
![image](https://github.com/ministryofjustice/data-platform/assets/15347726/65d9b574-22d5-49fe-acc5-46868b78dac1)

This indicates that I have `1.0.0-rc10(installed)`, but the opening square brackets show the actual version I have installed `[1.0.0-rc9]` and I can confirm this by using the `kubectl` for my namespace to check my pod:

Command used: `kubectl describe pods visual-studio-code-micha-57c54db579-5985m -n user-michaeljcollinsuk`

Truncated output:
```
Image:          ghcr.io/ministryofjustice/analytical-platform-visual-studio-code:1.0.0-rc9
```

As well as the UI being incorrect/misleading, it also blocks me from deploying the newer version of the tool - the "Deploy" button is greyed out. Manual intervention (updating the kubectl deployment) is needed to change version.

### To Reproduce

Unclear if this is reproducible from scratch, but I would try in dev:
1. Create at least 2 releases for a tool
2. Deploy tool 1 via My Tools
3. Now disable the tool 1 release via the Releases page, by making it a restricted tool
4. Go back to My Tools - does the UI show the bug described as above (incorrect version marked as installed, no option to deploy)

### Expected Behaviour

1. The UI is clear about the version of the tool a user has deployed
2. If a new version is available, and this is the only version available, the user should be able to deploy the new tool from the UI
3. After the new tool has been deployed, the UI matches what is described in the users tool deployment/pod details

### Additional context

I have only seen this bug with tools that are released using the `rc-n` tag, unclear if this was used in the past. But perhaps something in the Control Panel code is failing to parse this as it only expects a version number? Although this is just a theory, may affect other releases without the `rc-1` etc tags

**Comment by jamesstottmoj** [comment]
Looked into this yesterday and have a PR up for a potential fix. The image created by the PR was tested in prod and the fix seemed to have worked. This will be merged as part of the release process for the VSCode tool.

**Comment by jamesstottmoj** [comment]
Moving to blocked as this fix will be put in once VSCode is ready to be released

**Comment by jamesstottmoj** [comment]
This ticket should be merged between 29/04 and 30/04
