### ISSUE TITLE
Have an option to have Python Shell for processing.

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#403]
Potential users of the Data Platform and specifically those creating Data Products may already have existing python code used to register databases and tables in glue for users to consume through Athena. 

Often these pre-existing pipelines will not use Spark and so migration become more difficult to achieve with a Spark only solution. 

Having an option of using the python shell engine in glue would give greater flexibility and allow for smoother potential migrations from current compute methods in Kubernetes (orchestrated through airflow) to compute in glue. 

* https://github.com/ministryofjustice/data-platform-products/blob/main/data-products/example_prison_data_product/application/transform.py contains the code which is executed in the product's glue job
* This defaults to being executed on a spark cluster
* We want to allow data product creators to run their glue job on a python cluster, eg if they only need pandas and not PySpark for processing
* Add config in the data product creation which will allow users to execute python only code in the glue job. How will we handle custom libraries? What are the limitations of this approach?

There could also be efficiencies achieved through using the python shell glue engine for smaller data, as whilst the cost per DPU minutes is the same, the minimum DPUs for spark is 2 and for python shell is 0.0625, see https://aws.amazon.com/glue/pricing/ for pricing detail.

**Comment by murdo-moj** [comment]
Glue's Python has eg Pandas and Numpy by default. Extra libraries can be added, but this has to be done in the glue job config, so can be on request. https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html

**Comment by murdo-moj** [comment]
Glue's spark jobs have access to the python shell. There is not a significant cost saving to run pure python scripts as pure python shell jobs. Also, we want to encourage use of Athena to do transformations as this is actually much faster and cheaper. So this ticket is getting closed.
