### ISSUE TITLE
 ✨ Give DE SSO role access to cloudtrail s3 bucket

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#4068]
### Describe the feature request.

Give DE SSO role access to the modernisation platform cloudtrail s3 bucket modernisation-platform-logs-cloudtrail/AWSLogs/593291632749.

Ideally in the next sprint, but happy to delay if other high priority work

### Describe the context.

See [slack thread](https://mojdt.slack.com/archives/C04VBJTKY58/p1713178058870599)

### Value / Purpose
 DE can currently access cloudtrail events through the CLI and console, but not via [Athena](https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html) because we don't have permission to access the cloudtrail bucket

This ticket would make it easier to find out which glue jobs are using unsupported versions, as well other benefits such as tracking the number of users accessing glue tables

**Comment by SoumayaMauthoorMOJ** [comment]
- Replaced by #4236

**Comment by SoumayaMauthoorMOJ** [comment]
Reopening based on discussions with @bagg3rs . cc'ing @gustavmoller @williamorrie @PriyaBasker23  for reference.

**Comment by gustavmoller** [comment]
Hello! If possible, could we be provided access to this by the end of next week 🙏. We're currently putting together impact statements which are going to DG Richard Price, this will enable us to quantify the impact of our work on the AP.
