### ISSUE TITLE
📖 Notify change of image location for actions-runner

### ISSUE THREAD

**Issue by BrianEllwood** [ministryofjustice/analytical-platform#4076]
### User Story

As a…engineer
I need to re direct the original reference to the image location ghcr.io/ministryofjustice/data-platform-actions-runner to  the new ghcr.io/ministryofjustice/analytical-platform-actions-runner

So that it is in line with architectural restructure 

The Application owner/admins to be notified so they can make the appropriate changes

### Value / Purpose

This is a result of work carried out for this [ticket](https://github.com/ministryofjustice/data-platform/issues/4004)

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

amend the following reference to point to the new location  https://github.com/ministryofjustice/data-platform/blob/f8f62cd494ea736566c6db87fd777d39ffacd3cc/charts/actions-runner/values.yaml#L9

### Additional Information

If applicable contact repo owner before amending reference to the image.

### Definition of Done

- [ ] Application owner/admins notified

**Comment by jacobwoffenden** [comment]
actions-runner is an internal image, and all runners have been migrated to the new image
