### ISSUE TITLE
 ✨ Update data-engineering-exports to enable bucket creation in eu-west-2

### ISSUE THREAD

**Issue by AntFMoJ** [ministryofjustice/analytical-platform#4077]
### Describe the feature request.

West Midlands Police (WMP) currently aren't able to access the `mojap-wmp-proj` S3 bucket as it is in the `eu-west-1` region. The external user is investigating updating their role to enable this action, however the internal users (Ani Setchi and Mary Boeker) have requested if a bucket can be created in `eu-west-2` . This would require a change to the `data-engineering-exports` tool to enable selecting the region of the bucket being created.

### Describe the context.

Background to FR can be found in support ticket linked [here](https://github.com/ministryofjustice/data-platform-support/issues/525).

### User Types

Data Engineers, Data Scientists

**Comment by Ed-Bajo** [comment]
Closed as not planned. Wait for requestor to raise the issue again and plan for the wider work to be done.

Ant to go back to requestor.
