### ISSUE TITLE
 ✨ Provide a way to preview locally running applications on Analytical Platform

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#4118]
### Describe the feature request.

When developing applications on Analytical Platform's cloud development environment, it is essential that users can run and test their applications locally.

### Describe the context.

Running Dash apps locally.

Reference: https://user-guidance.analytical-platform.service.justice.gov.uk/appendix/dash.html

### Value / Purpose

This functionality exists in JupyterLab's NGINX proxy, but it uses path based routing.

### User Types

Analytical Platform users

**Comment by Ed-Bajo** [comment]
The feature request would be tackled in #4167
