### ISSUE TITLE
Smoke test for the scripts with  data provided by the user 

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#412]
This will be achieved by having per data product smoke tests. 

This could mean that data products should be uploaded with some sample data to run against the created glue job.

Check if possible for python and sql

**Comment by murdo-moj** [comment]
We already have unit tests which run sample data against the transform.py file. For a smoke test it would be ideal to have the transform.py file run in the execution environment (run the glue job)

**Comment by murdo-moj** [comment]
We already have unit tests which run sample data against the transform.py file. For a smoke test it would be ideal to have the transform.py file run in the execution environment (run the glue job)

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-platform-products/pull/31
