### ISSUE TITLE
Data Product Download

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#413]
Create a mechanism which allows consumers to read the data of the data product, so that consumers can access the data.

**Comment by PriyaBasker23** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data-Platform-Labs-6439239ff652d87aef65297a/issues/ministryofjustice/data-platform/413?planning-poker) with Zenhub @bogdan-mania-moj @hemeshpatel-moj @LavMatt @murdo-moj
