### ISSUE TITLE
Define Data Quality checks and technology

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#416]
As a data producer I want to check my data product is of good quality for transparency for my users

* Define data quality patterns for onboarding a data product. 
* What data quality checks will be done on every data product?
* What data quality checks can be customised to each data product?
* What technology will we use for the data quality checks:
  * Investigate on the Glue’s inbuilt data quality check 
  * Also investigate - package - [database-testing-tools](https://github.com/moj-analytical-services/database-testing-tools) if that will suitable for our usecase. [Here's](https://justiceuk-my.sharepoint.com/personal/michael_hodge1_justice_gov_uk/_layouts/15/stream.aspx?id=%2Fpersonal%2Fmichael%5Fhodge1%5Fjustice%5Fgov%5Fuk%2FDocuments%2Fvideos%2Fceo%2Fdatabase%2Daccess%2Dtools%2Fdatabase%5Ftesting%5Ftools%2Emov&ga=1) a video produced by DMET demonstrating the package 

Save the answers on confluence: https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4421223633/Data+Quality+Patterns

**Comment by murdo-moj** [comment]
https://docs.aws.amazon.com/glue/latest/dg/dqdl.html

https://docs.aws.amazon.com/glue/latest/dg/dqdl.html#dqdl-rule-types

**Comment by murdo-moj** [comment]
Automatic dq checks should be done and made available as part of a data product's metadata. We can implement these, they can be fairly light touch eg completeness. These should not cause any error or prevent a data product from being onboarded. This does not include schema checks. If a data append does not match the schema recorded in the data catalogue an error should be thrown.

Custom dq checks will need to be incorporated into the transformation pipeline logic which is created with a data product.

**Comment by murdo-moj** [comment]
https://docs.aws.amazon.com/glue/latest/ug/tutorial-data-quality.html

Data quality checks in glue can be defined in Amazon's data quality definition language and set up as a job on a glue catalog table. Outputs can be recorded in s3. Data quality failures can result in stopping to update the glue table or nothing depending on the setting.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_data_quality_ruleset

**Comment by murdo-moj** [comment]
https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4421223633/Data+Quality+Patterns writeup
