### ISSUE TITLE
 ✨ Grant Airflow DAG permission to trigger create-a-derived-table GitHub workflow

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#4166]
### Describe the feature request.

Grant airflow DAG permission to trigger create-a-derived-table GitHub workflow using the most appropriate method, which could be saving a Github personal taken to AWS Secrets/Parameters, or using a [GitHub app](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps)

### Describe the context.

We currently do not have a process for combining Airflow -> create-a-derived-table pipelines, apart from simply guessing the Airflow pipeline completion time and scheduling the time appropriately. There are multiple solutions, but a simple work-around is to use an Airflow bash operator and a curl command to workflow_dispatch the github action e.g:

```
curl -L \
  -X POST \
  -H “Accept: application/vnd.github+json” \
  -H “Authorization: Bearer <token>” \
  -H “X-GitHub-Api-Version: 2022-11-28” \
  https://api.github.com/repos/moj-analytical-services/create-a-derived-table/actions/workflows/<action_name>/dispatches \
  -d ‘{“ref”:“main”}’
```
This would require the Airflow DAG to have the relevant github permission.

**Comment by SoumayaMauthoorMOJ** [comment]
@jacobwoffenden let me know if you need more info :-)

**Comment by SoumayaMauthoorMOJ** [comment]
According to [Github](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#about-personal-access-tokens):

> Personal access tokens are intended to access GitHub resources on behalf of yourself. To access resources on behalf of an organization, or for long-lived integrations, you should use a GitHub App. For more information, see "[About creating GitHub Apps](https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/about-creating-github-apps)."

**Comment by SoumayaMauthoorMOJ** [comment]
@tomholt1 as discussed, please liaise on this ticket with the AP :-)

**Comment by Ed-Bajo** [comment]
@tomholt1 - Can we just clarify what the ask is for the AP team here. We can definitely generate a PAT for the runners, but worth us understanding what other facilitation your team will require (if any)?

**Comment by tomholt1** [comment]
Hey @Ed-Bajo, I think the context has changed a little since the ticket has been opened. We won't be needing a PAT as we will be planning to create a github app and authenticate that way using a JWT. What we require is just the relevant permissions to be able to run the above curl command in a DAG, that will trigger a github action upon the airflow jobs success

**Comment by jacobwoffenden** [comment]
@tomholt1 if you're going down the route of a GitHub Application, I'm not sure if you need input from our team anymore, it was originally suggested because we could provision a fine-grained access token using @moj-data-platform-robot

**Comment by jacobwoffenden** [comment]
Is this the GitHub App https://github.com/organizations/moj-analytical-services/settings/apps/airflow-dags-github-actions ?

**Comment by tomholt1** [comment]
Nope, I haven't set one up yet, although I'd be intrigued to know who set that up as I wonder if they're trying to achieve the same thing we are. So just to confirm - we don't need any updated airflow permissions to run the above curl command in an airflow dag?

**Comment by jacobwoffenden** [comment]
I'm unable to see **easily** when/who created a GitHub App

As for using a GitHub App to trigger a GitHub Actions workflow, I'm not sure this is something the Analytical Platform would want to facilitate, so it would be the responsibility of Data Engineering to ensure the application is correctly configured, and the tokens are stored securely for consumption within an Airflow DAG.

It might also be worth consulting with @ministryofjustice/operations-engineering about GitHub App vs. fine-grained token for this use case.

**Comment by tomholt1** [comment]
### Updated use case

We currently do not have a process for combining Airflow -> create-a-derived-table pipelines, apart from simply guessing the Airflow pipeline completion time and scheduling the time appropriately. There are multiple solutions, but a simple solution is to use an Airflow bash operator and a curl command to workflow_dispatch the github action e.g:

```
curl -L \
  -X POST \
  -H “Accept: application/vnd.github+json” \
  -H “Authorization: Bearer <auth_token>” \
  -H “X-GitHub-Api-Version: 2022-11-28” \
  https://api.github.com/repos/moj-analytical-services/create-a-derived-table/actions/workflows/<action_name>/dispatches \
  -d ‘{“ref”:“main”}’
```

The plan is now to create a Github App in `moj-analytical-services` to control the permissions for the above curl request. After some digging it looks like we will need to create a [JWT](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app#about-authentication-as-a-github-app) to authenticate the request.

More on [JWT](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app) for authentication, we will be needing a PEM file & a ClientID to generate the JWT

The Github App should hold the following permissions:
- Workflows (Read & Write)
- Webhooks (Read & Write)

I don't have the relevant access to create a github app so it would be great if this could be created and some guidance around authenticating would be great, thanks team!

**Comment by darren1988** [comment]
To be discussed at next refinement session

**Comment by SoumayaMauthoorMOJ** [comment]
@darren1988 can you invite @tomholt1 and I to the refinement session? I think @tomholt1 has made some progress on this with another team

**Comment by tomholt1** [comment]
No progress has been made as I need the Github App created, I just chased @darren1988 on this

**Comment by SoumayaMauthoorMOJ** [comment]
oops :-) thanks for clarifying

**Comment by SoumayaMauthoorMOJ** [comment]
Any update on this? I'm conscious @tomholt1 and I will be leaving soon :-)

**Comment by darren1988** [comment]
@SoumayaMauthoorMOJ this ticket has been refined and is scheduled to go into our next sprint commencing on 10/10/24 - 30/10/24

**Comment by darren1988** [comment]
@SoumayaMauthoorMOJ @tomholt1 we are pulling this ticket into our new sprint. I know you are both moving on soon - is there another point of contact for us to engage with regarding this work?

**Comment by SoumayaMauthoorMOJ** [comment]
How about @jhpyke since it impacts both create-a-derived-table and airflow?

**Comment by SoumayaMauthoorMOJ** [comment]
@gwionap could provide sign-off since he intends to use for his pipelines

**Comment by jacobwoffenden** [comment]
Hi all,

I have 

* Created a new GitHub App called "[Airflow GitHub Actions Trigger](https://github.com/organizations/moj-analytical-services/settings/apps/airflow-github-actions-trigger)" with the following permissions
  * Read access to metadata
  * Read and write access to actions
* [Installed](https://github.com/organizations/moj-analytical-services/settings/installations/55820002) it in `moj-analytical-services` for the following repositories
  * `create-a-derived-table`
* Created a new Secrets Manager [secret](https://moj.awsapps.com/start/#/console?account_id=189157455002&destination=https%3A%2F%2Feu-west-2.console.aws.amazon.com%2Fsecretsmanager%2Fsecret%3Fname%3Dgithub%252Fmoj-analytical-services%252Fairflow-github-actions-trigger%26region%3Deu-west-2) with the following key values
  * app ID
  * client ID
  * base64 encoded private key

Let me know if you can't access that secret, or if it doesn't do what is required, please open a support issue.

Cheers,

Jacob
