### ISSUE TITLE
✨ Update webapp guidance for AP

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#4181]
### Describe the feature request.

Based off the issues experienced in https://github.com/ministryofjustice/data-platform-support/issues/544 I thought it would be good to list where the current guidance, and templates can be improved.

## Update the template to include the healthcheck

- [build-push-deploy-dev.yml](https://github.com/ministryofjustice/data-platform-app-template/blob/main/.github/workflows/build-push-deploy-dev.yml)
- [build-push-deploy-prod.yml](https://github.com/ministryofjustice/data-platform-app-template/blob/main/.github/workflows/build-push-deploy-prod.yml)

Need the following added before line [164](https://github.com/ministryofjustice/data-platform-app-template/blob/e25aa1c9bfcd3d18324e47b218b0f67557b24fd7/.github/workflows/build-push-deploy-dev.yml#L164):

```
--set WebApp.AlternativeHealthCheck.enabled="true" \
--set WebApp.AlternativeHealthCheck.port=9999 \
```

This is to [prevent healthcheck issues ](https://github.com/ministryofjustice/data-platform-support/issues/544#issuecomment-2074421641)

## Update the guidance to state the port needs to be 9999

The healthcheck and other endpoints are sent to port 9999, but this normally isn't the default or norm port when people build webapps. So the guidance needs to specific that they need to use port 9999.

A good place to include this is probably where the Dockerfile is first mentioned [here](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/static-app.html#next-steps).

## Add note to make sure user doesn't set the namespace to be the same as the repo name

The Cloud Platform namespace should be different to the github repository name the app is in; this isn't explicitly stated so I think it would be good to just mentioned in [here](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/static-app.html#creating-a-namespace).

## Examples of working webapps using different app languages

Would be good to include a list of known, working webapps at the end of the [guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/static-app.html#deploying-a-webapp) for the various types of webapp people typically create. It's very RShiny heavy at the moment, so examples of Flask, Dash and streamlit would be useful too.

**Comment by Ed-Bajo** [comment]
We would look into the suggestions for the guidance.

**Comment by Emterry** [comment]
https://github.com/moj-analytical-services/user-guidance/pull/424
https://github.com/ministryofjustice/data-platform-app-template/pull/32
