### ISSUE TITLE
✨ Github workflow runner with access to s3

### ISSUE THREAD

**Issue by bcrawford-moj** [ministryofjustice/analytical-platform#4226]
### Describe the feature request.

I would like the workflow runner for [this project ](https://github.com/moj-analytical-services/bold_rr_pilot_families_nlp) to have access to s3 so we can load a large language model and run some inference in the code tests.

### Describe the context.

We are developing a piece of analysis which uses a large language model from huggingface. I have written some tests to test various bits of functionality (tokenizing, inference etc). I have then set up a workflow to run the tests (using pytest). The issue is that the runner cannot find the model. I assume this is because the runner can't just access anything on the internet (which makes sense). 

### Value / Purpose

This would allow us to create code tests which includes testing the model components of our applications/analysis. This will become increasingly valuable as we develop more AI and LLM applications. 

### User Types

Data scientists

**Comment by Ed-Bajo** [comment]
Additional information required in respect of the request.

**Comment by bcrawford-moj** [comment]
The s3 bucket is on the AP

**Comment by Ed-Bajo** [comment]
Requestor confirmed that all the required information are in the ticket.

**Comment by jacobwoffenden** [comment]
@bcrawford-moj what is the bucket you need access to?

**Comment by bcrawford-moj** [comment]
Hi Jacob. This one pease: alpha-bold-pilot-rr-families

**Comment by jacobwoffenden** [comment]
Hey @bcrawford-moj

A role with the ARN `arn:aws:iam::593291632749:role/github-bold-rr-pilot-families-nlp` has been created for your repository to assume.

If you need any more permissions can you raise a support issue.

Cheer

Jacob
