### ISSUE TITLE
📊 Discuss metrics for the services including tools and apps that we run

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#4239]
### User Story

As a Platform Team
I want to understand how our users are using our services
So that we know where we can focus or prioritise our work

### Value / Purpose

We have just added `vscode` as an offering on Analytical Platform
- how many users are using it?
- for how long are the using it?
- are they going to drop other tooling options now
- could we consolidate tooling eventually
- what about RShiny, are they being used, how much data is being pulled
- is the AP used :) 

### Useful Contacts

Rich

### Hypothesis

If we can observe AP
Then we can know AP

### Proposal

Get the metrics out (do we need an agent? otel?)
Display the metrics

### Definition of Done

- [ ] We know how our services (Tools and Apps) are being used e.g. daily, weekly monthly yearly usage

**Comment by Ed-Bajo** [comment]
Schedule a meeting to ascertain the metrics we would need. One hour meeting.
