### ISSUE TITLE
 ✨ Access to newly released Bedrock region in Ireland 

### ISSUE THREAD

**Issue by chloepugh** [ministryofjustice/analytical-platform#4297]
### Describe the feature request.

It seems Bedrock has recently been released in Ireland: https://docs.aws.amazon.com/bedrock/latest/userguide/models-regions.html

Could we get access to the Ireland region rather than Frankfurt? There are better models available in Ireland.

Thanks!

### Describe the context.

Using LLMs on non-public data

### Value / Purpose

There are several teams exploring the use AI to improve processes. We are severely limited by the fact that we mostly work with sensitive/non-public data, and this is something Bedrock can help with. Bedrock Frankfurt (that we currently have access to) is quite limited with the available models, and the performance of these models is not on par with the latest generation of LLMs. Bedrock Ireland makes Claude3 available, which is among the latest generation of well-performing LLMs.

### User Types

Data scientists

**Comment by julialawrence** [comment]
Hiya @chloepugh 

Concur the docs are listing it as available however, AWS doesn't appear to agree unfortunately. [This](https://mojdt.slack.com/archives/C015UBQ78MR/p1715325604644119) thread has details if you'd like to follow along.

**Comment by Emterry** [comment]
previous implementation for paris [here](https://github.com/ministryofjustice/analytical-platform/pull/4340)

**Comment by Ed-Bajo** [comment]
Ireland is still not an available region. The ticket would be closed now and reopened when Ireland becomes region.
