### ISSUE TITLE
✨ R in VSCode

### ISSUE THREAD

**Issue by elliot-linsey-cs** [ministryofjustice/analytical-platform#4309]
### Describe the feature request.

Can we have an installation of R on the AP version of VSCode? 

### Describe the context.

Data pipelines and analytical work for data science

### Value / Purpose

Having R on VSCode would make it easier to use one IDE for both Python and R. There have been projects where it would be useful to have python functionality combined with R, but this is difficult to setup in our existing versions of RStudio. VSCode appears to have greater support for this type of work. 

### User Types

Data scientists

**Comment by jacobwoffenden** [comment]
Could be solved by #4908

**Comment by jacobwoffenden** [comment]
Hi @elliot-linsey-cs

Until we provide first class support for R in Visual Studio Code, you could use Conda to install it

![Image](https://github.com/user-attachments/assets/63c92859-4bf4-4d1c-9876-21a9d46ec653)

**Comment by jacobwoffenden** [comment]
Hi @elliot-linsey-cs,

R 4.4.1 is now available in version 2.0.0 of Visual Studio Code on the Analytical Platform
