### ISSUE TITLE
📖 Update Base R images for 4.4.0 Airflow

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#4318]
### User Story

As an engineer
I expect my users to have access to secure base images
So that they can build more secure images for use in airflow.

### Value / Purpose

This allows us to provide a secure compute environment for our users, whilst providing access to the latest functionality.

### Useful Contacts

@jhpyke

### Hypothesis

In the data engineering ECR we currently publish two key internal R images -  [Rstudio](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/189157455002/rstudio?region=eu-west-1) and [r-airflow](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/189157455002/r-airflow?region=eu-west-1) (Links only available while logged into Data-Engineering-Prod). Both are based on public docker images, which have been republished internally. 

We should provide updated versions of these to support R 4.4.0. To do this, we will need to:

### Proposal

1. Acertain the base images currently used. This can be done by pulling the existing images from ECR. For RStudio, this is [Rocker's RStudio dockerhub](https://hub.docker.com/r/rocker/rstudio) repo. (**BLOCKER**: I cannot get the same info for r-airflow, as our admin role does not have the `ecr:BatchGetImage` action, and so cannot pull images from our ECR to inspect the existing image in docker. If this permission is added, you can pull the image into docker desktop and view the base image it is built from.)
2. Find updated releases of these base images, and download them to your developer mac
3. Use the view push commands button on the repo to see the commands required to republish the downloaded images in our internal ECR so users can build images based on them.
4. Notify users that new base images are available, and encourage them to migrate their airflow pipelines

### Definition of Done

- [x] Updated R images are available to build with
- [x] Users have been notified of updated images

**Comment by michaeljcollinsuk** [comment]
- `rstudio:4.4.0` image pulled from Rocker, and retagged/pushed to our ECR repo 189157455002.dkr.ecr.eu-west-1.amazonaws.com/rstudio:4.4.0
- `r-airflow-docker` image based on R4.4.0 has also been built/pushed. The latest version is `r-studio-docker:4.4.0-2` and was created via https://github.com/moj-analytical-services/r-airflow-docker/ with help from one of the data scientists Mike Ratford, who also updated the R airflow repo to use this image https://github.com/moj-analytical-services/template-airflow-r/blob/main/Dockerfile#L2

NOTE that the repo name has changed from `r-airflow` to `r-airflow-docker`. Reason for this change as explained from Mike:
> I think I must have manually pushed the last image to r-airflow when I was a data engineer but now I no longer have those permissions I used the github action which has pushed it to r-airflow-docker. It's probably best to use the action I would think? So the image would be r-airflow-docker:*.

**Comment by michaeljcollinsuk** [comment]
Draft comms https://docs.google.com/document/d/1KNxPkzPY9mFFpShujpr7SXSM-G9IN7LZrUdx_b4uitc/edit?usp=sharing

**Comment by michaeljcollinsuk** [comment]
Comms were sent out via a PagerDuty status update:
https://mojdt.slack.com/archives/C4PF7QAJZ/p1716200999616239
