### ISSUE TITLE
👥 EntraID integrations with AWS Identity Center tracking issue (see comments)

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#4324]
### User Story

As the AP team I want to know where we are at with AWS Identity Center 

### Value / Purpose

🗣️ Keep team updated on external dependancies 

### Useful Contacts

Julia and Rich

### Proposal

keep this issue in progress/block until done

relates to #4271 https://github.com/ministryofjustice/modernisation-platform/issues/6227

### Definition of Done

- [x] App Registrations have been created by TechServices
- [ ] Work completed on AWS Identity Centre

**Comment by bagg3rs** [comment]
From the 13/05/24 John N
"The two EntraID App Registrations have been scoped that will need to be completed for the SCIM functionality and the AWS Identity Centre connection. Yesterday they started looking at the Entra Security Groups self-service side of the demand. It is the piece that we need to spend some time focussing on getting right for us and you so that it will be secure and easy for you moving forward until we look at the next demand for options on automation."

They are looking to update us on Wednesday to go over details

**Comment by bagg3rs** [comment]
Meeting scheduled to for today 15/05 09:30 with John N

**Comment by julialawrence** [comment]
Original demand submitted on April 30th.
Approved on May 13th
Contacted by TS requesting additional information on May 21st
Returned questionnaire on May 22nd.
Expecting a meeting either 23rd-24th May or First week of June

**Comment by bagg3rs** [comment]
We are taking Identity Center to the CTO Solutions Surgery to get feedback and visibility

**Comment by bagg3rs** [comment]
Solution Surgery ✅
Next steps
- continue implementation with MP
- start an ADR on using IC SAML for AP

**Comment by bagg3rs** [comment]
Related [issue](https://github.com/ministryofjustice/analytical-platform/issues/4006)

**Comment by bagg3rs** [comment]
ADR-010 created [here](https://docs.analytical-platform.service.justice.gov.uk/documentation/adrs/adr-010-use-aws-iam-identity-center-managed-applications-for-user-access.html)

**Comment by bagg3rs** [comment]
Successfully tested app registrations on Friday with Julia and Dave for auth0

**Comment by bagg3rs** [comment]
Ongoing
- IDAM Submissions for Application Registrations approved and received
- Integration testing with Identity Center completed

Planned Next Steps  
- App registration added to Auth0 configuration
- Current GitHub Team group to accounts to be transformed into EntraID groups
- Testing with users

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/aws-root-account/pull/939
 To give us access Identity Center

**Comment by julialawrence** [comment]
Closing. The apps have been delivered and tested. Outstanding work will be tracked in #4838
