### ISSUE TITLE
 ✨ Set a default IP allowlist as part of Create auth0 client

### ISSUE THREAD

**Issue by ltd-pa** [ministryofjustice/analytical-platform#4335]
### Describe the feature request.

Set a default IP allowlist (e.g. DOM1) as part of Create auth0 client process in the control panel.

**Comment by ltd-pa** [comment]
Bump to keep issue open.

**Comment by YvanMOJdigital** [comment]
@ltd-pa Would you mind expanding on the need for this?

**Comment by ltd-pa** [comment]
I think it could improve security, and limit the scope for user error, if deployed apps were limited to MoJ networks by default, rather than requiring users to explicitly opt into this.

**Comment by julialawrence** [comment]
After a conversation with Laurence, agreed that FR can be closed in favour of this ticket: https://github.com/ministryofjustice/analytical-platform/issues/5387
