### ISSUE TITLE
🐞 investigate force replacement on terraform description impacting merge

### ISSUE THREAD

**Issue by Emterry** [ministryofjustice/analytical-platform#4343]
### Describe the bug.

as seen in this run : https://github.com/ministryofjustice/analytical-platform/actions/runs/9128282171/job/25100324310#step:13:81. It passed on plan however would cause a fail on merge

**Comment by jacobwoffenden** [comment]
As per [`CreatePolicy`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html#API_CreatePolicy_RequestParameters):

> The policy description is immutable. After a value is assigned, it cannot be changed.

Hence

```terraform
~ description = "Permissions needed to allow access to Bedrock in Frankfurt from tooling." -> "Permissions needed to allow access to Bedrock in Frankfurt  from tooling." # forces replacement
```

Then

```
Error: deleting IAM Policy (arn:aws:iam::${aws_account_id}:policy/analytical-platform-bedrock-integration): operation error IAM: DeletePolicy, https response error StatusCode: 409, RequestID: e91fcc39-159d-4aab-a507-4c9478843052, DeleteConflict: Cannot delete a policy attached to entities.
```

Its actually noted on [`aws_iam_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy#description)

> (Optional, Forces new resource) Description of the IAM policy.

**Comment by julialawrence** [comment]
The policy needs to be recreated with a correct description and roles reassigned. It's a bit of a quibble which is why it's low prio.

**Comment by michaeljcollinsuk** [comment]
@Emterry to convert this into a story ticket
