### ISSUE TITLE
 ✨ Incorporate Lake Formation management into Control Panel

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#4352]
### Describe the feature request.

 Incorporate [Lake Formation](https://aws.amazon.com/lake-formation/) management into Control Panel so that users can request/approve access to Athena databases and tables from the control panel

### Describe the context.

Data engineers currently uses [data-engineering-database-access](https://github.com/moj-analytical-services/data-engineering-database-access) and IAM [Customer managed policies](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#customer-managed-policies)  to manage users access to S3 data and associated Athena databases and tables in the AP. 

### Value / Purpose

Migrating to Lake Formation would have several benefits:

- Better support for cross-account permissions
- Support for column and row-level permissions
- Stop being limited by [IAM object quotas](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-entities)

Managing Lake Formation resources via the Control Panel would have several benefits:

- Less confusing for users

**Comment by Ed-Bajo** [comment]
This ticket relates to story #4367

**Comment by michaeljcollinsuk** [comment]
Initial work towards this is being tracked in https://github.com/ministryofjustice/analytical-platform/issues/4367

**Comment by Ed-Bajo** [comment]
Work has already started on this ticket.

**Comment by SoumayaMauthoorMOJ** [comment]
Reopening because work is progressing on this :-)
