### ISSUE TITLE
📖 Enable NVIDIA time-slicing

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#4353]
### User Story

As an Analytical Platform Platform Engineer
I expect the GPU enabled workloads to fully utilise the EC2 nodes we deploy
So that we aren't underutilising EC2 nodes

### Value / Purpose

Currently the GPU nodes are `p3.2xlarge` (8 vCPU, 61GiB memory, 1 Tesla V100 GPU), but the standard VS Code deployment, consumes 2vCPU and 12GiB memory, so a lot of the node isn't utilised. 

### Useful Contacts

@jacobwoffenden

### User Types

Platform Engineering

### Hypothesis

If we enable NVIDIA's time-slicing, then multiple workloads can share the GPU

### Proposal

https://aws.amazon.com/blogs/containers/gpu-sharing-on-amazon-eks-with-nvidia-time-slicing-and-accelerated-ec2-instances/

### Definition of Done

- [ ] time-slicing enabled
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by AntFMoJ** [comment]
Time-slicing has been added to the development and production clusters. They currently split each GPU resource into 4 allocatable GPUs, meaning more that one visual studio code deployment can run on a single gpu-enabled node.
