### ISSUE TITLE
 ✨ Amazon Bedrock - eu-west-1

### ISSUE THREAD

**Issue by MattFunnell** [ministryofjustice/analytical-platform#4357]
### Describe the feature request.

Hi - please could we enable access to run Amazon Bedrock in the eu-west-1 (Dublin, Ireland) region? This will help with DPIAs, as then data is staying in the same region as existing AWS storage

**Comment by Ed-Bajo** [comment]
Met with Matt Funnel and forwarded to him the security guidance on Data Sovereignty - https://security-guidance.service.justice.gov.uk/data-sovereignty/#data-sovereignty. 

He agreed that they will progress the DPIA using EEA basis, so the ticket can be closed.

**Comment by MattFunnell** [comment]
Hi Edwin - I spoke with @julialawrence and we discussed that this was a relatively quick action which would support our DPIA creation for using Bedrock, so could be progressed?

**Comment by MattFunnell** [comment]
Hi @Ed-Bajo - please can we re-open this?
