### ISSUE TITLE
📖 Create Patching Schedule

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#4363]
### User Story

As a… engineer in AP
I need/want/expect to… keep our core products up to date
So that… we provide a secure, up-to-date environment with the latest features for our users

### Value / Purpose

A key benefit of keeping software up to date is enhanced security, as updates often include patches for vulnerabilities that protect against potential threats and attacks. Additionally keeping software up to date also ensures better performance, access to new features, improved compatibility with other software, and stability through bug fixes.

### Definition of Done

- [x] Documentation what products are included in the patching schedule
- [x] Document how frequently a product should be patched
- [ ] Document under which other circumstances a product ought to be patched
- [x] Ensure each product has a method of patching documented in it's README
- [x] Test Patching each product

**Comment by Gary-H9** [comment]
This ticket is a prerequisite to [this](https://github.com/ministryofjustice/analytical-platform/issues/4638) ticket.

**Comment by jacobwoffenden** [comment]
GDoc https://docs.google.com/document/d/1RQ31ik6jqYGBHsURU0mpoyxeu2egKx787i6OaEbV2-o/edit

**Comment by tom-webber** [comment]
[GSheet summary / link aggregator](https://docs.google.com/spreadsheets/d/1vAjlY0_begATsYAU1FrJS7WRJFIGf-0cw55efSQ3WXw/edit?gid=0#gid=0)

**Comment by BrianEllwood** [comment]
looking for services/products  to be included

Change of direction, leave adding additional services/products to the list and work on how frequently a product should be patched and the method for the services already on the list

**Comment by BrianEllwood** [comment]
to do - finish documenting upgrade/patching process in a run book  draft [doc pr](https://github.com/ministryofjustice/analytical-platform/pull/5864)
update maintenance ticket to point to documentation

**Comment by BrianEllwood** [comment]
Carrying out patching/upgrade to confirm documentation correct.

**Comment by BrianEllwood** [comment]
Updating the readme for each product

**Comment by BrianEllwood** [comment]
Readme 's updated

**Comment by jacobwoffenden** [comment]
Pending #5907 for review of APC patching guidance

**Comment by BrianEllwood** [comment]
APC patching guidance approved and published.

**Comment by BrianEllwood** [comment]
Created a ticket to document maintenance in general
