### ISSUE TITLE
✨ Add CloudTrail to AP Users permissions to allow for better Airflow Error Tracking 

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#4368]
### Describe the feature request.

Airflow is used by a lot of analysts and data scientists, but sometimes jobs fail without proper or adequate logging information on the Airflow UI. When I was a Data Engineer, my go to would be to go to CloudTrail and look for why the job was failing. However, since leaving the Data Engineering team I no longer have access to the CloudTrail logs. As part of my MLOps work we are exploring how to use Airflow for model training; however, some users of Airflow for model training have experienced issues with their jobs getting stuck and not completing. I would like to know why these things happen, and the only way of doing that is to use check the CloudTrail logs. 

The CloudTrail logs, from experience, can be dense (as so much traffic occurs), but with the right guidance we can help AP users use this as a resource to look at Airflow failures. 

An alternative is to create a service where users can on the Control Panel for their relevant CloudTrail logs, but this seems to be a bigger task and would rely on users being linked to their Airflow jobs (which aren't currently recorded on the Control Panel) or for users to register Airflow jobs on the CP as well.

### Value / Purpose

Helps users understand issues with their Airflow runs without having to report to AP team straight away.

**Comment by jhpyke** [comment]
Hi,

Just to clarify the ask in this case, is this referring to the **CloudWatch** log groups currently accessible via the Airflow UI (to allow for better filtering using Cloudwatch), or the **CloudTrail** logs generated by the actions that a given DAG takes? or some third option I hadn't considered? Just so we can better understand the permissions desired and how they might compare to the current available permissionset.

Thanks,
Jake
