### ISSUE TITLE
📖 Snapshot and shutdown abandoned RDS instances

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#4375]
### User Story

As an Analytical Platform engineer
I expect all unused infrastructure to be shut down
So that we aren't paying for unnecessary resources

### Value / Purpose

It is unethical for us to waste money on resources that sit abandoned.

### Useful Contacts

@jacobwoffenden

### User Types

Platform Engineering

### Hypothesis

If we shutdown these unused RDS instances
Then we'll not have to pay for unused resources

### Proposal

Two RDS instances were identified in #4247 that have no tags, and don't look like they're used

`mpm-test-database-1` in `analyitcal-platform-data-engineering-production`
`addressbasepremium` in `analytical-platform-data-production`

Source https://docs.google.com/document/d/166N0-8FJnVGGQQVO-iffn_bnreEN2-ATxUIg6D6Dn0I/edit

### Additional Information

I have:
- Temporarily shut them down (21/05), but this is only for one week (until 28/05)
- Reached out to Data Engineering via Slack https://mojdt.slack.com/archives/C8X3PP1TN/p1716312950795289

### Definition of Done

If an owner identified:
- [ ] Import into Terraform
- [ ] Update tags
- [ ] Update RDS CA as per #4247

If no owner identified:
- [ ] Snapshot
- [ ] Destroy

**Comment by jacobwoffenden** [comment]
`mpm-test-database-1` snapshotted and destroyed as per https://mojdt.slack.com/archives/C8X3PP1TN/p1716364876820979?thread_ts=1716312950.795289&cid=C8X3PP1TN

**Comment by julialawrence** [comment]
Jacob shut down both instances
