### ISSUE TITLE
 ✨ Access to Bedrock - AI for Linked Data Projects

### ISSUE THREAD

**Issue by bcrawford-moj** [ministryofjustice/analytical-platform#4388]
### Describe the feature request.

Similar to [this issue](https://github.com/ministryofjustice/analytical-platform/issues/4222) for the AI for Linked Data team. We would like access to Bedrock. 

### Describe the context.

We have a number of projects for which access to Bedrock would be helpful.
- Extracting structured information on whether prisoners are in a drug recovery programme.
- Extracting structured information on the number of children a prisoner has.
- Generating summaries for use in pre-sentence reports.

### Value / Purpose

Allow us to complete the above projects as they require LLM access. 

### User Types

BOLD Data Scientists

**Comment by bcrawford-moj** [comment]
Could I request access for the following users:
- @bcrawford-moj 
- @carolinetudor
- @yznlp
- @DaoudC
- @wmartin-gss

**Comment by julialawrence** [comment]
Hiya, what models are you looking to use?

Additionally, are you planning to use data held in AP for this or openly available?

**Comment by bcrawford-moj** [comment]
For this ticket probably thinking Claude. We were planning on comparing what we can do with Bedrock and Claude compared to open models on gpu enabled by [this ticket](https://github.com/ministryofjustice/analytical-platform/issues/4120). It would be useful for us to compare the ease of and performance of Bedrock with a closed model set up, compared to the flexibility (e.g. finetuned models, further fine tuning) of the open model + gpu set up. Each set up will be more and less appropriate depending on the project.

**Comment by julialawrence** [comment]
@bcrawford-moj Are you planning to use AP data or open source data? This determines where we set you up with Bedrock access.

**Comment by bcrawford-moj** [comment]
AP data

**Comment by Ed-Bajo** [comment]
AP will onboard the request user/s.

**Comment by Ed-Bajo** [comment]
@bcrawford - moj please raise a support ticket for the onboarding of the user/s.

**Comment by bcrawford-moj** [comment]
Are you saying I have to raise a ticket for onboarding to the AP itself or for onboarding to Bedrock? If the former, these users already have AP accounts.

**Comment by julialawrence** [comment]
Bedrock

**Comment by bcrawford-moj** [comment]
I thought thats what this ticket was?

**Comment by julialawrence** [comment]
:D It's not a feature request. It's all good, I'll onboard you but I am just letting you know that the other project we've done this with had to raise a DPIA to cover the usage of their data outside the Ireland region. Bedrock is only available in Frankfurt and Paris at present. I'll post a comment here when you've been set up.

**Comment by bcrawford-moj** [comment]
Thanks! For future reference, which issue type should I use for things like this?

**Comment by julialawrence** [comment]
Hiya, you're all enabled. Now that we offer this service, even if it's limited, it's a support request.

**Comment by bcrawford-moj** [comment]
Great, thanks! And good to know - will use that one in future
