### ISSUE TITLE
✨ Provide access to AWS Q Developer in AWS Sandbox Account 

### ISSUE THREAD

**Issue by gustavmoller** [ministryofjustice/analytical-platform#4390]
### Describe the feature request.

Hello! [AWS Q Developer ](https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/what-is.html)is available for free between now and the end of June. Includes a chat in your IDE, as well as the ability to ask questions about your AWS resources; and access to a [Developer Agent](https://aws.amazon.com/q/developer/code-transformation/) which plans and executes tasks.

Could we enable this for testing purposes in the Sandbox account? It’s a slightly different AWS service, in that it is billed as a subscription per user, instead of by usage.

Is there an appropriate contact in Security who we could run this by to double check?

### Describe the context.

We'd like to explore the use of AWS Q to help developers working on the Analytical Platform.

### Value / Purpose

We'd like to trial the use of this while it's free.

### User Types

Analytical Platform SSO Roles

**Comment by Ed-Bajo** [comment]
The Data Engineers have full admin access and rights to grant the necessary access requested for in this ticket. It is our understanding that the AP team have no role in regards to this request.
