### ISSUE TITLE
📖 Short term accelerated compute instance - GPU node scale down

### ISSUE THREAD

**Issue by BrianEllwood** [ministryofjustice/analytical-platform#4402]
###  User Story
As a…engineer
I need/want/expect to…Have the Short term accelerated compute instance - GPU node scale down in a timely fashion. 
So that…we do not incur unnecessary cost  for an idle node

### Value / Purpose

Currently this is a restricted release but it would be good to have this configured correctly before going on GA to avoid unnecessary costs

### Proposal

Look at the best method for scaling down the GPU node, currently the vscode scheduler has a parameter MAX_IDLE_TIME of 600 (looks like minutes) before closing down an idle pod 

### Definition of Done

- [ ] GPU node scales down in a timely fashion
- [ ] README has been updated
- [ ] Documentation has been written / updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by BrianEllwood** [comment]
This ticket came out of the work on this [ticket](https://github.com/ministryofjustice/analytical-platform/issues/4120)

**Comment by julialawrence** [comment]
This isn't needed, as cluster autoscaler cleans up the instance once pods are descheduled.
