### ISSUE TITLE
✨ Export list of specific application users

### ISSUE THREAD

**Issue by Ed-Bajo** [ministryofjustice/analytical-platform#4449]
### User Story

As a Super and App Admin users,  

I want to be able to export a list of all application users per application, using a button on the Control Panel. 

So that  we could ascertain the numbers of internal (MoJ staff) and external (Non-MoJ staff) users accessing the platform to use analytical applications.

### Value / Purpose

This will allow the Analytical Platform team and users to self-serve in capturing the list of application users , to better understand the people accessing the platform to use the applications. 

### Useful Contacts

@bagg3rs 
@Gary-H9 
@michaeljcollinsuk 

### Proposal

Consider how best to generate the expected list regularly.

Generate a one-off list of all current app users from Auth 0.

### Additional Information
The generic definition of Internal Users = MoJ staff with access to the Analytical Platform and MOJ staff that have access to apps created on the Analytical Platform.

The generic definition for External Users = People outside of the MoJ that have access to apps created on the Analytical Platform.

### Definition of Done

- [ ] Generate list of application users on the Analytical Platform
- [ ] Breakdown of the application users into internal users (MoJ) staff and external users (non-Moj staff) using email suffix.

**Comment by julialawrence** [comment]
Darren will reach out to the requestor to find out what is actually needed.

**Comment by julialawrence** [comment]
Maybe worth a conversation with Edwin?

**Comment by darren1988** [comment]
Managed to track this down as an action following the May check-in. The action is here https://trello.com/c/cDnhsOgm/335-share-data-on-headline-number-for-deep-dives.

The ask within the trello card is a little vague so I've reached out for more detail and to understand what deep dive this data is required for?
