### ISSUE TITLE
📖 Create build/deployment process for Analytical Platform UI

### ISSUE THREAD

**Issue by jamesstottmoj** [ministryofjustice/analytical-platform#4456]
### User Story

As a developer
I need a process of deploying the Analytical Platform UI to the AP Compute account
So that the UI can be accessed and used by the wider business

### Value / Purpose

When developing the Quicksight MVP, we will be implementing this in the new AP UI. This is not currently deployed in any account/region. We need a create a process and pipeline that will allow for the application to be deployed in the Analytical Platform Compute account.

### Proposal

Things to consider

- CI/CD pipeline and deployment method (e.g not Flux)
- Environment and secrets management
- Any potential improvements over how we deploy the control panel

### Additional Information

Dependent on #4458

### Definition of Done

- [x] CI/CD Pipeline is set up for AP UI
- [x] Environment management defined 
- [x] AP UI is deployed to AP Compute

**Comment by michaeljcollinsuk** [comment]
Created a related ticket to refactor the AP UI codebase https://github.com/ministryofjustice/analytical-platform/issues/4581

**Comment by michaeljcollinsuk** [comment]
2/7/24
Excalidraw diagram outlining the deployment process https://mojdt.slack.com/archives/C06NFN4FMNG/p1719923719857789?thread_ts=1719921985.925189&cid=C06NFN4FMNG

Started work on the helm charts, draft PR open https://github.com/ministryofjustice/analytical-platform-ui/pull/193

**Comment by jacobwoffenden** [comment]
really early stage deployment to APC, need to update Entra app redirect URIs to include the new hostnames
