### ISSUE TITLE
📖 Design the architecture of the AP UI

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#4458]
### User Story

As a developer
I need a clear design of the architecture of the AP UI
So that I know what needs to be implemented

### Value / Purpose

Designing the architecture of the AP UI before starting on implementation will ensure it meets our requirements

### Hypothesis

N/A

### Proposal

Design the architecture of the AP UI, in order to drive the implementation of our Quicksight and Lake Formation MVP.

The design should consider:
- Required services (e.g. RDS, Redis)
- Technologies to use
- Design system implementation
- API calls to AWS services
- Location of infrastructure and services (e.g. which AWS accounts)
- Integration with existing applications (e.g. Control Panel)
- Monitoring
- Security
- Potential for further expansion
- Potential risks

Suggested outcome is an Excalidraw diagram that maps out the architecture, alongside any further notes.

### Definition of Done

- [x] Excalidraw diagram of agreed architecture
- [ ] More detailed notes as required

**Comment by jacobwoffenden** [comment]
Excalidraw AP UI in Slack Canvas https://moj.enterprise.slack.com/canvas/C04M8224WCV?focus_section_id=temp:C:MLB50b8137169e944fe8b0652389
