### ISSUE TITLE
💨 Airflow: Upgrade to latest version

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#4470]
The purpose of this ticket is to upgrade the version of AWS Managed Apache Airflow. Whether we do this or not is up for debate but this ticket serves as a note that this action needs to be done and as a precursor to another ticket which will say that this need to be done in code and be picked up automatically in future.

### Value / Purpose

Standard Practice.

### Additional Information

[AWS Docs on Airflow Versions](https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html)
[Airflow Supported Versions](https://airflow.apache.org/docs/apache-airflow/stable/installation/supported-versions.html)

### Definition of Done

- [ ] MWAA development environment upgraded to latest version
- [ ] MWAA production environment upgraded to latest version

**Comment by jacobwoffenden** [comment]
Closing as we aren't upgrading the current MWAA, we are going to build a new MWAA in APC and migrate DAGs over
