### ISSUE TITLE
📖 Investigate issue with renaming files and folders in S3

### ISSUE THREAD

**Issue by AntFMoJ** [ministryofjustice/analytical-platform#4516]
### User Story

As an engineer
I expect to be able to rename files and folders in S3 using my alpha user
So that I can do my work.

### Value / Purpose

A [support ticket](https://github.com/ministryofjustice/data-platform-support/issues/640) came in regarding a user (and his team) not being able to rename files or folder in their S3 bucket, which they had previously been able to do. The issue was remedied by adding `s3:GetObjectTagging` and `s3:PutObjectTagging` actions to their alpha-user permissions (s3-access), however the cause of this issue still needs investigating.

### Proposal

Look into cause of lost permissions to rename S3 files/folder and implement fix.

### Definition of Done

- [ ] Investigate cause of lost permissions
- [ ] Implement fix if needed
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by ltd-pa** [comment]
If relevant, I also had this issue, on more than one S3 bucket
