### ISSUE TITLE
🐞 Fix DBT-Docs-Generate so Catalog Team can ingest on a regular schedule

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#4550]
### Describe the bug.

[As per this slack thread](https://mojdt.slack.com/archives/C03B3UTAJJ1/p1717663144100799), a number of tables currently exist in main in `create-a-derived-table` that are not deployed via athena in prod. This leads to the `docs-generate` workflow failing, as it attempts to retrieve docs info on all tables in main, as opposed to all deployed tables. The identified tables need either moving into an isolated, non-main branch, or deploying once and pausing.

### To Reproduce

1. Go to Create-A-Derived-Table's 'Actions' tab
2. View the run history of `dbt-docs-generate`

### Expected Behaviour

Docs generate should be able to run without failing. Immediate fix is to move tables out of main until a decision is made on where to put them (main or feature branch). Another ticket should be made to explore conditional logic that checks a table's deployment schedule before generating docs, but this is out of scope for this bug.

### Additional context

Worth checking with the #data-modelling channel who the owner of `derived_delius_data_first` is, as this is the main offender.

**Comment by julialawrence** [comment]
Sorted in the first week of this sprint not moved because we live in anarchy.
