### ISSUE TITLE
 ✨ Manual Import/Export of files into VSCode

### ISSUE THREAD

**Issue by coau** [ministryofjustice/analytical-platform#4556]
### Describe the feature request.

Add an ability to import files into VSCode similar to RStudio. I know that I should be using git, but sometimes it is just much more convenient to download results directly to my machine

### Value / Purpose

Give option to simplify development process

### User Types

VSCode users

**Comment by jacobwoffenden** [comment]
@coau this is already built into VSCode, you need to alt-click in the explorer pane

![Image](https://github.com/ministryofjustice/analytical-platform/assets/15148673/1ee0e473-ac2f-4625-8193-44d2c932812e)

**Comment by coau** [comment]
@jacobwoffenden, turns out it's very simple. Thank you!
