### ISSUE TITLE
😈 Send Notification to Main Channel on Failed Terraform Applies

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4576]
### User Story

As an AP Engineer, I would like to be prompted when a terraform apply fails after a merge so the code can be fixed as quickly a possible.

### Value / Purpose

This will allow us to maintain our main repository in a deployable state always.

### Useful Contacts

Analytcal Platform Team

### User Types

Ops Engineers

### Hypothesis

If we are promptly notified of failures this will improve the overall posture of our platform

### Proposal

Add a slack notification when a terraform apply fails. If we limit it to applies only we should minimise spam.

### Definition of Done

- [ ] Webhook implemented
- [ ] Noisiness tuned
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
Draft PR created. [Documented the process](https://mojdt.slack.com/archives/C04M8224WCV/p1719327670904279) for future use, will share this in #github-community when I've confirmed this process works.

**Comment by Gary-H9** [comment]
PR merged with slight alterations courtesy of @jacobwoffenden
