### ISSUE TITLE
 ✨ Add Docker to VSCode

### ISSUE THREAD

**Issue by coau** [ministryofjustice/analytical-platform#4592]
### Describe the feature request.

Add docker engine to VSCode

### Describe the context.

I am developing Python code. While conda and .pyenv are fine, I need finer control of the development environment. Docker is going to solve this problem nicely

### Value / Purpose

Improve development experience

**Comment by jacobwoffenden** [comment]
@coau unfortunately the current architecture of Analytical Platform doesn't allow for this.

Analytical Platform's tooling runs on Kubernetes where access to the host's Docker daemon is deemed a security risk, additionally Kubernetes and Amazon's Elastic Kubernetes Service have dropped support for Dockershim, and now we use containerd.

https://kubernetes.io/blog/2022/02/17/dockershim-faq/

https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html

**Comment by coau** [comment]
@jacobwoffenden, thank you.
