### ISSUE TITLE
 ✨ IAM perm for mlflow-access repo to have access to alpha-analytical-platform-mlflow-development bucket on AP

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#4593]
### Describe the feature request.

I have a new repo called [mlflow-access](https://github.com/moj-analytical-services/mlflow-access) which mimics database access repo in giving users control to setup experiments and permissions in MLFlow Tracking Server on the AP. However, the repo needs to assume a role to be able to make changes to the following bucket `s3://alpha-analytical-platform-mlflow-development` and update the Athena table `mlflow_access.users` when a github action is run.

Not sure what policies this needs though, sorry.

**Comment by jacobwoffenden** [comment]
@mshodge I've created `arn:aws:iam::593291632749:role/github-mlflow-access` for you to use from your repository, if it needs fails and needs permissions adding, please raise a support issue

Cheers

Jacob
