### ISSUE TITLE
🐞 Migrate high usage MoJAS private repositories

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#4597]
### Describe the bug.

As per [this](https://mojdt.slack.com/archives/C05L0KBA7RS/p1719407206568719) thread GitHub Actions minutes are being used up quickly, last month they ran out. The purpose of this thread is to rectify this partially in the short term by taking action on the `airflow` and `create-a-derived-table`

**Comment by jacobwoffenden** [comment]
- https://github.com/moj-analytical-services/create-a-derived-table/pull/1667
- https://github.com/moj-analytical-services/airflow/pull/3800
