### ISSUE TITLE
Deploy Amundsen Data Catalogue Candidate

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#460]
## User Story

Identify a catalogue that we can stand up and start learning from quickly

## User Type(s)

Data Engineers

## Value

There is an immense value in assessing something based on interacting with vs reading about it, therefore build quick, assess fast and discard fast. Therefore, there is immense value to identify something quickly buildable and build it.

## Questions / Assumptions / Hypothesis

As ever, we accept the assumption that we might not use what we build. That is an acceptable risk that becomes less acceptable the longer we put off actually building

### Proposal
A proposal that is something testable, don't worry whether it works or not, it's a place for ideas.

Pick something, build something, profit. 

## Definition of done

- [ ] Build something
- [ ] Demo it
- [ ] Demo it to other teams
- [ ] Draw up some conclusions

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
@jhpyke, @Emterry, @julialawrence and myself tried to deploy Amundsen with their guide https://www.amundsen.io/amundsen/k8s_install. It doesn't work. @julialawrence also tried with Docker Compose, and had the same issues.

Firstly, the out-of-the-box image DOESN'T have OIDC built in, you have to build and push it to a container registry. ([source](https://www.amundsen.io/amundsen/authentication/oidc/#building-frontend-with-oidc))

Next, the versioning strategy for the chart and components is hard to decipher, there doesn't seem to be a total release.

Next, the container images run as root, so we'd have to build our own, but the Dockerfiles aren't reproducible builds.

Next, community support via their GitHub is lacking, issues go stale and just close.
