### ISSUE TITLE
📖 Investigate Lake Formation Tags

### ISSUE THREAD

**Issue by jamesstottmoj** [ministryofjustice/analytical-platform#4609]
### User Story

As a developer
I want to investigate use of lake formation tags to grant access to resources
So that I can assess if they are the appropriate tool to use

### Value / Purpose

By investigating tags, we can assess their suitability.
Go through tag creation process, applying to a resource and a principal and see what access is granted.
Try combination of resource based access management and tag based access management.
See how to apply tags with a resource that is shared cross account

### Useful Contacts

@jamesstottmoj

### Definition of Done

- [x] Document written explaining process

**Comment by jamesstottmoj** [comment]
Document can be found [here](https://docs.google.com/document/d/1RrZXreH7ngtgmlK3Ld5uqnioSk1HIgUg)

**Comment by michaeljcollinsuk** [comment]
Good work, useful findings!
