### ISSUE TITLE
🎨 Update Gov UK Frontend and MOJ Frontend in Control Panel

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#4645]
### User Story

As a AP user
I expect the Control Panel to use the latest gov uk and moj frontend styles and components
So that I get a better user experience

### Value / Purpose

The frontend dependencies have fallen far behind the latest versions, which means we use some outdated styles and logos (such as the crown image on login and used as the favicon). 

### Proposal

Update GOV UK Frontend and MOJ Frontend libraries to the latest version.

As there are major version increases, this will need some manual work within the codebase to ensure it is working. For example, GOV UK frontend has changed the path where assets sit, so we need to update our sass files to reference the new location for the static to build.

In order to do this correctly and accurately, we need to read through the release notes for the major version releases to check for breaking changes. For GOV UK frontend this is:
- [v4.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0)
- [v5.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0)

For MOJ Frontend:
- [v2.0.0](https://github.com/ministryofjustice/moj-frontend/releases/tag/v2.0.0)

Once we have the static building locally successfully, run the application and check everything looks and works as expected.

### Definition of Done

- [x] Update Gov UK Frontend to latest version, following release notes
- [x] Update MOJ Frontend to latest version, following release notes
- [x] Static builds locally 
- [x] Run application locally and check it appears correct
- [x] Ensure latest images/logos (such as the crown) are correct
- [x] Deploy to dev for further testing from the team
- [x] Deploy to prod

**Comment by jamesstottmoj** [comment]
Updates to MoJ frontend and GovUK Frontend in control panel. Added some functionality to hide/show forms when something is selected. Dev PR created [here](https://github.com/moj-analytical-services/analytical-platform-flux/pull/1276)

**Comment by michaeljcollinsuk** [comment]
Deployed to production on 6/8/24
