### ISSUE TITLE
📖 Determine IAM permissions required when using hybrid mode

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#4659]
### User Story

As a engineer
I need to know which permissions an IAM user requires to access data when using LF hybrid mode
So that we can apply these permissions to existing IAM roles

### Value / Purpose

We need to use hybrid mode to ensure users do not lose access to their data. We need to ensure that users IAM roles have the required permissions to use Lake Formation hybrid mode

### Proposal

Determine permissions required to use Lake Formation hybrid mode to ensure users do not lose access to their datasets.

### Additional Information

Related to findings from https://github.com/ministryofjustice/analytical-platform/issues/4359
### Definition of Done

- [x] Required permissions identified and documented
- [ ] Follow-on ticket raised

**Comment by julialawrence** [comment]
Good ticket for someone who's not touched LF

**Comment by BrianEllwood** [comment]
The permissions required when using Lake formation hybrid mode were identified in the work for this [ticket](https://github.com/ministryofjustice/analytical-platform/issues/4359) 

The findings are recorded in this [document](https://docs.google.com/document/d/1k-vvF9d7kgGMBtPDpXgRyPFaRrUF6iDU8WqanUJwNRw/edit)

The following permission needs granting to the users prior to the implementation of Lake Formation Hybrid mode to avoid breaking the users access: `lakeformation:GetDataAccess`

This is the AWS  [documentation](https://docs.aws.amazon.com/lake-formation/latest/dg/upgrade-glue-lake-formation-step3.html)

**Comment by BrianEllwood** [comment]
Sorry marked as done in error

**Comment by BrianEllwood** [comment]
I will check in standup if any follow up tickets are required.

**Comment by BrianEllwood** [comment]
follow on ticket [4707](https://github.com/ministryofjustice/analytical-platform/issues/4707)
