### ISSUE TITLE
📖 Reveal IP Addresses to App Owners

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#4747]
### User Story

As a App Owner on the AP Control Panel
I expect to be able to see the IP addresses of the IP Allow Lists
So that I can administer the application

### Value / Purpose

Removes a lot of support issues.

### Proposal

Add this information to the lists of ranges which users see.

### Definition of Done

- [x] Update the Control Panel View to include this information

**Comment by michaeljcollinsuk** [comment]
Changes have been deployed to dev for testing

**Comment by michaeljcollinsuk** [comment]
Deployed to production on 6/8/24
