### ISSUE TITLE
🔭 Onboard DPR to Observability Platform

### ISSUE THREAD

**Issue by harichintala1** [ministryofjustice/analytical-platform#4754]
### Describe the feature request.

The Observability Dashboard is designed to provide a comprehensive view of all critical metrics necessary for monitoring the health, performance, and security of DPR systems. This single pane of glass approach ensures that all relevant data is consolidated in one place, facilitating quick and informed decision-making. 

### Describe the context.

Onboard DPR AWS Custo Metrics to Observability Platform

### Value / Purpose

Centralized Monitoring: All essential metrics are available in one place, reducing the need to switch between different tools.

-  System Performance Metrics
- Application Health Metrics
- Network Metrics
- Custom Metrics

**Comment by darren1988** [comment]
Priority ticket for sprint 22

**Comment by jacobwoffenden** [comment]
Have reached out to @harichintala1 to understand what accounts need onboarding

**Comment by jacobwoffenden** [comment]
Hi @harichintala1

Your accounts have been onboarded to Observability Platform,

development, preproduction and test are accessible using dev
production is accessible using alpha

Until you amend [this code](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/digital-prison-reporting/observability-platform.tf#L8) as per our Slack conversation, your data sources **will not be available** in Grafana

Cheers,

Jacob
