### ISSUE TITLE
Airflow Migration: Building out Airflow Infra in MP

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#479]
## User Story

We would like to replicate the Airflow Pulumi stack built and deployed into our sandpit account in our new MP account using terraform.

## User Type(s)

Ops Engineers and Airflow Engineers

## Value

Beginning stages of Airflow migration out of AP into a MOJ hosting platform

### Proposal
A proposal that is something testable, don't worry whether it works or not, it's a place for ideas.

In essence, convert the Pulumi code building MWAA infrastructure (minus networking) into terraform on MP. This is also a good pairing opportunity for learning how to work in Modernisation Platform Environments. 

## Definition of done

- [ ] Terraform code created and deployed into MP Sandbox
- [ ] Documentation for using MP is created
- [ ] another team member has reviewed
- [ ] Code is linted and statically scanned.
- [ ] Follow-on stories raised. 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
Superseded by https://github.com/ministryofjustice/data-engineering-airflow/issues/116
