### ISSUE TITLE
🕵️ JupyterLab user research

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#4930]
### User Story

As the Analytical Platform team
I need to know what users are doing and want from JupyterLab
So that we can build a product that fits their need

### Value / Purpose

The work in #4607 has changed from a feature parity build with the COTS JupyterLab data science notebook, to a vanilla instance with the tools they need to install packages themselves (via Conda), however we appreciate this might not be the most user friendly replacement

### Useful Contacts

@jacobwoffenden

### User Types

Product Engineering

### Hypothesis

If we do user research of JupyterLab users
Then we can build a better product offering

### Proposal

@RNTjustice and the team prepare and engage in user research with a mixed pool of users

### Additional Information

Blocks #4607 

### Definition of Done

- [x] Kick off session & Questions - [Miro](https://miro.com/app/board/uXjVKrFm0Ao=/)
- [x] Users identified
- [x] Recruitment
- [x] Questions prepared
- [x] Run sessions
- [ ] Sense making & next steps

**Comment by Gary-H9** [comment]
Users granted access to the new release in Production:
- mattfunnell
- creader-moj
- mratford
- vmohanram

**Comment by Gary-H9** [comment]
Removed access from the above users.

**Comment by Gary-H9** [comment]
Users granted access to the new release (`JupyterLab 1.0.0-rc2`) in Production:

- mattfunnell
- creader-moj
- mratford
- vmohanram
