### ISSUE TITLE
📖 Create Support Runbook for Airflow

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#4931]
### User Story

As a member of the AP team
I need/want/expect to support users of our MWAA instance
So that they can use the service succesfully.

### Value / Purpose

This runbook will empower members of the team to support the tool with a simple flow of issues to look for. In doing so, we will empower a number of team members to tackle support issues that previously may have felt unable to help.

### Useful Contacts

@jhpyke

### Hypothesis

If we... write a runbook for support
Then... engineers will have more tools for approaching Airflow related support issues

### Definition of Done

- [ ] Documentation has been written / updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
I believe this has been completed as per [this](https://github.com/ministryofjustice/analytical-platform/pull/4778) merge.
