### ISSUE TITLE
📊 QuickSight Trial Information: Damilola

### ISSUE THREAD

**Issue by dami-moj** [ministryofjustice/analytical-platform#4936]
### Use Case Description

Legal Aid Stats Team is very interested in participating in the trial of the tool. 

**Use Case:**

The legal aid stats team currently manages [6 public facing](https://www.gov.uk/government/statistics/a-guide-to-legal-aid-statistics-in-england-and-wales/legal-aid-statistics-data-visualisation-tools) and 2 internal PowerBI interactive dashboards as part of our quarterly and monthly analysis reports. Given the isolation of PowerBI from the AP, these dashboards require extra efforts in maintenance and resolving issues with versioning and data exports, among others. 

We believe QuickSight's intuitive interface and integration with the Analytical Platform could streamline this process. 

Specifically, we hope with QuickSight, we will be able to facilitate easier sharing and collaboration on data visualizations across teams and stakeholders. Also, reduce the time and effort required to create and update dashboards, enabling faster decision-making. 

### Dataset(s) to Visualise

criminal_legal_aid_data_share - alpha-ls-laa-datashare

### Are you an Analytical Platform Admin of the S3 Data Warehouse for the Datasource(s)?

Yes

### Audience Details

- Other AP users 
- MOJ staff (LAA)

**Comment by julialawrence** [comment]
Hiya @dami-moj are you able to get in touch with me on Slack or Teams please?
