### ISSUE TITLE
📖 Test Validation script for Airflow Repo with Updated Regex Package

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#4998]
### User Story

As an airflow user
I want the validation script to spend less than 5 minutes running
So that I can get on with my day.

### Value / Purpose

Currently [the version of regex](https://github.com/moj-analytical-services/airflow/blob/9c24b77e4e4e49f3dbdc8e393f7d7245372f771f/requirements-validation.txt#L12) used for validation in Airflow is about 4 years old, and takes an extremely long time to install as part of workflows. As such, we should update to the latest version of regex (as in [this PR](https://github.com/moj-analytical-services/airflow/pull/4186)) to save about 5 minute per run. This will save a significant amount of compute time, and as such, money for the business.

### Useful Contacts

@jhpyke

### Hypothesis

If we update regex
Then validation will continue working the way we expect

### Proposal

We only use `fullmatch` and `compile` from `regex`. As such, could compare the code for those functions between versions for functionality changes. Alternatively, we can try and manually violate each of the policies that rely on these functions and ensure they still work as intended.

### Additional Information

Could be used as an opportunity to write unit tests for validation?

### Definition of Done

- [x] We are able to update the regex package version
- [x] Validation script still performs as expected
- [ ] Support is prepared to respond to any issues arising from the upgrade

**Comment by jacobwoffenden** [comment]
Resolved by https://github.com/moj-analytical-services/airflow/pull/4186
