### ISSUE TITLE
📊 QuickSight Trial Information: OPG BI Dashboards

### ISSUE THREAD

**Issue by gwionap** [ministryofjustice/analytical-platform#5005]
### Use Case Description

OPG have a number of projects that could make use of BI functionality. For example, OPG requires MI for their Use an LPA digital service, where they have the intention to link up monthly service usage reports to OPG's existing Lasting Powers of Attorney (LPA) case management data available on the AP. This could provide business insight on:
- The institutions who are and who are not using the digital product when requests are created for them on the service
- The profile of the type of LPA customers which are currently using the service and identify the gaps in OPG's customers to help grow the usage of the service
The ability to implement a BI solution via QuickSight would also allow OPG users to understand the functionality available compared with PowerBI, which is currently the organisations BI tool of choice.

### Dataset(s) to Visualise

Database 1 - `guardianship_derived`
Database 2 - `sirius_derived`

### Are you an Analytical Platform Admin of the S3 Data Warehouse for the Datasource(s)?

No

### Audience Details

Dashboard(s) will be internally used by both OPG operations and user research staff and by Digital's user researcher to identify external stakeholders to create content for these conversations.

### Additional Information

On the listed databases, these form the output layer of our data warehouse in create-a-derived-table and we foresee any BI products / tables being created in one of these databases. We are not an admin for the S3 bucket (`mojap-derived-tables`), though we have control / sign off of use of the data location via data-engineering-database-access.

**Comment by tom-webber** [comment]
Team has been onboarded, and UR session is set up
