### ISSUE TITLE
⬆️ Upgrade `analytical-platform-compute` cluster to `1.31`

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#5066]
Upgrades: [test](https://github.com/ministryofjustice/analytical-platform/issues/5060), [development](https://github.com/ministryofjustice/analytical-platform/issues/5065), [production](https://github.com/ministryofjustice/analytical-platform/issues/5066).

### User Story
As a platform engineer
I expect my clusters to be up to date
So that they don't whither and die, or end up on extended support because 💰

### Useful Contacts
Gary, Jacob, Julia, Emma.

Proposal
Upgrade the cluster - [analytical-platform-compute-production](https://eu-west-2.console.aws.amazon.com/eks/home?region=eu-west-2#/clusters/analytical-platform-compute-production) in `analytical-platform-compute-production`

Additional Information
[kubernetes-release-calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)

### Definition of Done

- [ ]  Research the components that make up the cluster and understand if the impact/dependencies of upgrading.
- [ ]  Understand and document how to test the cluster functionality for when this is done in Production
- [ ]  Upgrade the cluster to 1.31 from 1.30
- [ ]  Document findings and present to the team

**Comment by jacobwoffenden** [comment]
Completed in https://github.com/ministryofjustice/analytical-platform/issues/5661
