### ISSUE TITLE
🔖 Add consistent GitHub labels to our repositories

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#52]
## User Story

As a platform engineer
I want labels on my GitHub  pull requests
So that I can quickly filter pull requests

## Value

Labels provide a way to filter certain types of issues e.g. `bug` or custom labels e.g. `vpc` or `networking` which are useful for troubleshooting and also look pretty 🦄 🌈
Useful when using GitHub Projects ✨

## Questions
Can as a team review the default labels add any custom and deploy them as [code](https://registry.terraform.io/providers/bateller/github/latest/docs/resources/issue_label)
- should we apply to AP repos?

## Definition of done

- [ ] discussed as team and created initial label list
- [ ] readme has been updated with link to code?
- [ ] Github Action is applying labels to issues and PR's 🤖
- [ ] labels deployed to our repo's 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
For pull requests we can use https://github.com/actions/labeler and some rules on file paths, but right now I'm not sure how we could auto add labels for issues 🤔

**Comment by bagg3rs** [comment]
Correct there is this [action](https://github.com/github/issue-labeler), but I did actually get this mixed up. Ticket is to define our labels and have updated to reflect that. Labeler is enabled via #87 but we still need to make make sure we are happy with whats there and to remove any of the default labels that are unneeded.
