### ISSUE TITLE
🐞 Visual Studio Code: `venv` deactivation

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#5243]
> [!CAUTION]
> Solve [this](https://github.com/ministryofjustice/analytical-platform/issues/5242) bug first. 

### Describe the bug.

User feedback:

VS code will forget my virtual environment regularly, often 2 or 3 times a day. I am not sure if there is a VS code specific guide, but I am having to re run the R studio set up guide every time (specifically source venv/bin/activate  and source ~/.bash_profile , and then re setting up DBT as that is what I am using).

**Q:**  when you say forget, can you describe this a bit more, I rarely use venv so just want to understand this for troubleshooting purposes. If you have a venv , does the terminal eject you from that venv, or does all the configuration of the venv just seem to disappear?

**A:** All the venv related files are still there, all that happens is that it is deactivated, so I have to reactive it using these source venv/bin/activate  and source ~/.bash_profileand then set up dbt again using dbt deps

### Additional context

Raised in relation to [this](https://mojdt.slack.com/archives/C06TFT94JTC/p1725024104545289) Slack thread.

**Comment by Gary-H9** [comment]
Note: https://github.com/ministryofjustice/data-platform-support/issues/657#issuecomment-2152826042 + https://stackoverflow.com/a/416931

**Comment by Gary-H9** [comment]
Spoke to the user in question about this, advised to use `bashrc`. Will update docs by the end of this week provided it's working as expected.

**Comment by Gary-H9** [comment]
[PR](https://github.com/moj-analytical-services/user-guidance/pull/443) awaiting for this.

**Comment by Gary-H9** [comment]
This will be picked up post the resolution of the [this](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=78284583) ticket.

**Comment by jacobwoffenden** [comment]
user guide pull request merged
