### ISSUE TITLE
 ✨ Update Slack new joiners message 

### ISSUE THREAD

**Issue by andyrogers1973** [ministryofjustice/analytical-platform#5286]
### Describe the feature request.

Can I request that the Slack message shown to users when they join the #ask-data-engineering Slack channel is changed.

Please update the new joiners message to:

:new: to the Analytical Platform and need an account then head over to [Join GitHub](https://join-github.service.justice.gov.uk/)

**Comment by bagg3rs** [comment]
Great idea @andyrogers1973 we talked about this at Away Day

- [x] Update Slack
- [x] Update User Guidance

**Comment by bagg3rs** [comment]
Updated docs https://github.com/moj-analytical-services/user-guidance/commit/6b9b51398c4db50afd88565e69eaa1c58adf9133
