### ISSUE TITLE
Recruit Data Platform Users - HMPPS

### ISSUE THREAD

**Issue by ChikC** [ministryofjustice/analytical-platform#535]

**Comment by ChikC** [comment]
Initial engagement email sent to Howard Smith. Awaiting response.

**Comment by ChikC** [comment]
A session has been scheduled for 12th June at 1 pm.

**Comment by ChikC** [comment]
Meeting scheduled for the 19th of June.

**Comment by murdo-moj** [comment]
We talked to Howard. He suggested we contact Grant Chequer about the ARNS dataset as a data product candidate.

**Comment by ChikC** [comment]
Edward and Greg are engaging with the HMPPS to see which use cases are ready for the team to explore. 

Edward has given an indicative time frame of 2 months before we can be confident of the priorities to focus on. 

This was fed back to the team at Retro - 22/06/23.
