### ISSUE TITLE
📥 Maintenance - Cloud Development Base Image 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#5389]
> [!CAUTION]
> This image underpins many containerised services in the Analytical Platform.

### User Story
As a… engineer on the Analytical Platform
I need/want/expect to… keep Cloud Development Environment Base up to date
So that… security / best practice etc
### Definition of Done
- [x] Merge any open dependabot Pull Requests in the Analytical Platform Cloud Development Environment Base [repository](https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-base/pulls). 
- [x] Create new [release](https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-base/releases).

**Comment by jacobwoffenden** [comment]
[1.2.0](https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-base/releases/tag/1.2.0) released
