### ISSUE TITLE
:monocle_face: Embed AP Compute Quicksight within Control Panel

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5532]
### User Story

As a developer
I want to embed the AP Compute Quicksight instance within Control Panel
So that we can offer access to AP users

### Value / Purpose

A solution to deliver Quicksight to users of the the AP.

### Hypothesis

That we can embed the Quicksight running int he AP Compute account within the Control Panel, which runs in the AP-prod account

### Proposal

1. Port code from the AP UI implementation where possible
2. Create an embed URL for users using their Justice email, which should already have been captured
3. For users who have not completed the auth process which captures their Justice email, display an error and ask them to authenticate
4. New top-level nav button to access Quicksight
5. Should embed quicksight for the corresponding environment:
    - Dev control panel should embed the Quicksight instance in AP compute dev
    - Local control panel should embed the Quicksight instance in AP compute dev
    - Prod control panel should embed the Quicksight instance in AP compute prod

### Definition of Done

- [ ] Confirmation that AP Compute Quicksight can be embedded within Control Panel
- [ ] (Optional) if not possible, reasons documented

**Comment by jamesstottmoj** [comment]
There was an issue with assuming the role in production. Adding logging seems to have resolved said issue. Have not been able to reproduce since. Moving to done
