### ISSUE TITLE
:sparkles: Add API endpoint to Control Panel that returns a users Justice Email

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5533]
### User Story

As a developer
I need the control panel API to return users Justice email address
So that we can programatically match a users github identity with their justice identity from other services

### Value / Purpose

Will allow us to use a users Github identity to retrieve their Justice identity. We can then use this to sync permissions granted from the [data-engineering-database-access repo](https://github.com/moj-analytical-services/data-engineering-database-access/) with Lake Formation permissions against the user's Justice identity.

### Hypothesis

If we... have way to programatically retrieve a users Justice email from their Github username
Then... we can use the Justice identity to grant LF permissions when their access changes in  [data-engineering-database-access](https://github.com/moj-analytical-services/data-engineering-database-access/) 

### Proposal

- Check existing API endpoints in Control Panel for one that could be used
- If one is not present, and a new endpoint that takes a users Github username, and as a minimum returns the users Justice Identity
- Consider any other details about the user that we may want to return
- Ensure adequate authentication is in place for the API endpoint. We should be able to utilise the existing auth process, which uses Auth0

### Definition of Done

- [x] API endpoint implemented - UPDATE used existing endpoint
- [x] API endpoint documented - UPDATE not required as used existing endpoint
- [x] API endpoint tested using a test application set up in Auth0 - UPDATE details captured in comments below
- [x] Any follow up tickets raised - UPDATE none required

**Comment by michaeljcollinsuk** [comment]
UPDATE 18/10/24:

- An endpoint already exists that, when authenticated, takes a users Github ID and returns a JSON response with details about the user. I will update this to include the users `justice_email` field.
- We will need to authenticate via Auth0: 
    - We will create a M2M application to represent the `data-engineering-access` action, which is linked to the Control Panel API. Scope can be limited to `retrieve:user` for extra security.
    - Request can then be made to Auth0 made with the client credentials of the M2M application, which is verified and returns an access token for the Control Panel API
    - Use the returned access token to make a request to the Control Panel user detail endpoint

The endpoint to be used in Control Panel is:
```
https://controlpanel.services.analytical-platform.service.justice.gov.uk/api/cpanel/v1/users/github|<github_id>/ 
```
Example when encoded:
```
https://controlpanel.services.analytical-platform.service.justice.gov.uk/api/cpanel/v1/users/github%7C12345678/
```

**Comment by michaeljcollinsuk** [comment]
PR to amend endpoint merged and deployed to dev, but not prod.

[M2M application for dev is in Auth0 - named database-engineering-access-dev](https://manage.auth0.com/dashboard/eu/dev-analytics-moj/applications/0h5GegC3NPElWndsDssG6L3nJPlisIqP/settings)

[M2M application for prod is in Auth0 alpha tenant - named data-base-engineering-access-alpha](https://manage.auth0.com/dashboard/eu/alpha-analytics-moj/applications/bgqVuAtZaK3dM3x1pf5mbFXATRWpqNop/settings)

Full instructions (along with a UI to test) on how to generate an access token and then use it with the Control Panel API are available in auth0. Key points below:

The endpoints to use to generate an access token is (for dev and prod):
```
POST https://dev-analytics-moj.eu.auth0.com/oauth/token
POST https://alpha-analytics-moj.eu.auth0.com/oauth/token
```
Your request data must include your client credientials, and the correct `audience` for your environment. The `audience` is the identifier of the API application in Auth0.

Full example of data to include in the POST request:
```
'{"client_id":"<CLIENT_ID>","client_secret":"<CLIENT_SECRET>","audience":"<AUDIENCE_URN>","grant_type":"client_credentials"}'
```
You can then use the returned access token with an Authorization Header to request data from the Control Panel API:
```
'authorization: Bearer <access_token>'
```

**Comment by michaeljcollinsuk** [comment]
@julialawrence closing as complete but details of endpoints and where to find credentials are listed above

**Comment by julialawrence** [comment]
Tested and works perfectly!
Code here:
https://github.com/moj-analytical-services/data-engineering-database-access/pull/4392
