### ISSUE TITLE
✨ Add GSL to RStudio image

### ISSUE THREAD

**Issue by AntFMoJ** [ministryofjustice/analytical-platform#5571]
### Describe the feature request.

The `libgsl-dev` package (or similar) needs to be added to our RStudio image on AP to enable R users to use numerical computing routines via the API for R.

### Describe the context.

A support request was raised [here](https://github.com/ministryofjustice/data-platform-support/issues/857) which indicated the need for GSL to be installed on the AP RStudio image.

### User Types

Data Scientists, Data Analysts

**Comment by darren1988** [comment]
to be discussed at refinement on 8/10/24

**Comment by jacobwoffenden** [comment]
Asked user to test via https://github.com/ministryofjustice/data-platform-support/issues/857

**Comment by jacobwoffenden** [comment]
User confirmed its working

**Comment by AntFMoJ** [comment]
Thank you Jacob!
