### ISSUE TITLE
✨ Surge GPU capacity

### ISSUE THREAD

**Issue by bcrawford-moj** [ministryofjustice/analytical-platform#5580]
### Describe the feature request.

Robyn Foyster and I are running a team office day where we will set our team's a challenge involving using AI and ML models on the AP. There will be approximately 30 participants some of whom will want to use GPU simultaneously. It will be on Wednesday 13th November.

(Similar to [this](https://github.com/ministryofjustice/analytical-platform/issues/5009) ticket from earlier in the year)

### Value / Purpose

Team building and learning and development in the field of using AI on the AP.

### User Types

Data scientists

**Comment by simon-pope** [comment]
@bcrawford-moj this can be handled as a support request. Could you please close this FR and raise a support request?  Thanks!

**Comment by bcrawford-moj** [comment]
Sure, apologies - I always get it wrong.
