### ISSUE TITLE
📖 Synchronise Permissions between LakeFormation and DEDA for `mojap-derived-tables` bucket

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#5600]
### User Story

DEDA -- Data engineering database access

I would like to be able to make contents of the CaDeT output bucket (COB) available for visualisation without compromising the security and running afoul of the existing permissions while keeping prod running. One part of this requires replication of the data into a separate account covered in this [story](https://github.com/ministryofjustice/analytical-platform/issues/5599) and the other is synchronising bucket permissions between https://github.com/search?q=repo%3Amoj-analytical-services%2Fdata-engineering-database-access%20mojap-derived-tables&type=code and LakeFormation in the replicated account. The requirement is for these permissions to be updated synchronously or as near-real-time as possible.

### Value / Purpose

Security is good. No security is bad.
Making QS available quicker while avoiding risks inherent in our current MVP setup is project goal and a user need.

### Useful Contacts

Julia Lawrence Jacob Hamblin-Pyke

### Hypothesis

If we can manage the permissions in near-real-time, we will not be opening a security gap in our current setup via QS access.

### Proposal

Identify all project files in DEDA that reference `mojap-derived-tables` bucket
Implement a bolt-on terraform or pulumi component in https://github.com/moj-analytical-services/data-engineering-database-access which is triggered by changes in config and project files that mention [the COB](https://github.com/search?q=repo%3Amoj-analytical-services%2Fdata-engineering-database-access%20mojap-derived-tables&type=code) and does the following
1. Map a user's github identity to their justice identity (the goal is to use an API for this going forward, but to speed development, using a lookup list for now is acceptable)
2. Infer their QS username from their justice identity
3. Use LakeFormation sharing role that exists in APC Production to assign the QS user required LF permissions in both London and Ireland on the _replicated bucket paths_
4. Undoes these changes when the configuration files change

In order to minimise refactoring, it might be worthwhile for the new component to run on all configuration-related changes in order to avoid changing the code when new projects are added and old one are removed.

Note: Specific permissions on each bucket paths are set up in `iam_config.yaml` files under each project. Specific user permissions are defined [here](https://github.com/moj-analytical-services/data-engineering-database-access/tree/main/project_access) 

### Additional Information

There will be a follow-on story raised to replicate the datbase/tables permissions as well. Buckets are split out to identify risks. 
The replicated bucket will be managed in LF only which should simplify permissions management.

### Definition of Done

- [ ] Implement proposal
- [ ] Follow-on stories raised
- [ ] Team reviewed.

**Comment by julialawrence** [comment]
For information: https://docs.google.com/document/d/1h6lft2IWB2eImFf6_Vd6DOFkLU-FNZIC0yJncmCimOc/edit

**Comment by julialawrence** [comment]
Progress Update:
https://github.com/moj-analytical-services/data-engineering-database-access/pull/4392

* Users are mapped to their permissions for the target bucket
* Their membership in the github org retrieved
* Their github ids retrieved
* API to retrieve their justice emails tested

This should be all the needed information aside from the actual replicated bucket name needed to start composing lake formation data locations permissions.

To do as part of this story:

* Create secret for storing client id, client secret, audience and github token
* Retrieve information from secret to run operations against github, auth0 and Control Panel
* Workflows
* Code Quality

Follow-on story:
(Once Bucket replication is done)
* Create role in APC to be assumable by the role running database-access jobs to perform data permissions creations
* Crawler
* Some kind of lookup of tables to locations
* Testing

**Comment by tom-webber** [comment]
The first part of this may provide a solution for #5849
