### ISSUE TITLE
✨ Enable hourly runs in create-a-derived-table

### ISSUE THREAD

**Issue by moj-supratikc** [ministryofjustice/analytical-platform#5646]
### Describe the feature request.

See Slack thread here for full details: https://mojdt.slack.com/archives/C06TFT94JTC/p1728488760638649

We want to have the ability to run hourly workflows for a subset of models, similar to the bold-daily workflows on create-a-derived-table.

### Describe the context.

Context:
We have been building out the Avature recruitment pipelines and derived models. We are just entering a UAT period with analysts on the current user-facing facts/ dimensions.
Currently all the models are views. However the data is quite large (and growing quickly every day), and there is some fairly complex logic under the hood to generate the user-facing models. As such, the final facts/ dimensions have unusable query times (upwards of 30 seconds).
We have found that materializing the end models is much faster and results in far less data scanned (as expected!), however our operational users would not be able to use data that is a day out of date (as it would be with daily) - they need the data as close to live as possible.
Because of this, we'd want to materialize those tables hourly at minimum to meet their need.

### Value / Purpose

Will enable operational analysts to have recruitment data on prison officers that is correct to within the hour, for allocation and other operational purposes, while also having fast query times.

### User Types

Analysts, Operational Users

**Comment by simon-pope** [comment]
@moj-supratikc @pricemg I have invited you to the Request Forum on 14th October to present this to the team.  Any questions, please let me know

**Comment by simon-pope** [comment]
To be presented in request forum 21st October

**Comment by simon-pope** [comment]
Request forum: Will require a spike to ascertain whether this can be achieved, taking in to account existing AWS throughput limits and impacts on other users when this runs.  

@moj-supratikc will provide the following information that will feed in to a spike:

1. What should happen if a previous job fails/is delayed/doesn't run?
2. How many models are currently run?
3. How long do the models take to run currently?

**Comment by moj-supratikc** [comment]
Additional details

Specific models we're considering:
- Everything in the `mojap_derived_tables/models/people/avature_stg/dimensions` folder in create-a-derived-table. All upstream models of these ones are views, so should not need altering.


If a job fails:
- It should run again as normal the next hour. At the moment, the materialization will recreate the all fact/ dimension tables from scratch, so there should be no consequences of of a fail + re-run (aside from stale data). We would alert our customers when it happens.

If a job takes >1hr:
- This is a trickier one, but hopefully not one we run into any time soon. As it stands, the full set of models don't take anywhere near this long to build. We would probably want to intervene before the build times get anywhere near this and rework our modelling or split up the jobs in some way. If we need a technical solution now, I would probably say just cancel the workflow after 50 minutes has elapsed (if that sort of thing is possible?)

Build times:
- A full build of avature_base and avature_stg takes a few minutes

**Comment by simon-pope** [comment]
@moj-supratikc thanks for the above.  So we can ensure this request is correctly prioritised, what is the timeline you are working against and what is the impact if AP cannot fulfil this request?

**Comment by simon-pope** [comment]
User story created as sub-task. Will be prioritised and taken to refinement w/c 28/10

**Comment by moj-supratikc** [comment]
Thanks @simon-pope. Our pipeline is due to complete UAT by mid-Nov, but we can switch them to using views for the real-time data if they absolutely need that. I guess the main impact is a really poor user experience (>30s query times, that will keep growing), with a risk that analysts decide it's too slow to use and go back to offline excel extracts.
