### ISSUE TITLE
✨ Enable Data Engineering access to Analytical Platform's Terraform setup

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#5658]
### Describe the feature request.

As the title says, this feature request is to provide Data Engineering access to Analytical Platform's Terraform setup.

### Describe the context.

Data Engineering are embarking on a stream of work to port IaC from Pulumi to Terraform, and originally requested we create the state S3 bucket and DynamoDB tables using our repository for use in their repository.

### Value / Purpose

By giving select users access to a subset of the state bucket, they can import resources using their existing Data Engineering role.

### User Types

Data Engineering

### Proposal

Give DE roles access to 

- `aws/${ACCOUNT}/de-${COMPONENT}` in state bucket
- Any DynamoDB tables required
- Any KMS keys required

### Defintion of Done

- [x] Bucket permissions updated
- [x] DynamoDB permissions updates
- [ ] ~KMS permissions updated~
- [x] Data Engineer can _at least_ run a local init/plan

**Comment by jacobwoffenden** [comment]
@gwionap, @davidbridgwood @sivabathina2, @mamonu 

Can one of you please provide the name of the AWS role you use to access 

- `analytical-platform-data-production`
- `analytical-platform-data-engineering-production`
- `analytical-platform-data-engineering-sandbox-a`

**Comment by gwionap** [comment]
Sure, `modernisation-platform-data-eng` for both `analytical-platform-data-production` and `analytical-platform-data-engineering-production`. For `analytical-platform-data-engineering-sandbox-a` we use the same role or `AdministratorAccess`.

**Comment by jacobwoffenden** [comment]
@gwionap, @davidbridgwood @sivabathina2 @mamonu 

I've made changes to our state bucket, state locking table, and MP's data engineering policy with the hope that you should now be able to interact with our state!

All those things are now deployed so can someone try the following:

1. Follow [our guidance](https://docs.analytical-platform.service.justice.gov.uk/documentation/platform/infrastructure/developing.html) for Developing the Analytical Platform, using 1Password for SSH is optional
2. Checkout the branch `test/terraform-for-de`
3. Change directory in to `terraform/aws/analytical-platform-data-engineering-sandbox-a/terraform-testing`
4. Log in to AWS `aws-sso exec --profile analytical-platform-data-engineering-sandbox-a:modernisation-platform-data-eng`
5. Initialise Terraform `terraform init -backend-config=assume_role={role_arn=\"arn:aws:iam::042130406152:role/data-engineering-state-access\"}`
6. Plan Terraform `terraform plan`
7. Apply Terraform `terraform apply`

**Comment by gwionap** [comment]
Morning @jacobwoffenden. On `terraform plan` I get the following error:

```
│ Error: Error acquiring the state lock
│ 
│ Error message: operation error DynamoDB: PutItem, https response error StatusCode: 400, RequestID:
│ KBUN8566NGM4CAME58NISAPS6BVV4KQNSO5AEMVJF66Q9ASUAAJG, ResourceNotFoundException: Requested resource not found
│ Unable to retrieve item from DynamoDB table "global-tf-state-aqsvzyd5u9-locks": operation error DynamoDB: GetItem, https response error
│ StatusCode: 400, RequestID: USF7RRCTV97POJGIE945BHRMPRVV4KQNSO5AEMVJF66Q9ASUAAJG, ResourceNotFoundException: Requested resource not found
│ 
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
```

**Comment by jacobwoffenden** [comment]
OK, can you try this for step 5 please

```bash
terraform init -backend-config=assume_role={role_arn=\"arn:aws:iam::042130406152:role/data-engineering-state-access\"}
```

---

Rather than opting for the model of external roles interacting with S3 and DynamoDB, I have go for the approach that @ministryofjustice/modernisation-platform use for member planning, which is to initialise with a role where the backend lives. I don't think accessing DynamoDB like we were trying works as I expected.

Source:
- https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/running-terraform-plan-locally.html#run-terraform-plan
- https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/scripts/member-local-plan.sh#L25

**Comment by gwionap** [comment]
Now getting this error @jacobwoffenden when running init as per the above:

```
│ Error: Cannot assume IAM Role
│ 
│ IAM Role (arn:aws:iam::042130406152:role/data-engineering-state-access) cannot be assumed.
│ 
│ There are a number of possible causes of this - the most common are:
│   * The credentials used in order to assume the role are invalid
│   * The credentials do not have appropriate permission to assume the role
│   * The role ARN is not valid
│ 
│ Error: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: dcd84c9e-bef1-402c-b996-a36ac3a168dc, api error AccessDenied: User:
│ arn:aws:sts::684969100054:assumed-role/AWSReservedSSO_modernisation-platform-data-eng_19ac4a28d1fccd44/gwionap@digital.justice.gov.uk is not authorized to perform:
│ sts:AssumeRole on resource: arn:aws:iam::042130406152:role/data-engineering-state-access
```

**Comment by jacobwoffenden** [comment]
Thanks @gwionap, waiting on @ministryofjustice/modernisation-platform to review a pull request before we test again, will let you know when its ready

**Comment by jacobwoffenden** [comment]
@gwionap that has been merged - can you try again? 😇

**Comment by jacobwoffenden** [comment]
@gwionap confirmed `init` is working but `plan` fails with

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Cannot assume IAM Role
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on terraform.tf line 19, in provider "aws":
│   19: provider "aws" {
│ 
│ IAM Role (arn:aws:iam::684969100054:role/GlobalGitHubActionAdmin) cannot be assumed.
│ 
│ There are a number of possible causes of this - the most common are:
│   * The credentials used in order to assume the role are invalid
│   * The credentials do not have appropriate permission to assume the role
│   * The role ARN is not valid
│ 
│ Error: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID:
│ a8507b42-9ed8-49a5-8956-0b22a11969db, api error AccessDenied: User:
│ arn:aws:sts::684969100054:assumed-role/AWSReservedSSO_modernisation-platform-data-eng_19ac4a28d1fccd44/gwionap@digital.justice.gov.uk
│ is not authorized to perform: sts:AssumeRole on resource:
│ arn:aws:iam::684969100054:role/GlobalGitHubActionAdmin
│ 
```

due to

```hcl
provider "aws" {
  region = "eu-west-2"
  assume_role {
    role_arn = "arn:aws:iam::${var.account_ids["analytical-platform-data-engineering-sandbox-a"]}:role/GlobalGitHubActionAdmin"
  }
  default_tags {
    tags = var.tags
  }
}
```

it will require something similar to below where it checks the users role first

```hcl
provider "aws" {
  alias  = "analytical-platform-management-production"
  region = "eu-west-2"
  assume_role {
    role_arn = can(regex("AdministratorAccess", data.aws_iam_session_context.session.issuer_arn)) ? null : "arn:aws:iam::${var.account_ids["analytical-platform-management-production"]}:role/GlobalGitHubActionAdmin"
  }
  default_tags {
    tags = var.tags
  }
}
```

**Comment by jacobwoffenden** [comment]
Updated https://github.com/ministryofjustice/analytical-platform/pull/5745/commits/14b105ca170ce1abb1fa131f1ffe4491cd146212

**Comment by jacobwoffenden** [comment]
Hey @gwionap @davidbridgwood @sivabathina2 @mamonu

@jhpyke has tested the steps in https://github.com/ministryofjustice/analytical-platform/issues/5658#issuecomment-2426991497 and can successfully init, plan and apply using the data-eng role! 🎉 

I'll close this now - do you want to raise a follow on session and we can go over creating what we call components?
