### ISSUE TITLE
DPR Observability Configuration, Enable Custom Metrics for a Namespace

### ISSUE THREAD

**Issue by harichintala1** [ministryofjustice/analytical-platform#5669]
### Describe the feature request.

Please onboard Custom Namespace, **DPRAgentCustomMetrics**

### Describe the context.

Please onboard Custom Namespace, **DPRAgentCustomMetrics**

### Value / Purpose

Ability to push Custom Metrics into Observability Platform

**Comment by simon-pope** [comment]
Discuss in Amigos

**Comment by jacobwoffenden** [comment]
Similar to https://github.com/ministryofjustice/analytical-platform/issues/5735

**Comment by jacobwoffenden** [comment]
@simon-pope this should be done the same time as #5735

**Comment by jacobwoffenden** [comment]
Hi @harichintala1,

Apologies for the delay - this has been added.

Cheers
