### ISSUE TITLE
🐞 User report 502 error

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#5677]
### Describe the bug.

This bug ticket is being raised off of the back of [this](https://github.com/ministryofjustice/data-platform-support/issues/872) support request. 

### To Reproduce

At this moment we cannot reliably reproduce the issue. 

### Expected Behaviour

502 Bad Gateway errors should not occur.

### Additional context

- Although we initially believed that this error was isolated to the user Andreas we have since had two individual reports of the same issue from the AP engineering team looking at this - Michael and Jacob. The differentiating factor between Andreas and our experience is that Andreas constantly has a 502 error but for ourselves we have only seen it intermittently.
- Andreas see the error when using all of the AP tooling, VSCode, RStudio and JupyterLab.

Other information.
- Andreas did have extensive [issues](https://github.com/ministryofjustice/data-platform-support/issues/419) accessing previously.
- We made a change relating to Auth0 last Thursday.
- Jacob W investigating updating Lua
- An avenue to explore is installing tcpdump on the relevant container and dumping whilst the error occurs or more generally doing a dump in the correct place

**Comment by Gary-H9** [comment]
User has [reported](https://github.com/ministryofjustice/data-platform-support/issues/872#issuecomment-2414061777) that it is now working for them - @ 15:19. 🤷 

There is also work going on in the Operations Engineering space today, we're not sure if this could have had an effect.

**Comment by jacobwoffenden** [comment]
We've published [1.0.0](https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-nginx-proxy/releases/tag/1.0.0) of the new `analytical-platform-cloud-development-environment-nginx-proxy`

**Comment by jacobwoffenden** [comment]
RCA document: https://docs.google.com/document/d/124LbTyFhAKaBRN7CUFz8kVQpykONNq9ItZWSkgqCj_Y

**Comment by michaeljcollinsuk** [comment]
We provided an update to the user that reported the issue in https://github.com/ministryofjustice/data-platform-support/issues/872#issuecomment-2426415612

All findings recorded in the RCA document: https://docs.google.com/document/d/124LbTyFhAKaBRN7CUFz8kVQpykONNq9ItZWSkgqCj_Y

As we cannot take this any further now, and the user has reported the issue has resolved for them, closing this issue for now.
