### ISSUE TITLE
Add data reconciliation custom metrics namespace for DPR

### ISSUE THREAD

**Issue by tom-ogle-moj** [ministryofjustice/analytical-platform#5735]
### Describe the feature request.

Please onboard Custom Namespace, **DPRDataReconciliationCustom** for the[ Digital Prison Reporting cloudwatch metrics integration](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/digital-prison-reporting/observability-platform.tf).

### Describe the context.

As part of Digital Prison Reporting I'm working on reporting data reconciliation metrics in to Cloudwatch. We want these to be picked up by the integration and available in Grafana.

### Value / Purpose

This will enable us to use these metrics in dashboards/alerts in Grafana.

**Comment by simon-pope** [comment]
For amigos

**Comment by jacobwoffenden** [comment]
Hi @tom-ogle-moj,

Apologies for the delay - this has been added.

Cheers
