### ISSUE TITLE
🔗 Attach QuickSight to VPC

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#5736]
### User Story

As an Analytical Platform engineer
I want our QuickSight instance in Analytical Platform Compute to be connected to the Analytical Platform Compute VPC
So that it can reach any data sources available on the corporate network

### Value / Purpose

Some data sources, like an RDS instance in Cloud Platform for example, are not exposed to the internet.

If our QuickSight instance is connected to our VPC, then when https://github.com/ministryofjustice/modernisation-platform/issues/7313 is complete, QuickSight should be able to route to internal resources.

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Proposal

Connect QuickSight to VPC

### Additional Information

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_vpc_connection

### Definition of Done

- [ ] Policy, role and security groups created
- [ ] QuickSight VPC connection created in private subnets

**Comment by YvanMOJdigital** [comment]
to enable cat team to complete this: https://github.com/ministryofjustice/find-moj-data/issues/965

**Comment by jacobwoffenden** [comment]
MP's platform VPC has been RAM shared with APC: 
- https://github.com/ministryofjustice/modernisation-platform/pull/8373
- https://github.com/ministryofjustice/modernisation-platform/pull/8374
- https://github.com/ministryofjustice/modernisation-platform/pull/8375

**Comment by jacobwoffenden** [comment]
Connected to RDS validated https://mojdt.slack.com/archives/C06UQ5HSR25/p1731401281358729?thread_ts=1731339904.580809&cid=C06UQ5HSR25
