### ISSUE TITLE
Spike: Design for live preview of VS code

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#5774]
### Proposal

We should see if the simple browser in vs code actually works first

1. Add a new server block to NGINX similar to https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-nginx-proxy/blob/main/src/etc/nginx/nginx.conf.template#L158 but listening on n+1 port and exposing another upstream port e.g. 8081
    * I suspect an update to https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-nginx-proxy/blob/main/src/opt/lua-scripts/auth0-login.lua#L8 needs to be made to accept a new hostname 
2. Update the deployment and service to surface this new proxy port
3. Expose this via a new ingress `${USERNAME}-${CDE_TOOL}-tunnel.${CDE_DOMAIN}`

### Definition of Done

**Comment by jacobwoffenden** [comment]
Initial thought is:

1. Add a new server block to NGINX similar to https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-nginx-proxy/blob/main/src/etc/nginx/nginx.conf.template#L158 but listening on n+1 port and exposing another upstream port e.g. 8081
    * I suspect an update to https://github.com/ministryofjustice/analytical-platform-cloud-development-environment-nginx-proxy/blob/main/src/opt/lua-scripts/auth0-login.lua#L8 needs to be made to accept a new hostname 
2. Update the deployment and service to surface this new proxy port
3. Expose this via a new ingress `${USERNAME}-${CDE_TOOL}-tunnel.${CDE_DOMAIN}`

**Comment by jacobwoffenden** [comment]
Done as part of https://github.com/ministryofjustice/analytical-platform/issues/4167
