### ISSUE TITLE
📖 Enable MWAA to read ECR in data-engineering-prod

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#5775]
### User Story

Data engineers would like to be able to pull images from Data Engineering ERC repos. 

### Value / Purpose

Giving people access to this will, as per @jhpyke would make data engineers more likely to test their DAGs and build development version of their images

### Useful Contacts

@jhpyke 

### User Types

Data engineers, DAG writers

### Hypothesis
If we enable this functionality, data engineers will be more likely to produce development image.

### Proposal

Amend the script that generates airflow roles to add the role as a pusher/puller to a specific ECR repo. This might need [iam_builder](https://github.com/moj-analytical-services/iam_builder) release.

### Definition of Done

- [ ] Documentation has been written / updated
- [ ] Code amended
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Follow-on stories raised

**Comment by YvanMOJdigital** [comment]
@julialawrence Do we want to do this???

**Comment by julialawrence** [comment]
We are going to take the original FR as an airflow migration requirement.
