### ISSUE TITLE
Spike: AP Control Panel API access

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/analytical-platform#5777]
### User Story

As a AP app owner
I want to get access to the Control Panel API
So that I can make use of endpoints that list information about my app owners

### Value / Purpose

See parent feature request

### Useful Contacts

See parent feature request

### User Types

App owners/admins

### Hypothesis

If we... allow access to the Control Panel API's from user apps
Then... we will improve our service for app owners and their users

### Proposal

In summary:
- Make use of [Auth0 machine-to-machine authorization](https://auth0.com/blog/using-m2m-authorization/) to allow apps to request an access token to the Control Panel API via Oauth 2.0 client credentials grant flow
- The returned token can then be used to interact with specific endpoints related of the Control Panel API

To do this we will need to:
- Add a feature to the control panel to allow app admins to create a M2M application in Auth0 for their webapp. This can work similarly to how we allow app admins to create client credentials for authentication via a button.
- Return the client credentials to the app admin, so that they can use them to generate an access token via Auth0. I can see a couple of options here:
   1. Store them as secrets in their GitHub repository, so that they can be deployed as env vars within their application (this method is preferred, but would restrict their use to only within the app)
   2. Make them visible to the user in their "Manage app" page in Control Panel (less secure, but the credentials could then be used outside of the app)
- Consider which endpoints we want to grant apps access to. Initially, to meet the requirements of the feature request, I propose this should only be:
  - `retrieve-app` endpoint: /api/cpanel/v1/apps/<res_id>/ (we will need to expose an apps `res_id` field to app admins in Control Panel)
  - `appcustomers-list` endpoint : `/api/cpanel/v1/apps/<uuid:res_id>/customers/`
  - A new endpoint to add a customer to their app
  - A new endpoint to remove a customer from their app 
- Ensure that there is sufficient validation on each endpoint so that they are only accessible for the apps related to the M2M application. We should be able to find this out from the JWT in Control Panel when receiving a request, by using the `sub` and linking this to the App when the M2M is generated.
- Provide detailed user guidance on how to create their M2M application, generate and use the access token. We can also rely on the Auth0 documentation for part of this.

### Additional Information

Some links from initial discovery into the ticket:

Related to identifying the M2M app making the request 
- https://community.auth0.com/t/sub-claim-format-for-m2m-tokens/39451/3
- https://auth0.com/docs/get-started/apis/scopes/sample-use-cases-scopes-and-claims

### Definition of Done

- [x] Proposal implemented
- [ ] Deployed and made available to test with the FR user

**Comment by michaeljcollinsuk** [comment]
Update from 4/11/24:

I have been able to create a M2M application programatically using the Auth0 management API [create client endpoint](https://auth0.com/docs/api/management/v2/clients/post-clients).

I can then link the application (client) to the Control Panel API auth0 entity, [using the create client grant endpoint](https://auth0.com/docs/api/management/v2/client-grants/post-client-grants).

This resolves the initial blocker of registering M2M applications programatically, as we should be able to implement this as a feature triggered on the "Manage app" page.

I am now looking into object level permissions in Django Rest Framework. Relevant links:
https://github.com/dfunckt/django-rules#permissions-in-django-rest-framework
https://github.com/dfunckt/django-rules#permissions-in-models

**Comment by michaeljcollinsuk** [comment]
Update from 8/11/24:

Draft PR open https://github.com/ministryofjustice/analytics-platform-control-panel/pull/1384

Next steps:
- Consider how to reveal client secret to users (can pull this from Auth0 if we dont want to store it)
- Update the UI to display all relevant details to users such as:
  - The `res_id` for the app to be used with app endpionts
  - API url? Or link to API documentation?
  - Available endpoints?
- Update permissions check on the API view that lists app customers

**Comment by michaeljcollinsuk** [comment]
Considered three options for displaying the created client secret to users:

1. Store the secret in the CP database. Display it to app admins, optionally via a show/hide button
2. Don’t store the secret in the CP database. Display it to app admins, via a show/hide button, that makes an external call to auth0 to get the secret when clicked.
3. Don’t store the secret in CP database, display the secret once only after the M2M client is created. Add “refresh client secret” button that user can use to generate new secret, which is displayed once only. Existing client secret can be accessed via Auth0 portal if absolutely necessary.

After discussing with the team, decided to go with option 3.

**Comment by michaeljcollinsuk** [comment]
Bugfix PR following testing in dev https://github.com/ministryofjustice/analytics-platform-control-panel/pull/1403

**Comment by michaeljcollinsuk** [comment]
UPDATE:
- Bugfix PR merged and deployed to dev for testing

TODO:
- Deploy to prod, where creating M2M client is disabled by a feature flag but can still be tested
- Create new permissions in Auth0 for the Control Panel API application
- Contact original FR user, get them to test. We may need to enable the feature for only this user to do this

**Comment by michaeljcollinsuk** [comment]
Deployed to prod. Will create follow up ticket for next steps including testing by original FR user.
