### ISSUE TITLE
📖 QuickSight Guidance and Documentation

### ISSUE THREAD

**Issue by simon-pope** [ministryofjustice/analytical-platform#5783]
### User Story

**As a** new or inexperienced QS user
**I expect** to get guidance on how to navigate through QuickSight
**So that** I can access my AP data quickly and effectively. 

### Value / Purpose

- "First impressions" of new QS users will be improved if guidance on how to get started is available in CP
- Reduce support requests that focus on "how do I" in QS

See Issue No's 16 and 18 in [QS Insights to Actions](https://docs.google.com/spreadsheets/d/1NGfawP4OtodvoxdRXE9dvTjyetWYlNENWOYt7P7mm6Y/edit?gid=0#gid=0)

### Proposal

Create walk through of how to create a data set. If we can't write point them to most concise explaination 

### Definition of Done

- [ ] Guidance available in CP for QS
- [ ] Validated by UR that it adds value and allows users to achieve what they want to do

**Comment by tom-webber** [comment]
Overview/structure: [google doc](https://docs.google.com/document/d/1h6lft2IWB2eImFf6_Vd6DOFkLU-FNZIC0yJncmCimOc/edit?tab=t.96nxkrbla21l#heading=h.liue889mw7k7), [Slack thread](https://mojdt.slack.com/archives/C04M8224WCV/p1733839884290789?thread_ts=1733839808.982359&cid=C04M8224WCV)
