### ISSUE TITLE
📖 Design and Build a Testing Pipeline for Deployments

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#5798]
### User Story

As a maintainer of Create a Derived Table
I need/want/expect to be able to test and validate that package upgrades will not impact current users significantly before we roll them out.
So that we can have a robust test of all major functionality to quality assure package updates.

### Value / Purpose

This will allow us to be more responsive in updating and keeping updated the tool, as it will allow us to know whether any updates to packages introduce breaking changes without having to do intensive manual testing.

### Useful Contacts

@jhpyke, Data Modelling Team

### Hypothesis

If we... build a testing pipeline
Then... we will be able to update all our packages to the latest compatible versions.

### Proposal

To achieve this, we should create a new pipeline in a new domain. It (and it's domain) should have a name that indicates that it's an internal testing database, and should not put it in an area that will be accessible to current users.

This pipeline should:
- Construct an Iceberg table
- Construct a hive table
- Take suggestions from data modellers on key tables from existing pipelines to build/test against.
- Use major macros from transform_table
- Run dbt tests (base these on tests on chosen source tables)
- Take less than 30 mins to run end-to-end (lower is better!)
- Only run against the `sandpit` target

While building this pipeline, it's important to keep the number of runs to a minimum while using real data, as this can degrade user performance. This pipeline will normally only need to run when we have pending package versions, so usually only a couple of times in a given day. 

Ideally, this pipeline should trigger on PRs that update either `requirements-sandpit.txt` or `requirements.txt` and run a deployment when those files are touched to prove the changes proposed are non-destructive.

### Definition of Done

- [x] New domain for developer_sandpit is made
- [x] New set of models exist in that domain to test key functionality detailed in ticket
- [x] Existing 'deploy sandpit' github action is modified to deploy new set of models.
- [x] Changes to the requirements files trigger deployment.
- [x] Ensure bucket life cycling deletes the data

**Comment by jhpyke** [comment]
https://asdslack.slack.com/archives/C03J21VFHQ9/p1729757784797299

Discussion with data modellers on suitable candidate tables

**Comment by jnayak-moj** [comment]
Work in progress. As part of building the test pipeline, we are building and will test both iceberg and hive table types as target. So I have chosen 6 models from stg_delius database. So I had built these models now. I am adding data tests for these models.

**Comment by jnayak-moj** [comment]
I have added few data tests to the test pipeline and I am currently testing those functionality.

**Comment by jnayak-moj** [comment]
I have added few generic test macros to the pipeline which does the data tests for the test pipeline. The build is passing. 
I will have a catch up with Jacob on the next steps.

**Comment by jnayak-moj** [comment]
I have put the test pipeline in the github workflow deploy-sandpit and I am currently testing the workflow.

**Comment by jnayak-moj** [comment]
Currently testing the github action(deploy-sandpit) in the sandpit DPAT env. Making necessary changes to the skip logic and testing the workflow.

**Comment by jnayak-moj** [comment]
I am testing the workflow that PR should trigger the deployment only when changes to the requirements file. It should skip all the deployment steps if there are changes in other files in the repo but not in the requirements file.

**Comment by jnayak-moj** [comment]
The build skip logic.
1. when changes in both requirements.txt and requirements-sandpit.txt > install requirements.txt only
2. When only changes in requirements.txt > install requirements.txt
3. When only changes in requirements-sandpit.txt > install requirements-sandpit.txt
4. When changes to other requirements file other than requirements.txt and requirements-sandpit.txt > skip all the steps
5. When no changes to any requirements file but other source code changes> skip all the steps

**Comment by jnayak-moj** [comment]
1. when changes in both requirements.txt and requirements-sandpit.txt > install requirements.txt only
![Image](https://github.com/user-attachments/assets/e495d5f3-2e64-450f-b3e6-cf98ed1ca547)
![Image](https://github.com/user-attachments/assets/cf18a170-a0a9-4295-8af1-b47827e0fc78)

**Comment by jnayak-moj** [comment]
2. When only changes in requirements-sandpit.txt > install requirements-sandpit.txt
![Image](https://github.com/user-attachments/assets/12664ba1-5851-42f7-9c80-877d06f7955f)
![Image](https://github.com/user-attachments/assets/48f806fa-fa51-4cf9-a475-77c305b31b60)

**Comment by jnayak-moj** [comment]
3. When only changes in requirements.txt > install requirements.txt
![Image](https://github.com/user-attachments/assets/49a86441-c6f6-403e-9c73-9c2d0ddff9cf)
![Image](https://github.com/user-attachments/assets/3b6b3546-69c5-40c8-85b3-d340a55b45f0)

**Comment by jnayak-moj** [comment]
4. When changes to other requirements file other than requirements.txt and requirements-sandpit.txt > skip all the steps
5. When no changes to any requirements file but other source code changes> skip all the steps
![Image](https://github.com/user-attachments/assets/dd2d74cc-f0be-4b99-93c3-b38a2494ffe0)
![Image](https://github.com/user-attachments/assets/0d136aa2-b4de-4f1e-9a2f-80dc8d9fe4b0)
