### ISSUE TITLE
🛒 Request AWS accounts for Data Platform

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#58]
Request 3 AWS Accounts from Modernisation Platform

- [ ] Data Platform Management --  for state management (member)
- [ ] Data Platform Networking (member-unrestricted)
- [x] Data Engineering Sandbox B -- for testing cross-account iam (member) [requested](https://github.com/ministryofjustice/modernisation-platform/issues/3400)

**Comment by julialawrence** [comment]
Have requested sandbox-b for data platform. Not requesting any additional ones.
