### ISSUE TITLE
🐞 JupyterLab isn't idling

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#5800]
### Describe the bug.

This morning I logged in to Control Panel and noticed my JupyterLab was running, but I haven't used it this week 🤔

### To Reproduce

1. Launch JupyterLab 3.6.3, specifically [this](https://controlpanel.services.analytical-platform.service.justice.gov.uk/release/67/) variant
2. Leave it

### Expected Behaviour

It should idle after the configured time

### Additional context

Initial thought was that it was affected by this bug https://github.com/ministryofjustice/analytical-platform/issues/4938

**Comment by Emterry** [comment]
Still to do : release updated rstudio and jupyter on control panel

**Comment by Emterry** [comment]
Releases updated on control panel for rstudio and juypterlab to reflect new max_idle_time of 16 hours
