### ISSUE TITLE
📖 Validate new CaDeT testing pipeline by testing dependabot desired changes

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#5855]
### User Story

As a Data Engineer
I need/want/expect to be able to test package upgrades
So that I can keep the product up to date

### Value / Purpose

Following on from #5798, We will want to validate that our testing pipeline is able to deploy with different package versions from the main branch. Currently, dependabot has a number of PRs raised. This ticket looks to collect all those changes into a single PR changing first `requirements-sandpit.txt`, to trigger the testing pipeline. Once the testing pipeline deploys successfully, we will be able to validate that key deployments still work with newer versions.

### Useful Contacts

@jhpyke, Data Modellers

### Proposal

We should try and include all changes EXCEPT any updates to `dbt-` related packages, as these should be more thoroughly validated with users before upgrading.

### Definition of Done

- [x] All compatible dependabot changes are collected into a single PR
- [x] Testing workflow passes
- [x] Changes are deployed to main succesfully

**Comment by jnayak-moj** [comment]
The PR is approved and merged.
