### ISSUE TITLE
📖 Update CaDeT Workflows to resolve node.js warns

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#5856]
### User Story

As a user of CaDeT
I need/want/expect to be able to use workflows without errors/warnings unrelated to my work coming up
So that I'm not confused by them.

### Value / Purpose

Older node.js versions are out of date, and as such should be migrated away from. [This](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/11521684934) [affects](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/11539561393) [a number ](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/10118156608) of our actions, and should be rectified.

### Useful Contacts

@jhpyke

### Hypothesis

If we... update our workflows
Then... the warnings will go away (also our workflows will be more secure)

### Proposal

Identify which steps in our workflows are using node.js, and then find which workflows we use those steps in. Ensure workflows are updated to use newer versions of these actions where appropriate. Check for any major version changes, and check that any functionality we're relying on has not changed. If changes are required to accomodate the newer actions, then use one of our less important workflows (e.g. `Deploy dbt sandpit DPAT`) to ensure that customers will not be disrupted by any versioning changes.

### Definition of Done

- [ ] All action steps using node.js are identified
- [ ] Any using older node versions are updated
- [ ] Changes are tested using a minor action to minimise disruption
- [ ] All actions have parity of functionality with before the update

**Comment by jnayak-moj** [comment]
work is in progress. identified the github workflows where the package version needs upgrade.

**Comment by jnayak-moj** [comment]
I have raised a PR. addressed the PR comments and the PR need to be approved again and then merged to main.
