### ISSUE TITLE
🕵️ Review Analytics Platform Ops repository

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#588]
## User Story

Follow on from https://github.com/ministryofjustice/data-platform/issues/536

As a DevOps/Platform engineer, I want all infrastructure code to be usable and up-to-date

## User Type(s)

DevOps/Platform engineers

## Value

healthy and maintainable infrastruce-as-code

### Proposal

Review code in https://github.com/ministryofjustice/analytics-platform-ops, try and get access to git-crypt, see if you can get it to plan

## Definition of done

- [ ] Access to git-crypt
- [ ] Able to plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jhpyke** [comment]
@jacobwoffenden to update

**Comment by julialawrence** [comment]
We're moving the repo into Data Platform, so it will be reviewed as part of that. Issue raised as #2137
