### ISSUE TITLE
🪐   JupyterLab - `cmake` 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#5901]
As part of the JupyterLab [User Research](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=69334387&issue=ministryofjustice%7Canalytical-platform%7C4607) a user fed back that they wanted the following installed: 
- [cmake](https://cmake.org/) 
- [nbstripout](https://github.com/kynan/nbstripout) 

~Evaluate if we are going to do this or not.~

~If not capture the reasoning in communications for when the image is generally released.~

### Definition of Done

The purpose of this ticket is to install cmake in the JupyterLab image, since this is a specific ask from UR.

**Comment by jacobwoffenden** [comment]
nbstripout makes sense to chuck in jupyterlab because its for notebooks, but might make sense to put in CDE base if we are to encourage users to use VS Code for notebooks

**Comment by Gary-H9** [comment]
Our bias is to not install/manage packages were possible so we will leave this to the users should they need it. Users can install this as per this screenshot.

![Image](https://github.com/user-attachments/assets/aaa96432-4a2a-4d40-91b9-00bba04f28b2)
