### ISSUE TITLE
:broom: Clean out old users and apps - one off

### ISSUE THREAD

**Issue by jamesstottmoj** [ministryofjustice/analytical-platform#5986]
### User Story

As a developer
I want to remove old users and applications
So that there are less users and apps to search through in the control panel.

### Value / Purpose

There are several users who haven't logged into the control panel in over a year. There are also several apps that no longer have a related github repository. Clearing these users and apps will clean up both pages/

### Definition of Done

- [ ] Users that haven't logged in in over a year removed
- [ ] Apps that don't have a related github repo removed

**Comment by YvanMOJdigital** [comment]
followup story for JML automation
