### ISSUE TITLE
VSCode DBT SQL Server Connection

### ISSUE THREAD

**Issue by sandygudgeon** [ministryofjustice/analytical-platform#6031]
### Describe the feature request.

I want to be able to connect to Azure SQL resources, specifically the HMCTS Strategic Data Platform that uses Azure Synapse Analytics.  There is connectivity from MoJAP tools as I can connect to the SQL Pool in SDP using VSCode.  However in the MoJAP VSCode when trying to run DBT there are dependencies that were missing.  The unixODBC library had been installed (thanks Jacob) but it now **needs the 'ODBC Driver 18 for SQL Server' to be installed.**

### Describe the context.

This is to facilitate testing around the OneCrown project, a joint MoJ/HMCTS project to get a consistent Crown dataset across both orgs and platforms.

### Value / Purpose

The OneCrown project is a high priority & high profile project for both MoJ & HMCTS and will repair reputational damage and enable delivery of published statistics.

### User Types

Analysis & Data Engineers

**Comment by simon-pope** [comment]
Hi @sandygudgeon , thanks for this. Are you able to attend the Feature Request forum on 18/10 at 3pm to present the request and allow the team the opportunity to pose any questions so that the ask is fully understood?

**Comment by simon-pope** [comment]
@sandygudgeon I've caught up with the team and there's no need to attend the request forum as we have all the information we need.

**Comment by jacobwoffenden** [comment]
Visual Studio Code [2.6.0](https://github.com/ministryofjustice/analytical-platform-visual-studio-code/releases/tag/2.6.0) released generally
