### ISSUE TITLE
📋 Make nginx-proxy-jupyter ecr-repo public and push to GHCR

### ISSUE THREAD

**Issue by Emterry** [ministryofjustice/analytical-platform#6087]
### Describe the sub-task.

As part of the migration the repos consuming the workflows should be made public and migrated to GitHub Actions hosted runners and GHCR

### Steps to Address

- [x] use Gitleaks to scan image to check for vulnerabilities 
- [ ] migrate to GHCR

**Comment by BrianEllwood** [comment]
gitleaks detect --source .

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

4:19PM INF 54 commits scanned.
4:19PM INF scan completed in 43.7ms
4:19PM INF no leaks found

**Comment by BrianEllwood** [comment]
No need to migrate as superseded
