### ISSUE TITLE
📖 Allow AP Users Access to QuickSight via Control Panel

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#6118]
### User Story

As a AP User, I would like to be able to access QuickSight from within the Control Panel without requesting superuser permissions.

### Value / Purpose

We currently have one team using QuickSight via Control Panel and another team have approached to use it for a similar usecase. It isn't feasible to make all of them superadmins, so we need the ability to selectively toggle access similar to how we currently do Bedrock.

### Useful Contacts

@julialawrence

### Proposal

1. Add a checkbox to the user profile page to enable them to see the QuickSight tab
2. Add a link to the documentation on how to set up and manage QS users.

### Definition of Done

- [x] Proposal implemented
- [ ] Code reviewed

**Comment by michaeljcollinsuk** [comment]
Implementation PR merged, release to dev for testing pending
