### ISSUE TITLE
🔈NGINX release communications

### ISSUE THREAD

**Issue by simon-pope** [ministryofjustice/analytical-platform#6152]
### User Story
As a AP user
I want to know the details of upcoming **NGINX** releases and when they have been completed
So that I am aware of any changes that may impact on my work and have time to raise any questions

### Value / Purpose
**Before** an AP release the user base will be informed of the details of the release. The comms will be sent in good time for any questions to be raised with the team, and for users to learn more about the release, as required.  

**After** an AP release the user base will be informed that it has completed successfully and be reminded what is now available and where. The comms will be sent as part of the release process (Definition of Done).  

### Definition of Done
- [ ] All PRs related to release are merged to guidance 
- [ ] Release notes in Github are complete, prior to pre-release comms being sent
- [ ] [User Guidance](https://github.com/moj-analytical-services/user-guidance) is updated to reflect any long lived changes
- [ ] Release date (and time if required) are agreed, along with notice period for users
- [ ] [Pre-release template](https://docs.google.com/document/d/16z3c9AwO31Zbj--ozeO_QlfbL5SVK2bw6qY3d6dpSz8/edit?tab=t.0) is populated and added to ticket
- [ ] [Post-release template](https://docs.google.com/document/d/16z3c9AwO31Zbj--ozeO_QlfbL5SVK2bw6qY3d6dpSz8/edit?tab=t.wryteihtqn02) is populated and added to ticket
- [ ] Pre-release note is sent in #analytical-platform-support channel at agreed date
- [ ] Post-release note is sent in #analytical-platform-support channel after release

### Release templates for completion
**Pre-Release template**
> **Pre-Release Notice**
> 
> AP will be releasing **[version and tool]** on **[release date]**
> 
> This release will include:
> [bulleted list of changes included in release]
> 
> For a complete list of changes see [link to release details in GitHub]
> 
> _Optional_ - **Important:** [include details of breaking changes or any actions the user will need to take pre or post release]
> 
> If you have any questions contact the AP team via #ask-analytical-platform

**Post-Release template**
> **Release Notice**
> 
> AP have released **[version and tool]**
> 
> This release includes:
> [bulleted list of changes included in release]
> 
> For a complete list of changes see [link to release details in GitHub]
> 
> _Optional_ - **Important:** [include details of what users need to do now]
> 
> If you have any questions contact the AP team via #ask-analytical-platform

**Comment by michaeljcollinsuk** [comment]
Due to increasing number of users reporting the 502 Bad Gateway error, we decided to hastily make the CDE NGINX releases have been made available to all users (as "unrestricted" releases in Control Panel).

We released comms to users about the releases being rolled out [via a PagerDuty incident in the support channel](https://mojdt.slack.com/archives/C4PF7QAJZ/p1734455750431779)

We also updated our daily ["Need support?"](https://mojdt.slack.com/archives/C4PF7QAJZ/p1734512412305089) message to include a message specifc to the 502 error, which linked to our [support tracking issue](https://github.com/ministryofjustice/data-platform-support/issues/1036):
> :sad_mac: If you are experiencing a "502 Bad Gateway", please refer to the tracking issue [here](https://github.com/ministryofjustice/data-platform-support/issues/1036)

As such, I dont think it is too late to release pre-release comms, and perhaps this was not necessary this time due to the nature of the releases (bugfix, with no new features).

We may still want to post some post-release comms - I will discuss this with the team at stand up on 19/12/24

**Comment by michaeljcollinsuk** [comment]
Suggested post release comms:

```
AP have released new versions of RStudio and JupyterLab that enables a new auth proxy (referred to as CDE NGINX). These releases resolve the 502 Bad Gateway error that users have been encountering.

The list of newly available releases are:
- RStudio: 4.4.1 - CDE NGINX
- RStudio: 4.2.3 - CDE NGINX
- JupyterLab 3.6.3 (Ubuntu 22.04, CPU: 1, RAM: 12GB) - CDE NGINX
- JupyterLab: 3.1.13, Python: 3.9, Spark: 3.1.1 - CDE NGINX

In addition to the above, high memory releases with the CDE NGINX proxy have been made available to users who previously had access to them. 

In order to avoid the 502 Bad Gateway error we recommend all users upgrade to the CDE NGINX version of the tool that you require via the Control Panel as soon as possible. Older releases will still be available to use, but will be marked as deprecated and will be retired in future.

If you have any questions [please raise a support issue](https://github.com/ministryofjustice/data-platform-support/issues/new?template=analytical-platform-support.yml)
```

**Comment by michaeljcollinsuk** [comment]
Comms published in:
- [AP Support channel](https://mojdt.slack.com/archives/C4PF7QAJZ/p1734606417627259)
- [AP Ask channel ](https://mojdt.slack.com/archives/C06TFT94JTC/p1734606427644109)
- [Ask data engineering](https://mojdt.slack.com/archives/C8X3PP1TN/p1734606437816809)
- PagerDuty maintenance status page
