### ISSUE TITLE
📊 QuickSight Trial Information: Tochi Asangansi

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#6155]
### Use Case Description

Viewing the Find MoJ Data dashboard 
Tochi.Asangansi@justice.gov.uk

### Dataset(s) to Visualise

It's the datahub postgres - the other FMD devs have this access so you can clone theirs

### Are you an Analytical Platform Admin of the S3 Data Warehouse for the Datasource(s)?

No

### Audience Details

- AP users
- MoJ managment

**Comment by murdo-moj** [comment]
Currently dependent on https://github.com/ministryofjustice/analytical-platform/issues/6118

**Comment by julialawrence** [comment]
This has been completed. Tochi has access now.
