### ISSUE TITLE
📖 Install ffmpeg to enable speech-to-text functionality

### ISSUE THREAD

**Issue by simon-pope** [ministryofjustice/analytical-platform#6167]
### User Story

As a VS Code user in the AP
I need the openai whisper model to be installed
So that whisper can be used for our use cases

### Value / Purpose

Enable use of OpenAI whisper as a critical bottleneck for a prisons data science project.

### Hypothesis

If we... [do a thing]
Then... [this will happen]

### Additional Information

From the Feature Request

I would like to be able to use the openai whisper model in python for transcribing audio to text, in VS code on the AP (https://huggingface.co/openai/whisper-large-v3-turbo).
This requires ffmpeg (https://www.ffmpeg.org/), which requires root access for installation on linux.

**Describe the context.**
My team are about to start work on a project to transcribe and translate audio. The current state of the art in this space is the OpenAI whisper model. Unlike their other models (the GPT family), Whisper can be downloaded and run locally. It will be critical for our project to be able to test whisper for our use case. In order to be able to do this, we need to be able to run it on the AP. And to do that, we need ffmpeg :)

### Definition of Done

 - [ ] TBD

**Comment by jacobwoffenden** [comment]
- CDE Base 1.8.0-rc1 released
- VS Code 2.7.0-rc1 released
- VS Code 2.7.0-rc1 restricted release created on Control Panel

**Comment by jacobwoffenden** [comment]
- CDE Base 1.8.0 releases
- VS Code 2.7.0 released generally

**Comment by DomoMKT** [comment]
you can achieve high-quality text-to-speech with extremely low latency by converting your text at [www.nemesyslabs.com](https://www.nemesyslabs.com)!
