### ISSUE TITLE
✨ Access Cloudwatch logs from Airflow

### ISSUE THREAD

**Issue by williamorrie** [ministryofjustice/analytical-platform#6247]
### Describe the feature request.

1. CloudWatch logs subscription filter (for CloudTrail event `StartQueryExecution`)
2. IAM builder extending to cover CloudWatch log groups

See [slack discussion](https://mojdt.slack.com/archives/C8X3PP1TN/p1733312718879479) with @jacobwoffenden for further details

### Describe the context.

Planning a firebreak sprint on w/c 16th Dec, to produce a KPI dashboard for Athena. 

**Related RF's:**
#5849 - mapping GitHub usernames to AD emails
#6207 - Quicksight access

### Value / Purpose

This feature could allow for a more detailed analysis of AP data usage, contributing to a clearer understanding of data access and usage trends.

### User Types

Data Engineers, Data Analysts

**Comment by jacobwoffenden** [comment]
Data Engineering will make the necessary changes to IAM builder. I will close this request as nothing else is required from Analytical Platform.
