### ISSUE TITLE
🧭 Diagrams as Code

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#648]
### User Story

As a Platform Engineer
I want `long-lived` diagrams stored as code in the product or services repository.
So that diagrams are versioned, stored as text (searchable.. actionable, diffed easily, integration for `CI/CD` / automation and in one repository.

### Value / Purpose

- All the products we deploy are stored as code. In every version, we can integrate, apply metadata. This is not true of diagrams of static tools exporting PDF/JPEG/PNG. These ultimately end up dead e.g. not a true reflection of whats deployed so require further investigations (time is money)) and the source files (to actually update the thing) of the diagram are 100% absent 👿 and the source missing 🪦...☠️.
- Gain a structured way of storing these stories/maps for the things we have created for future you and others.
- Can we be more DRY(Don't Repeat Yourself)😐? With Mermaid/UML/Visio/Draw.io you need to create multiple diagrams to show various levels of detail or other sections. Changing Visio/Draw.io can be problematic (I need to add another box.... _shuffles endless lines around..._, this results in the diagrams never being touched after the project is completed usually when whoever created them has gone. 

### Useful Contacts

Rich B

### Additional Information

- Must be easy for all team members! We can have a play-off on learn tech afternoon.
- You can export this [AWS example](https://structurizr.com/dsl?example=amazon-web-services) code to see the language differences e.g. mermaid, dot, UML etc.
- https://github.com/structurizr/dsl provides a context-based (C4 diagramming language) rather than [named boxes and arrows](https://youtu.be/Za1-v4Zkq5E?t=514). 
- HMPPS and LLA use [structurizr](https://structurizr.com/share/56937) [AWS example](https://structurizr.com/dsl?example=amazon-web-services) 🤔 discussion: is this a problem if just creating simpler [deployment diagrams](https://en.wikipedia.org/wiki/Deployment_diagram) vs the added complexity of e.g. using structurizr is there... value in the effort. 
- [Diagrams](https://diagrams.mingrammer.com/) @Gary-H9 as Code lets you draw the cloud system architecture in Python code. [nice AWS example](https://diagrams.mingrammer.com/docs/getting-started/examples)
- [Mermaid MoJO-DNS example](https://mermaid-js.github.io/mermaid-live-editor/view#pako:eNqtV2FT2zgQ_Sue9AtMLBsSKCXT6QwQyOUuhBSn5eZCp6PYcqLGlnySjJsS_vutLDlx4LjjuDIZjySv3u4-Pe2a-0bII9LoNOKEF-EcC-UMrm-ZA3_XJOWKfP0kidiJcSfGKIeh834q_A_OJf_VuYpjGlKclCvG2tHWuw5CH1Z9pohgRK2c3uje7A8TnkcGoJfwKU4s2EjA1lDZ2efR8MFEECY0XMB257YxVyqTHd-PZJTybx5WCZaSYuaBB7-gC-rLDIdE-qPxeHTT_83P8AxmrXZr_3D_4O3eoX-mnTcxi5pDogouFs0-iwWWSuShygW5bRinZVYvSdssGfMyb2tzhqcJiQwJn3mEY86Ic3MyXDn9XmCZmOY0iSibmS0VVRaghxUp8NLOAiLuwIOlBMgAXGc17t3Y9ydK4XCeEqZWJzcBghc7OzCwb8cCM0lV72Z3t86ptawRO6Nqnk-9kKd-ShkFWpY8_pZLBb79iGQJX2ofSM2KiilI5yXBmIyxELyQCCc2y3WINsLtrLej1Y5eL4GDo8ODw3dHB0d-xXPT-mpabpvgoEqqYkaf3rN5DQenE5MWBB_xtLKCnKy4zMqAY6v3U5xgFhLxZeMFQLSX87PAYoX5lEhjfoHFDGI0sOeQKBxDJS_OFKZsLTebg5lZeJDpFeoOg_3yfK67lYcIKzzF0hrrF5Wul8HHgR13rdEjrNZPxGr_BCzgrURZ51pjcXNby1d2etofdo_tOKxY_FIXmsZ84ZWQCscxiojmHkVMomgeZoj-bUl5HGrrf4X6GK39arSnYgHcCy4KLCIi5EQj_KGr12bNosQCRD_iQuFki8CaYe3CamY0RTgCHr2SOU8a2XqWT2_G77x84YNZxVpdeK8Oq664V4PUTEqKVqN8Cuk667r9Z04Ehbu7ckaAO7H9DH70jjiwssWRNqmxUxSFx0IZVgyAhLhIsaKc-VlJBxiP51Q68MOO4jxRNHPACGYJZYuKrydRdq8u92uh6enkZHwVOFCx9r1SqvBUjj4K2PVcsh9zzFSe1pCGV5fBpPv7mcN4Kj3B-b9i_HI5CsptNZR5mklvjVDibS_9IygcQjCsoQ1yqM6T8ll9VcD7rRK5dQrG8r_3P0BFJyG0mbVODZK-kZBgf3g-ngw5QIAsNjdwOxMTgbV-JAWrgllOI90w_DkvkOIIri0DPSFoN3oc0xnUF7TkuUByKRVJpbZSc4KyUpvI3i-JmGlIKJOsitg8MbTjhEP7YpPN98KgXIBvvxnor2prd5gmeEoTqpbmzpTrJEcFkQq1trLaoNYSg0UPp_gHZyXBeMpzSKWQ_qz8DHxUNn1Repdf8Q-_CjnUzb5LYo3vxDRJOm8uLo6P9_Zc2MYXpPOm3W7bMSpopOadVva9the-nFzb213bfV2opO66-q1HrfWo7W4050JTcsujdmspwtD4IN91KYBUKt4n53ZlW4MbCdh8nmyE44UvVWGTfHdA2tHbFyf5BM21KnPLqvOcs1vWcBspgbJDI_hf4F5D3jZATSn0sA4MIxLjPFH6NB7ANM-gY5PziCouGh04N-I2cK54sGRhNTc2XYpnAqdm8eEvstkcVA)
- [Backstage](https://developer-portal.apps.live.cloud-platform.service.justice.gov.uk/catalog/default/api/hmpps-community) is worth watching, great job of rendering [code](https://github.com/ministryofjustice/hmpps-auth/blob/main/hmpps-catalog-info.yaml) inside the repo into diagrams.
- Excalidraw - we are using for our C4 diagrams already see #580 

### Definition of Done
- [ ] Discussed as team 
- [ ] README has been updated
- [ ] User docs on how to diagram have been created
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
Team has elected to use Diagrams for the time being. Should we need to pivot we will revisit this ticket.

**Comment by bagg3rs** [comment]
Have transferred this issue to look at _IF_ we should look at using e.g. Strcuturizer
