### ISSUE TITLE
Investigate integrating CKAN with AAD

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#658]
We need users to be able to authenticate with CKAN during the Hackathon which would be easier to do if they can use their AAD identities.

This is a time-boxed spike: Max 3 hours.

Definition of Done:

* Users can authenticate with CKAN using AAD.

**Comment by julialawrence** [comment]
Timebox for a few hours.

**Comment by jacobwoffenden** [comment]
CKAN has been parked, no longer chasing as potential candidate
