### ISSUE TITLE
Investigate creating a base image

### ISSUE THREAD

**Issue by bogdan-mania-moj** [ministryofjustice/analytical-platform#736]
## Investigation

This is a quick investigation to determine if it's worth creating a docker base image on top of which our specific code can be added, for example if there are additional libraries that are used by all, or most functions.

LE: currently there is no need for a custom base image, all lambda functions are very simple and don't need any additional libraries. moving this over to done can be revisited again in the future if the need arises.

**Comment by jacobwoffenden** [comment]
we've got two on offer already;
https://github.com/ministryofjustice/data-platform/tree/main/containers/alpine-base
https://github.com/ministryofjustice/data-platform/tree/main/containers/ubuntu-base

**Comment by bogdan-mania-moj** [comment]
That's cool, but Lambda functions need specific base images. Amazon provides one that already has everything required for running lambda functions with containers: https://docs.aws.amazon.com/lambda/latest/dg/images-create.html

The images you mentioned will need to be customised to work with Lambda

**Comment by jacobwoffenden** [comment]
Ah, it didn't say Lambda in the title or initial description.

In that case I would suggest using AWS' curated base images https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#runtimes-images-lp the same way this is created https://github.com/ministryofjustice/data-platform/blob/main/containers/daap-athena-load

**Comment by bogdan-mania-moj** [comment]
It's a subtask of an epic that mentions Lambda, but I understand the confusion 😄 

Yes, the plan is to use an AWS curated base image, this ticket is to investigate if it's worth creating our own base image based on that
