### ISSUE TITLE
Athena vs Glue Load

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#782]
what are the tradeoffs between the two? How do the costs differ? Are there limitations with one approach or the other with respect to functionality e.g. limited data quality provision in athena? (for the MVP we want only 1 type of compute, will just Athena suffice?)
Cost implications between them

**Defintion of Done** 

1. Record the decision in confluence 
2. Choose one of the option 
3. Demo the Athena load to TA's

**Comment by LavMatt** [comment]
decision recorded here https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4463755568/MVP+compute+method
