### ISSUE TITLE
Change the backend storage architecture to have separate data lake style zones

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#784]
Change the backend storage architecture to have separate data lake style zones (eg landing, raw, refined, curated) https://playbook.hackney.gov.uk/Data-Platform-Playbook/playbook/elements-of-the-platform/data-lake
Introduce the landing bucket layer to the pipeline.

**Definition of Done** 

* separate buckets for landing and raw/curated/Fail (3 buckets)
* Alter the base pathing object to reflect the new bucket structure
* Create new copy lambda to copy objects from landing to raw
* investigate and test disabling ACLs and potentially implement. See https://docs.aws.amazon.com/AmazonS3/latest/userguide/acls.html

See the diagram below 

![Image](https://github.com/ministryofjustice/data-platform/blob/main/docs/source/documentation/platform/images/daap-data-flow-architecture.excalidraw.png?raw=true)

**Comment by murdo-moj** [comment]
Just doing #1755 as a separate PR first, so I can use the pathing in the landing to raw lambda I'm making
