### ISSUE TITLE
Investigate how we integrate the athena data load option into the data product registration.

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#785]
I want my data product to be processed with athena - How do I input this? How does this get executed in AWS? Can we automatically choose which compute type to use for a give data product? (athena or glue) (just investigate). After investigation a ticket would be implemented based on this. 

**Definition of done** 
Solution recorded in confluence

**Comment by LavMatt** [comment]
For the initial MVP we will not be offering an option and will use Athena as the default and only processing option. Hence this (for the time being) is not required.
