### ISSUE TITLE
User research on metadata

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#787]
User research on metadata -
 Explicitly add process guide/confluence page for verifying information asset owners are happy to be IAOs upon registration of a data product.

https://github.com/agile-lab-dev/Data-Product-Specification

Put the question back to others in the wider data platform: ‘what are we obligated to do with regard to this’?

**Current plan as follows**
Some examples of metadata 
https://github.com/agile-lab-dev/Data-Product-Specification

https://github.com/ministryofjustice/data-platform-products/blob/main/data-products/example_prison_data_product/metadata/00-specification.yml

https://github.com/ministryofjustice/data-platform-products/blob/main/data-products/example_prison_data_product/metadata/01-governance.yml
List the minimum required metadata (Murdo help with it)
Liaise with Catalogue team ( @Julia Lawrence) for required metadata for data catalogue
List the metadata that we can automatically generate (Murdo - to provide some suggestions on that)
Richard to discuss with @Edwin Bajomo and @Alex von Feldmann to liaise with IAO's to gather feedback and provide us 

**Definition of done** 
1. Kick start with some user research 
2. Gather some feedback and use it to deisgn meta data registration with the outcome of the issue

**Comment by murdo-moj** [comment]
I started a metadata spec, with a terms glossary
https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/
