### ISSUE TITLE
Authenticating With Airflow UI

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#791]
Investigate if tokens generated by the Airflow UI are valid IAM users in different accounts. 

Identify additional permissions required. 

If valuable, investigate whether the UI can be integrated with an (external) identity provider.

This requires a creation of another SSO permission set with an iam policy that has already been defined. Creating the permission set needs a PR in the root account repository and assignment to a github group in MP requires adding a link in the environment json as well as introductions of rego tests for a new permission level.

Linked below is the pull request to implement it.

TODO:

- [x] Map `data-platform-apps-and-tools-airflow-users` to `modernisation-platform-mwaa-user`
- [x] Add a user to `data-platform-apps-and-tools-airflow-users`

**Comment by jacobwoffenden** [comment]
# Plan
GitHub group (data-platform-airflow-users) -> AWS IAM Identity Center (modernisation-platform-data-platform-airflow-users) -> AWS IAM Policy (data-platform-airflow-users)

**Comment by julialawrence** [comment]
Is this still blocked?

**Comment by jacobwoffenden** [comment]
Moving to blocked while we decide if we should bump to next sprint

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5235

**Comment by jacobwoffenden** [comment]
Access to MWAA tested using `modernisation-platform-mwaa-user` permission set

Screen capture https://github.com/ministryofjustice/data-platform/assets/15148673/0e973312-77e6-4e1e-b785-1988b3381584
