### ISSUE TITLE
📮 GOV.UK Notify account for Data Platform

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/analytical-platform#81]
## User Story

As a Data Platform user
I want to receive notifications about my data or dissemination products via email if I prefer that over GitHub or Slack notifications.

## Value

- Notify provides an easy and convenient API for sending templated emails
- Users will see professionally formatted notifications with a trusted sender (and valid reply-to) address 

We are not proposing to include SMS notifications at this stage as this incurs additional cost.

## Definition of done

- [x] GOV.UK Notify account created
- [x] core team added as account administrators
- [x] dev/test and prod API keys generated
- [ ] API keys stored within AWS secrets manager within DP accounts (consistent secret name across accounts so can be used as env vars)
- [ ] a couple of sample email templates created with appropriate variables (e.g. data product name / URI)
- [ ] test emails sent & received

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
Created Ministry of Justice Data Platform GOV.UK Notify service and added @jemnery, @bagg3rs and @julialawrence as team members

**Comment by jemnery** [comment]
Thank you 👍

**Comment by jacobwoffenden** [comment]
Requested service be set to "live" by GDS

**Comment by jacobwoffenden** [comment]
> Requested service be set to "live" by GDS

This is done

**Comment by jacobwoffenden** [comment]
API keys generated for "development" (Test – pretends to send messages), "internal" (Team and guest list – limits who you can send to) and "production" (Live – sends to anyone). Added to Data Platform's 1Password
