### ISSUE TITLE
📝 Create paper for Tech Services TDA on unlocking AuthZ for MoJ

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#817]
## User Story

As a Justice Digital employee
I expect our main identity service to provide systematic access control
So that we and other teams can make use of existing system rather than all teams managing this themselves.

## Value

Have one place where identity and access management is controlled.

## Definition of done

- [ ] One pager and presentation/diagram created for TDA and all their fears alleviated.
- [x] #943
- [ ]  Outcome documented in ADR and issues raised to complete work in AAD prod

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by julialawrence** [comment]
We don't think we need this because we're using delegated permissions for now and don't require the app to have any permissions itself.
