### ISSUE TITLE
💬 Decide how we should operate AWS QuickSight

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#833]
## Background and context

AWS QuickSight is currently offered on a best endeavour basis.

It looks to have been provided at some point, but is not an official Analytical Platform component.

Recently we've had a few support requests regarding IdAM, and I'm wondering if it's worth revisiting if/how we provide this service.

## User types impacted

Data (consumers) and Platform (administration) Engineering teams

## Requested Feature

Formalisation of the administration and support of AWS QuickSight

## Your usecase

Provide clarity to the consumers and administrators on the status of the service

## Reference:

Analytical Platform technical documentation: https://silver-dollop-30c6a355.pages.github.io/documentation/80-archived-operations-handbook/40-common-user-support/Quicksight.html#how-to-access-quicksight-as-an-author

Recent support issue: https://github.com/ministryofjustice/data-platform-support/issues/126

**Comment by bagg3rs** [comment]
I am reopening this issue as we need to investigate and have an alternative BI offering and this one is part of AWS which makes securing access much easier. This also relates #1687

**Comment by julialawrence** [comment]
This needs to either cover the new QS or closed.
@jacobwoffenden
