### ISSUE TITLE
🔃 Dynamic Reteaming - Investigate how this could work for our teams and beyond

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/analytical-platform#863]
## User Story

> After a chat with @ChikC on having one backlog for Data Platform e.g. CI/AP/LABs, Chike mentioned Heidi Helfand and her book [Dynamic Reteaming](https://www.heidihelfand.com/dynamic-reteaming/) and I ended up watching her talk [here](https://www.youtube.com/watch?v=pDkM1-QeW4E) which solidified my thinking that this should be investigated and documented.

As a Data Platform team member
I want new members of our team to be up and running as soon as possible
So that we can have an efficient onboarding and knowledge transfer within our ever changing teams

**What this is not about**

- Musical chairs e.g. bouncing everyday between different teams
- Forcing people to move
- moving teams if you don't like the work

## Value

_"Bounded and stable membership is less and less the norm as teams become more dynamic and are frequently overlapping"_ 

People will leave, how do we get ahead of this inevitable problem?
To cope with changes in the team composition

## Questions / Assumptions / Hypothesis
How will people feel about working in different teams
Could this work across wider P&A hosting/platform teams

### Hypothesis
If we embrace dynamic reteaming
Then we will make sure that we are spreading domain knowledge, we can do this by pairing up and mixing up DP teams and making sure that the guidance is available which will improve our onboarding. 

### Proposal
Create a lightning talk on Dynamic Reteaming and get a response from team.

## Definition of done

- [ ] create a lightning talk ⚡️
- [ ] presented 🎥
- [ ] create issue to in act if ✅ 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Gary-H9** [comment]
Worth noting the devcontainer in this piece of work
