### ISSUE TITLE
Investigate Data product Versioning

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#864]
Bringing in data product versioning when there is schema changes would be useful mechanism 

1. Investigate options of how we could implement it 
2. Record the solution in confluence 
3.  ~~Amend directory structure of data product storage to show data product versions. Amend the connected components such as api , lambda etc to reflect the changes for versioning~~

DOD:
Current solution should work with the changed implementation

**Comment by LavMatt** [comment]
as this is closely linked with the schema versioning, and the discovery of schema and data product has been done together, it makes sense to have a new implementation ticket
