### ISSUE TITLE
 Check data product exists when requesting a presigned url for a data product

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#865]
Bug - Check data product exists when requesting a presigned url for a data product

Current behaviour: A presigned url will be made to upload to a directory. This directory includes a data product name. The data product name does not get checked for if a corresponding code/metadata entry exists.

Expected behaviour: Check for the existence of a data product with the name supplied. If it does not exist, the presigned url request should return an error detailing this.

**Comment by murdo-moj** [comment]
I am saying that a data product can "exist" when it has a directory in the `/code` directory of the raw bucket area

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-platform/pull/1162

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-platform/pull/1162

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/3098
