### ISSUE TITLE
Environments for deployment 

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#867]
Create environments ( dev, preprod and prod ) for MVP development 

Three **different account** should be created for Data-As-A-Product ( Name option  can be discussed)
sandbox account will be for local testing

1. Dev 
2. Preprod
3. Prod 

Create a few issues with MP in github to create environments
Liaise with MP and create the three accounts 

We will need to deploy changes in terraform through dev, preprod and prod via github workflows. Some of these pipelines will be set up by MP. Understand how much of the deployment pipeline comes set up by MP, and what we need to do ourselves.

**Deployment strategy should be gated deployment - which requires mannual approval move to environment.  ***
https://dsdmoj.atlassian.net/wiki/spaces/DE/pages/4226646354/ADR-2+Use+gates+in+the+deployment+pipeline

**Comment by murdo-moj** [comment]
After we have our environments, we need to set up a deployment strategy. This will define:
- how to make changes to code
- how to test changes to code in an automated way
- how to promote changes to code through environments
- how and when to version the codebase, for the purpose of making clear changes to the data product API and infrastructure. Will we have separate versioning for the API and for the infrastructure? Example: we deploy a host of changes from a sprint to prod, to release new features such as a data out endpoint, and the version of the data platform increments from v2.6 to v3.0


Some capabilities (eg automated application testing) in our deployment won't yet be built. We need to make tickets to fill in the gaps in our deployment and then create the resources.

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/4794

**Comment by murdo-moj** [comment]
It's getting done in the next sprint for mod platform
