### ISSUE TITLE
Setup message broker and queue on AWS

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#965]

**Comment by mitchdawson1982** [comment]
- [X] Message queue created and deployed for S3
- [X] Message queue created and deployed for IAM
- [X] Message queue created and deployed for AUTH
- [X] Python producer and consumer written and tested
- [X] Initial SQS IAM policy deployed for S3
- [X] Initial SQS IAM policy deployed for IAM
- [X] Initial SQS IAM policy deployed for AUTH
- [] IAM Policy further configuration
- [] Commit and Merge Terraform

**Comment by ymao2** [comment]
completed this task
