### ISSUE TITLE
Develop recovery mechanism for event driven loads

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#998]
Need to have a mechanism in place for a couple of scenarios:

1. The load process has not been triggered for a batch of uploaded files and we need to trigger these files to be run through the load process via a method other than an object created notification.
2. Disaster recovery scenario. We need to re-create an entire data product from the raw history files.

This is also relevant to the legacy `register-my-data` process which now used event driven triggers.

**Definition of done**
- Define how this would be orchestrated
- Develop initial python code that would allow the above scenarios to be met

**Comment by murdo-moj** [comment]
To recreate an entire data product:

- Create a lambda function which takes as an input a data product name.
- It is only triggered manually
- Check if the data product exists
- Drop the existing tables for that data product
- Delete the curated parquet files for that data product
- Feed all data files in raw history through the athena load process again

**Comment by murdo-moj** [comment]
For rerunning selected files which have failed, this should be another lambda manually triggered with an input of a data product name:

- Create a lambda function which takes as an input a data product name.
- It is only triggered manually
- Check if the data product exists
- Compare timestamps in raw_history and curated
- Find timestamps present in raw_history and not in curated
- Feed all those data files in raw history through the athena load process again

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-platform/pull/1307/files

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/data-platform/pull/1307

**Comment by murdo-moj** [comment]
Increasing the 1000 invocations limit for lambda requires a request https://repost.aws/knowledge-center/lambda-concurrency-limit-increase

Probably not something we want to bother with

**Comment by murdo-moj** [comment]
these are the data load times from matts presentation [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFZsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19eef77dc5ed1582e7ddb498d09712725f5a1b59/image.png)
